"""Tests for tools/data/inventions.py and tools/build_inventions.py.

    python -I -m unittest discover -s tools/tests -v
"""

import collections
import importlib.util
import re
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(TOOLS))


def load_data():
    spec = importlib.util.spec_from_file_location("aov_inventions_data", TOOLS / "data" / "inventions.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.INVENTIONS


INVENTIONS = load_data()
KEYS = [i["key"] for i in INVENTIONS]


class DataTests(unittest.TestCase):
    def test_sixty_unique_inventions(self):
        self.assertEqual(len(INVENTIONS), 60)
        self.assertEqual(len(set(KEYS)), 60)

    def test_category_counts_match_research_doc(self):
        counts = collections.Counter(i["category"] for i in INVENTIONS)
        self.assertEqual(counts, {"economic": 16, "military": 26, "society": 18})

    def test_every_category_tier_pair_is_populated(self):
        pairs = {(i["category"], i["tier"]) for i in INVENTIONS}
        self.assertEqual(len(pairs), 9)

    def test_fields(self):
        for i in INVENTIONS:
            with self.subTest(i["key"]):
                self.assertRegex(i["key"], r"^[a-z0-9_]+$")
                self.assertIn(i["tier"], (1, 2, 3))
                self.assertRegex(i["icon"], r"^Artf_\w+\.dds$")
                self.assertTrue(i["modifier"].strip())
                self.assertTrue(i["name"] and i["desc"])
                self.assertNotIn('"', i["name"] + i["desc"])

    def test_maa_unlocks(self):
        maa = {i["key"]: i["maa"] for i in INVENTIONS if i["maa"]}
        self.assertEqual(maa, {
            "prototype_tanks": "aov_prototype_tanks",
            "war_golems": "aov_war_golems",
            "damestear_reactor_megacannon": "aov_damestear_megacannon",
        })

    def test_locks(self):
        self.assertEqual(sum(1 for i in INVENTIONS if i["faith"]), 8)
        self.assertEqual({i["key"] for i in INVENTIONS if i["gnome_only"]},
                         {"conversation_calibrator", "coddorran_powered_exosuit", "gu_boats", "prefabricated_city_constructors"})

    def test_no_keys_tiger_rejects_in_character_modifiers(self):
        # travel_speed is a travel-plan modifier and cultural_acceptance_gain_mult a culture modifier
        for i in INVENTIONS:
            keys = set(re.findall(r"^\s*([a-z_]+)\s*=", i["modifier"], re.M))
            with self.subTest(i["key"]):
                self.assertFalse(keys & {"travel_speed", "cultural_acceptance_gain_mult"})

    def test_sorted_by_category_tier_key(self):
        order = {"economic": 0, "military": 1, "society": 2}
        self.assertEqual(INVENTIONS, sorted(INVENTIONS, key=lambda i: (order[i["category"]], i["tier"], i["key"])))


import build_inventions as bi  # noqa: E402
import build_hud_override  # noqa: E402  (brace_delta)


def balanced(text):
    depth = 0
    for line in text.split("\n"):
        depth += build_hud_override.brace_delta(line)
        if depth < 0:
            return False
    return depth == 0


def top_level_blocks(text):
    return re.findall(r"^([A-Za-z0-9_]+) = \{", text, re.M)


class ValidateTests(unittest.TestCase):
    def test_real_data_is_valid(self):
        bi.validate(INVENTIONS)

    def test_rejects_duplicate_key(self):
        with self.assertRaises(bi.GeneratorError):
            bi.validate(INVENTIONS + [dict(INVENTIONS[0])])

    def test_rejects_unknown_faith(self):
        bad = dict(INVENTIONS[0], faith="faith = faith:made_up")
        with self.assertRaises(bi.GeneratorError):
            bi.validate([bad])

    def test_rejects_bad_category(self):
        with self.assertRaises(bi.GeneratorError):
            bi.validate([dict(INVENTIONS[0], category="magic")])


class ScriptOutputTests(unittest.TestCase):
    def test_all_script_outputs_balanced_and_headed(self):
        for name in ("modifiers", "triggers", "values", "effects", "custom_loc"):
            with self.subTest(name):
                text = getattr(bi, name)(INVENTIONS)
                self.assertTrue(text.startswith("# Anbennar Overhaul: generated by tools/build_inventions.py"))
                self.assertTrue(balanced(text))

    def test_modifier_per_invention_with_category_icon(self):
        text = bi.modifiers(INVENTIONS)
        self.assertEqual(top_level_blocks(text), [f"aov_invention_{k}" for k in KEYS])
        self.assertIn("aov_invention_sparkdrive_rifles = {\n\ticon = martial_positive\n\tgunpowder_damage_mult = 0.15\n}", text)

    def test_triggers_per_invention(self):
        names = set(top_level_blocks(bi.triggers(INVENTIONS)))
        for k in KEYS:
            for suffix in ("visible", "unlocked", "available", "discovered", "active", "discoverable", "activatable", "offered"):
                self.assertIn(f"aov_invention_{k}_{suffix}", names)
        for c in bi.CATEGORIES:
            self.assertIn(f"aov_inventions_{c}_discoverable", names)
            self.assertIn(f"aov_inventions_{c}_unoffered_discoverable", names)
            for t in (1, 2, 3):
                self.assertIn(f"aov_inventions_t{t}_{c}_activatable", names)
        for n in ("aov_inventions_any_discovered", "aov_inventions_any_discoverable", "aov_inventions_any_activatable",
                  "aov_inventions_t1_activatable", "aov_inventions_t2_activatable", "aov_inventions_t3_activatable"):
            self.assertIn(n, names)

    def test_unlocked_uses_tier_era(self):
        text = bi.triggers(INVENTIONS)
        for i in INVENTIONS:
            block = re.search(rf"^aov_invention_{i['key']}_unlocked = \{{\n(.*?)\n\}}", text, re.M | re.S).group(1)
            self.assertIn(bi.ERAS[i["tier"]], block)

    def test_category_aggregate_only_lists_its_category(self):
        text = bi.triggers(INVENTIONS)
        for c in bi.CATEGORIES:
            block = re.search(rf"^aov_inventions_{c}_discoverable = \{{\n(.*?)\n\}}", text, re.M | re.S).group(1)
            listed = set(re.findall(r"aov_invention_([a-z0-9_]+)_discoverable", block))
            self.assertEqual(listed, {i["key"] for i in INVENTIONS if i["category"] == c})

    def test_values(self):
        text = bi.values(INVENTIONS)
        self.assertEqual(top_level_blocks(text), ["aov_invention_active_count", "aov_invention_newest_order"])
        for k in KEYS:
            self.assertIn(f"aov_invention_{k}_active = yes", text)
            self.assertIn(f"min = var:aov_inv_{k}_order", text)

    def test_effects_per_invention(self):
        names = set(top_level_blocks(bi.effects(INVENTIONS)))
        for k in KEYS:
            for suffix in ("discover", "activate", "deactivate"):
                self.assertIn(f"aov_invention_{k}_{suffix}", names)
        for c in bi.CATEGORIES:
            self.assertIn(f"aov_inventions_discover_random_{c}", names)
            self.assertIn(f"aov_inventions_roll_offers_{c}", names)
            self.assertIn(f"aov_inventions_ai_start_technomancers_{c}", names)
        for n in ("aov_inventions_discover_random", "aov_inventions_discover_research_target",
                  "aov_inventions_activate_last_discovered", "aov_inventions_suspend_all", "aov_inventions_resume_all",
                  "aov_inventions_deactivate_newest", "aov_inventions_inherit", "aov_inventions_ai_activate_best"):
            self.assertIn(n, names)

    def effect_block(self, name):
        text = bi.effects(INVENTIONS)
        return re.search(rf"^{name} = \{{\n(.*?)\n^\}}", text, re.M | re.S).group(1)

    def test_suspend_and_resume_cover_every_invention(self):
        suspend = self.effect_block("aov_inventions_suspend_all")
        resume = self.effect_block("aov_inventions_resume_all")
        for k in KEYS:
            self.assertIn(f"remove_character_modifier = aov_invention_{k}", suspend)
            self.assertIn(f"add_character_modifier = {{ modifier = aov_invention_{k} }}", resume)

    def test_activate_respects_dormancy(self):
        block = self.effect_block("aov_invention_sparkdrive_rifles_activate")
        self.assertIn("NOT = { has_variable = aov_artificery_dormant }", block)

    def test_deactivate_newest_is_a_single_chain(self):
        block = self.effect_block("aov_inventions_deactivate_newest")
        self.assertEqual(block.count("\tif = {"), 1)
        self.assertEqual(block.count("\telse_if = {"), 59)

    def test_random_draw_per_category_only_lists_its_category(self):
        for c in bi.CATEGORIES:
            block = self.effect_block(f"aov_inventions_discover_random_{c}")
            listed = set(re.findall(r"aov_invention_([a-z0-9_]+)_discover = yes", block))
            self.assertEqual(listed, {i["key"] for i in INVENTIONS if i["category"] == c})

    def test_roll_offers_fills_three_slots(self):
        block = self.effect_block("aov_inventions_roll_offers_military")
        for n in (1, 2, 3):
            self.assertIn(f"name = aov_tech_offer_military_{n}", block)
        self.assertIn("set_variable = aov_tech_offers_rolled_military", block)

    def test_custom_loc_and_loc(self):
        cl = bi.custom_loc(INVENTIONS)
        self.assertEqual(top_level_blocks(cl), ["AovLastDiscoveredName", "AovResearchTargetName"])
        lc = bi.loc(INVENTIONS)
        self.assertTrue(lc.startswith("l_english:\n"))
        for i in INVENTIONS:
            self.assertIn(f' aov_invention_{i["key"]}: "{i["name"]}"', lc)
            self.assertIn(f" aov_invention_{i['key']}_desc:", lc)
            self.assertIn(f" aov_invention_{i['key']}_tt:", lc)

    def test_deterministic(self):
        for name in ("modifiers", "triggers", "values", "effects", "custom_loc", "loc"):
            self.assertEqual(getattr(bi, name)(INVENTIONS), getattr(bi, name)(INVENTIONS))


class GuiOutputTests(unittest.TestCase):
    def test_nine_sguis_per_invention(self):
        names = top_level_blocks(bi.sguis(INVENTIONS))
        self.assertEqual(len(names), 9 * 60)
        for k in KEYS:
            for s in ("visible", "unlocked", "undiscovered", "activate", "deactivate", "toggle", "offered", "research", "effects"):
                self.assertIn(f"aov_inv_{k}_{s}_sgui", names)

    def sgui_block(self, name):
        return re.search(rf"^{name} = \{{\n(.*?)\n\}}", bi.sguis(INVENTIONS), re.M | re.S).group(1)

    def test_deactivate_starts_cooldown(self):
        self.assertIn("aov_artificery_start_slot_cooldown = yes", self.sgui_block("aov_inv_sparkdrive_rifles_deactivate_sgui"))

    def test_toggle_activates_or_deactivates_with_cooldown(self):
        block = self.sgui_block("aov_inv_sparkdrive_rifles_toggle_sgui")
        self.assertIn("aov_invention_sparkdrive_rifles_discovered = yes", block)
        self.assertRegex(block, r"trigger_if = \{\s*limit = \{ NOT = \{ aov_invention_sparkdrive_rifles_active = yes \} \}"
                                r"\s*aov_invention_sparkdrive_rifles_available = yes\s*aov_artificery_has_free_slot = yes")
        self.assertRegex(block, r"aov_invention_sparkdrive_rifles_deactivate = yes\s*aov_artificery_start_slot_cooldown = yes")
        self.assertIn("else = { aov_invention_sparkdrive_rifles_activate = yes }", block)

    def test_gui_balanced_with_types(self):
        text = bi.gui(INVENTIONS)
        self.assertTrue(balanced(text))
        for t in ("aov_inventions_tier_1", "aov_inventions_tier_2", "aov_inventions_tier_3",
                  "aov_inventions_offers_economic", "aov_inventions_offers_military", "aov_inventions_offers_society"):
            self.assertIn(f"type {t} = vbox {{", text)
        for k in KEYS:
            self.assertIn(f"type aov_invention_{k}_tooltip = object_tooltip_pop_out {{", text)

    def tier_body(self, t):
        text = bi.gui(INVENTIONS)
        return text.split(f"type aov_inventions_tier_{t} = vbox {{")[1].split("\n\t}\n")[0]

    def test_tiers_have_society_economic_military_sections_of_their_boxes(self):
        for t in (1, 2, 3):
            body = self.tier_body(t)
            names = re.findall(r'name = "aov_inventions_t\d_([a-z]+)"', body)
            self.assertEqual(names, ["society", "economic", "military"])
            for c in bi.CATEGORIES:
                section = body.split(f'name = "aov_inventions_t{t}_{c}"')[1].split('name = "aov_inventions_t')[0]
                listed = re.findall(r'name = "aov_inv_box_([a-z0-9_]+)"', section)
                self.assertEqual(listed, [i["key"] for i in INVENTIONS if i["category"] == c and i["tier"] == t])

    def test_rows_hold_at_most_five_boxes(self):
        for t in (1, 2, 3):
            for row in self.tier_body(t).split("hbox = {")[1:]:
                self.assertLessEqual(row.count('name = "aov_inv_box_'), bi.PER_ROW)

    def box(self, k):
        text = bi.gui(INVENTIONS)
        return text.split(f'name = "aov_inv_box_{k}"')[1].split('name = "aov_inv_box_')[0]

    def test_box_click_toggles_and_hover_shows_invention_tooltip(self):
        for i in INVENTIONS:
            k = i["key"]
            b = self.box(k)
            self.assertIn(f"aov_inv_{k}_visible_sgui", b.split("\n")[1])
            self.assertIn(f"onclick = \"[GetScriptedGui('aov_inv_{k}_toggle_sgui').Execute( {bi.ROOT} )]\"", b)
            self.assertRegex(b, rf"tooltipwidget = \{{\s*aov_invention_{k}_tooltip = \{{\}}")
            self.assertIn(f"gfx/interface/icons/aov_inventions/{i['icon']}", b)
            self.assertIn(f"down = \"[GetScriptedGui('aov_inv_{k}_deactivate_sgui').IsShown( {bi.ROOT} )]\"", b)

    def test_tooltip_has_name_description_effects_and_status(self):
        text = bi.gui(INVENTIONS)
        for i in INVENTIONS:
            k = i["key"]
            tt = text.split(f"type aov_invention_{k}_tooltip = object_tooltip_pop_out {{")[1].split("\n\t}\n")[0]
            self.assertIn(f'text = "aov_invention_{k}"', tt)
            self.assertIn(f'text = "aov_invention_{k}_subtitle"', tt)
            self.assertIn(f'text = "aov_invention_{k}_desc"', tt)
            self.assertIn(f"[GetScriptedGui('aov_inv_{k}_effects_sgui').BuildTooltip( {bi.ROOT} )]", tt)
            for key in (f"AOV_INV_LOCKED_TIER_{i['tier']}_TT", "AOV_INV_UNDISCOVERED_TT", "AOV_INV_CLICK_ACTIVATE",
                        "AOV_INV_NO_FREE_SLOT", "AOV_INV_CLICK_DEACTIVATE"):
                self.assertIn(f'text = "{key}"', tt)

    def test_effects_sgui_adds_the_invention_modifier(self):
        for k in KEYS:
            block = self.sgui_block(f"aov_inv_{k}_effects_sgui")
            self.assertIn(f"add_character_modifier = {{ modifier = aov_invention_{k} }}", block)
            self.assertNotIn("is_shown", block)

    def test_offers_only_list_their_category_and_use_the_tooltip(self):
        text = bi.gui(INVENTIONS)
        for c in bi.CATEGORIES:
            body = text.split(f"type aov_inventions_offers_{c} = vbox {{")[1].split("type aov_inventions_offers_")[0]
            listed = set(re.findall(r'name = "aov_inv_offer_([a-z0-9_]+)"', body))
            self.assertEqual(listed, {i["key"] for i in INVENTIONS if i["category"] == c})
            for k in listed:
                self.assertIn(f"aov_invention_{k}_tooltip = {{}}", body)
                self.assertIn(f"GetScriptedGui('aov_inv_{k}_research_sgui').Execute", body)

    def test_subtitle_loc(self):
        lc = bi.loc(INVENTIONS)
        self.assertIn(' aov_invention_sparkdrive_rifles_subtitle: "$AOV_CATEGORY_MILITARY$, $AOV_TIER_1$"', lc)

    def test_render_all_paths(self):
        files = bi.render_all(INVENTIONS)
        self.assertEqual(set(files), {
            "common/modifiers/aov_invention_modifiers.txt",
            "common/scripted_triggers/aov_invention_triggers.txt",
            "common/script_values/aov_invention_values.txt",
            "common/scripted_effects/aov_invention_effects.txt",
            "common/scripted_guis/aov_invention_sgui.txt",
            "common/customizable_localization/aov_invention_custom_loc.txt",
            "gui/aov_inventions_generated.gui",
            "localization/english/aov_inventions_l_english.yml",
        })

    def test_write_all_bom_lf(self):
        with tempfile.TemporaryDirectory() as tmp:
            bi.write_all({"a/b.txt": "x = {\n}\n"}, Path(tmp))
            raw = (Path(tmp) / "a" / "b.txt").read_bytes()
            self.assertEqual(raw, b"\xef\xbb\xbfx = {\n}\n")

    def test_copy_icons_copies_each_distinct_icon(self):
        with tempfile.TemporaryDirectory() as tmp:
            eu4, root = Path(tmp, "eu4"), Path(tmp, "mod")
            (eu4 / bi.EU4_ICONS).mkdir(parents=True)
            for name in {i["icon"] for i in INVENTIONS}:
                (eu4 / bi.EU4_ICONS / name).write_bytes(b"DDS ")
            bi.copy_icons(INVENTIONS, eu4, root)
            self.assertEqual(len(list((root / bi.ICON_DIR).glob("*.dds"))), len({i["icon"] for i in INVENTIONS}))

    def test_copy_icons_missing_source(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(bi.GeneratorError):
                bi.copy_icons(INVENTIONS, Path(tmp, "nope"), Path(tmp, "mod"))


if __name__ == "__main__":
    unittest.main()
