"""Tests for tools/build_lifestyle_override.py.

    python -I -m unittest discover -s tools/tests -v
"""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import build_lifestyle_override as blo  # noqa: E402

FIXTURE = (
    "window = {\n"
    "\t\tbackground = {\n"
    "\t\t\tvisible = \"[EqualTo_string( Lifestyle.GetKey, 'learning_lifestyle' )]\"\n"
    "\t\t\ttexture = \"gfx/interface/progressbars/progress_gray.dds\"\n"
    "\t\t}\n"
    "\n"
    "\t\tbackground = {\n"
    "\t\t\tvisible = \"[EqualTo_string( Lifestyle.GetKey, 'wanderer_lifestyle' )]\"\n"
    "\t\t\ttexture = \"gfx/interface/progressbars/progress_brown.dds\"\n"
    "\t\t\talpha = 0.2\n"
    "\t\t}\n"
    "\n"
    "\t\tprogressbar_lifestyle_xp = {\n"
    "\t\t\tvisible = \"[EqualTo_string( Lifestyle.GetKey, 'wanderer_lifestyle' )]\"\n"
    "\t\t\tprogresstexture = \"gfx/interface/progressbars/progress_brown.dds\"\n"
    "\t\t\tnoprogresstexture = \"gfx/interface/progressbars/progress_brown_bg.dds\"\n"
    "\t\t}\n"
    "\n"
    "\t\ticon_lifestyle_unspent_points = {\n"
    "\t\t\tvisible = \"[EqualTo_string( Lifestyle.GetKey, 'wanderer_lifestyle' )]\"\n"
    "\t\t\ttexture = \"gfx/interface/icons/lifestyles_perks/node_wanderer.dds\"\n"
    "\t\t}\n"
    "\n"
    "}\n"
)


def nth(text, needle, n):
    i = -1
    for _ in range(n + 1):
        i = text.index(needle, i + 1)
    return i


class InsertMagicTests(unittest.TestCase):
    def test_inserts_a_magic_copy_after_each_anchor(self):
        out = blo.insert_magic(FIXTURE)
        self.assertEqual(out.count("'magic_lifestyle'"), 3)
        for i in range(3):  # each copy follows its wanderer block
            self.assertLess(nth(out, "'wanderer_lifestyle'", i), nth(out, "'magic_lifestyle'", i))
        for chunk in out.split(blo.MARKER)[1:]:  # the marked copies carry no wanderer art
            copy = chunk.split("\n\n", 1)[0]
            self.assertNotIn("progress_brown", copy)
            self.assertNotIn("node_wanderer", copy)

    def test_textures_mapped(self):
        out = blo.insert_magic(FIXTURE)
        for new in blo.TEXTURES.values():
            self.assertIn(new, out)

    def test_errors_when_anchor_count_changes(self):
        with self.assertRaises(blo.GeneratorError):
            blo.insert_magic(FIXTURE.replace("'wanderer_lifestyle'", "'other'", 1))

    def test_errors_on_unmapped_texture(self):
        with self.assertRaises(blo.GeneratorError):
            blo.insert_magic(FIXTURE.replace("progress_brown_bg.dds", "progress_new.dds"))

    def test_refuses_generated_input(self):
        with self.assertRaises(blo.GeneratorError):
            blo.insert_magic(blo.insert_magic(FIXTURE))

    def test_only_adds_marked_blocks(self):
        out = blo.insert_magic(FIXTURE)
        self.assertEqual(sum(blo.brace_delta(l) for l in out.split("\n")), 0)
        # dropping each marked copy (blank line, comment, block) restores the source
        lines, kept, i = out.split("\n"), [], 0
        while i < len(lines):
            if lines[i].strip().startswith(blo.MARKER):
                kept.pop()  # the blank line before the comment
                depth, i = 0, i + 1
                while True:
                    depth += blo.brace_delta(lines[i])
                    i += 1
                    if depth == 0:
                        break
            else:
                kept.append(lines[i])
                i += 1
        self.assertEqual("\n".join(kept), FIXTURE)


class BuildTests(unittest.TestCase):
    def test_build_keeps_bom_and_adds_header(self):
        out = blo.build(b"\xef\xbb\xbf" + FIXTURE.encode())
        self.assertTrue(out.startswith(b"\xef\xbb\xbf# Anbennar Overhaul: generated by tools/build_lifestyle_override.py"))

    def test_build_preserves_crlf(self):
        out = blo.build(FIXTURE.replace("\n", "\r\n").encode())
        self.assertFalse(out.startswith(b"\xef\xbb\xbf"))
        self.assertNotIn("\n", out.decode().replace("\r\n", ""))


class FindSourceTests(unittest.TestCase):
    def test_prefers_anbennar_then_game(self):
        with tempfile.TemporaryDirectory() as tmp:
            anb, game = Path(tmp, "anb"), Path(tmp, "game")
            (game / "gui").mkdir(parents=True)
            (game / "gui" / "window_character_lifestyle.gui").write_text("x")
            self.assertEqual(blo.find_source(anb, game), game / "gui" / "window_character_lifestyle.gui")
            (anb / "gui").mkdir(parents=True)
            (anb / "gui" / "window_character_lifestyle.gui").write_text("x")
            self.assertEqual(blo.find_source(anb, game), anb / "gui" / "window_character_lifestyle.gui")

    def test_neither_exists(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(blo.GeneratorError):
                blo.find_source(Path(tmp, "a"), Path(tmp, "b"))


if __name__ == "__main__":
    unittest.main()
