"""Tests for tools/data/inventions.py and tools/build_inventions.py.

    python -I -m unittest discover -s tools/tests -v
"""

import collections
import importlib.util
import re
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(TOOLS))


def load_data():
    spec = importlib.util.spec_from_file_location("aov_inventions_data", TOOLS / "data" / "inventions.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.INVENTIONS


INVENTIONS = load_data()
KEYS = [i["key"] for i in INVENTIONS]


class DataTests(unittest.TestCase):
    def test_sixty_unique_inventions(self):
        self.assertEqual(len(INVENTIONS), 60)
        self.assertEqual(len(set(KEYS)), 60)

    def test_category_counts_match_research_doc(self):
        counts = collections.Counter(i["category"] for i in INVENTIONS)
        self.assertEqual(counts, {"economic": 16, "military": 26, "society": 18})

    def test_every_category_tier_pair_is_populated(self):
        pairs = {(i["category"], i["tier"]) for i in INVENTIONS}
        self.assertEqual(len(pairs), 9)

    def test_fields(self):
        for i in INVENTIONS:
            with self.subTest(i["key"]):
                self.assertRegex(i["key"], r"^[a-z0-9_]+$")
                self.assertIn(i["tier"], (1, 2, 3))
                self.assertRegex(i["icon"], r"^Artf_\w+\.dds$")
                self.assertTrue(i["modifier"].strip())
                self.assertTrue(i["name"] and i["desc"])
                self.assertNotIn('"', i["name"] + i["desc"])

    def test_maa_unlocks(self):
        maa = {i["key"]: i["maa"] for i in INVENTIONS if i["maa"]}
        self.assertEqual(maa, {
            "prototype_tanks": "aov_prototype_tanks",
            "war_golems": "aov_war_golems",
            "damestear_reactor_megacannon": "aov_damestear_megacannon",
        })

    def test_locks(self):
        self.assertEqual(sum(1 for i in INVENTIONS if i["faith"]), 8)
        self.assertEqual({i["key"] for i in INVENTIONS if i["gnome_only"]},
                         {"conversation_calibrator", "coddorran_powered_exosuit", "gu_boats", "prefabricated_city_constructors"})

    def test_sorted_by_category_tier_key(self):
        order = {"economic": 0, "military": 1, "society": 2}
        self.assertEqual(INVENTIONS, sorted(INVENTIONS, key=lambda i: (order[i["category"]], i["tier"], i["key"])))


import build_inventions as bi  # noqa: E402
import build_hud_override  # noqa: E402  (brace_delta)


def balanced(text):
    depth = 0
    for line in text.split("\n"):
        depth += build_hud_override.brace_delta(line)
        if depth < 0:
            return False
    return depth == 0


def top_level_blocks(text):
    return re.findall(r"^([A-Za-z0-9_]+) = \{", text, re.M)


class ValidateTests(unittest.TestCase):
    def test_real_data_is_valid(self):
        bi.validate(INVENTIONS)

    def test_rejects_duplicate_key(self):
        with self.assertRaises(bi.GeneratorError):
            bi.validate(INVENTIONS + [dict(INVENTIONS[0])])

    def test_rejects_unknown_faith(self):
        bad = dict(INVENTIONS[0], faith="faith = faith:made_up")
        with self.assertRaises(bi.GeneratorError):
            bi.validate([bad])

    def test_rejects_bad_category(self):
        with self.assertRaises(bi.GeneratorError):
            bi.validate([dict(INVENTIONS[0], category="magic")])


class ScriptOutputTests(unittest.TestCase):
    def test_all_script_outputs_balanced_and_headed(self):
        for name in ("modifiers", "triggers", "values", "effects", "custom_loc"):
            with self.subTest(name):
                text = getattr(bi, name)(INVENTIONS)
                self.assertTrue(text.startswith("# Anbennar Overhaul: generated by tools/build_inventions.py"))
                self.assertTrue(balanced(text))

    def test_modifier_per_invention_with_category_icon(self):
        text = bi.modifiers(INVENTIONS)
        self.assertEqual(top_level_blocks(text), [f"aov_invention_{k}" for k in KEYS])
        self.assertIn("aov_invention_sparkdrive_rifles = {\n\ticon = martial_positive\n\tgunpowder_damage_mult = 0.15\n}", text)

    def test_triggers_per_invention(self):
        names = set(top_level_blocks(bi.triggers(INVENTIONS)))
        for k in KEYS:
            for suffix in ("visible", "unlocked", "available", "discovered", "active", "discoverable", "activatable", "offered"):
                self.assertIn(f"aov_invention_{k}_{suffix}", names)
        for c in bi.CATEGORIES:
            self.assertIn(f"aov_inventions_{c}_discoverable", names)
            self.assertIn(f"aov_inventions_{c}_unoffered_discoverable", names)
            for t in (1, 2, 3):
                self.assertIn(f"aov_inventions_t{t}_{c}_activatable", names)
        for n in ("aov_inventions_any_discovered", "aov_inventions_any_discoverable", "aov_inventions_any_activatable",
                  "aov_inventions_t1_activatable", "aov_inventions_t2_activatable", "aov_inventions_t3_activatable"):
            self.assertIn(n, names)

    def test_unlocked_uses_tier_era(self):
        text = bi.triggers(INVENTIONS)
        for i in INVENTIONS:
            block = re.search(rf"^aov_invention_{i['key']}_unlocked = \{{\n(.*?)\n\}}", text, re.M | re.S).group(1)
            self.assertIn(bi.ERAS[i["tier"]], block)

    def test_category_aggregate_only_lists_its_category(self):
        text = bi.triggers(INVENTIONS)
        for c in bi.CATEGORIES:
            block = re.search(rf"^aov_inventions_{c}_discoverable = \{{\n(.*?)\n\}}", text, re.M | re.S).group(1)
            listed = set(re.findall(r"aov_invention_([a-z0-9_]+)_discoverable", block))
            self.assertEqual(listed, {i["key"] for i in INVENTIONS if i["category"] == c})

    def test_values(self):
        text = bi.values(INVENTIONS)
        self.assertEqual(top_level_blocks(text), ["aov_invention_active_count", "aov_invention_newest_order"])
        for k in KEYS:
            self.assertIn(f"aov_invention_{k}_active = yes", text)
            self.assertIn(f"min = var:aov_inv_{k}_order", text)

    def test_effects_per_invention(self):
        names = set(top_level_blocks(bi.effects(INVENTIONS)))
        for k in KEYS:
            for suffix in ("discover", "activate", "deactivate"):
                self.assertIn(f"aov_invention_{k}_{suffix}", names)
        for c in bi.CATEGORIES:
            self.assertIn(f"aov_inventions_discover_random_{c}", names)
            self.assertIn(f"aov_inventions_roll_offers_{c}", names)
            self.assertIn(f"aov_inventions_ai_start_technomancers_{c}", names)
        for n in ("aov_inventions_discover_random", "aov_inventions_discover_research_target",
                  "aov_inventions_activate_last_discovered", "aov_inventions_suspend_all", "aov_inventions_resume_all",
                  "aov_inventions_deactivate_newest", "aov_inventions_inherit", "aov_inventions_ai_activate_best"):
            self.assertIn(n, names)

    def effect_block(self, name):
        text = bi.effects(INVENTIONS)
        return re.search(rf"^{name} = \{{\n(.*?)\n^\}}", text, re.M | re.S).group(1)

    def test_suspend_and_resume_cover_every_invention(self):
        suspend = self.effect_block("aov_inventions_suspend_all")
        resume = self.effect_block("aov_inventions_resume_all")
        for k in KEYS:
            self.assertIn(f"remove_character_modifier = aov_invention_{k}", suspend)
            self.assertIn(f"add_character_modifier = {{ modifier = aov_invention_{k} }}", resume)

    def test_activate_respects_dormancy(self):
        block = self.effect_block("aov_invention_sparkdrive_rifles_activate")
        self.assertIn("NOT = { has_variable = aov_artificery_dormant }", block)

    def test_deactivate_newest_is_a_single_chain(self):
        block = self.effect_block("aov_inventions_deactivate_newest")
        self.assertEqual(block.count("\tif = {"), 1)
        self.assertEqual(block.count("\telse_if = {"), 59)

    def test_random_draw_per_category_only_lists_its_category(self):
        for c in bi.CATEGORIES:
            block = self.effect_block(f"aov_inventions_discover_random_{c}")
            listed = set(re.findall(r"aov_invention_([a-z0-9_]+)_discover = yes", block))
            self.assertEqual(listed, {i["key"] for i in INVENTIONS if i["category"] == c})

    def test_roll_offers_fills_three_slots(self):
        block = self.effect_block("aov_inventions_roll_offers_military")
        for n in (1, 2, 3):
            self.assertIn(f"name = aov_tech_offer_military_{n}", block)
        self.assertIn("set_variable = aov_tech_offers_rolled_military", block)

    def test_custom_loc_and_loc(self):
        cl = bi.custom_loc(INVENTIONS)
        self.assertEqual(top_level_blocks(cl), ["AovLastDiscoveredName", "AovResearchTargetName"])
        lc = bi.loc(INVENTIONS)
        self.assertTrue(lc.startswith("l_english:\n"))
        for i in INVENTIONS:
            self.assertIn(f' aov_invention_{i["key"]}: "{i["name"]}"', lc)
            self.assertIn(f" aov_invention_{i['key']}_desc:", lc)
            self.assertIn(f" aov_invention_{i['key']}_tt:", lc)

    def test_deterministic(self):
        for name in ("modifiers", "triggers", "values", "effects", "custom_loc", "loc"):
            self.assertEqual(getattr(bi, name)(INVENTIONS), getattr(bi, name)(INVENTIONS))


if __name__ == "__main__":
    unittest.main()
