import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # python -I does not add the tools folder
import build_county_view_override as cvo  # noqa: E402
from build_hud_override import GeneratorError  # noqa: E402

FIXTURE = """window = {
\twidget = {
\t\tbackground = {
\t\t\tvisible = "[HoldingView.HasHolding]"
\t\t\ttexture = "[HoldingView.GetHolding.GetIllustration]"
\t\t\talpha = 0.8

\t\t\tmodify_texture = {
\t\t\t\ttexture = "gfx/mask.dds"
\t\t\t\tblend_mode = alphamultiply
\t\t\t}
\t\t}

\t\tbackground = {
\t\t\ttexture = "[HoldingView.GetProvince.GetTerrain.GetIllustration]"
\t\t}
\t}
}
"""


class CountyViewTests(unittest.TestCase):
    def test_inserts_monument_illustration_after_holding_illustration(self):
        out = cvo.insert(FIXTURE)
        self.assertIn("HoldingView.GetProvince.Custom('AovMonumentIllustration')", out)
        self.assertLess(out.index("HoldingView.GetHolding.GetIllustration"), out.index("AovMonumentIllustration"))
        self.assertLess(out.index("AovMonumentIllustration"), out.index("GetTerrain"))

    def test_errors_without_anchor(self):
        with self.assertRaises(GeneratorError):
            cvo.insert(FIXTURE.replace("HoldingView.GetHolding.GetIllustration", "x"))

    def test_errors_if_already_generated(self):
        with self.assertRaises(GeneratorError):
            cvo.insert(cvo.insert(FIXTURE))

    def test_build_adds_header_and_keeps_bom(self):
        out = cvo.build(b"\xef\xbb\xbf" + FIXTURE.encode()).decode("utf-8-sig")
        self.assertTrue(out.startswith("# Anbennar Overhaul: generated by tools/build_county_view_override.py"))
