"""Tests for tools/data/spells.py and tools/build_spells.py.

    python -I -m unittest discover -s tools/tests -v
"""

import collections
import importlib.util
import re
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS = Path(__file__).resolve().parent.parent
MOD = TOOLS.parent
sys.path.insert(0, str(TOOLS))


def load_data():
    spec = importlib.util.spec_from_file_location("aov_spells_data", TOOLS / "data" / "spells.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.SPELLS


SPELLS = load_data()

import build_spells as bs  # noqa: E402
import build_hud_override  # noqa: E402  (brace_delta)


def balanced(text):
    depth = 0
    for line in text.split("\n"):
        depth += build_hud_override.brace_delta(line)
        if depth < 0:
            return False
    return depth == 0


def top_level_blocks(text):
    return re.findall(r"^([A-Za-z0-9_.]+) = \{", text, re.M)


def block(text, name):
    m = re.search(rf"^{re.escape(name)} = \{{\n(.*?)\n^\}}", text, re.M | re.S)
    assert m, name
    return m.group(1)


class DataTests(unittest.TestCase):
    def test_forty_nine_spells_in_eight_schools(self):
        self.assertEqual(len(SPELLS), 49)
        counts = collections.Counter(s["school"] for s in SPELLS)
        self.assertEqual(set(counts), set(bs.SCHOOLS))
        self.assertEqual(counts["transmutation"], 7)
        self.assertTrue(all(counts[c] == 6 for c in bs.SCHOOLS if c != "transmutation"))

    def test_slots_match_levels(self):
        level_of_slot = {1: 0, 2: 1, 3: 1, 4: 2, 5: 2, 6: 3}
        for s in SPELLS:
            if s["slot"]:
                self.assertEqual(level_of_slot[s["slot"]], s["level"], s["key"])
        for c in bs.SCHOOLS:
            slots = [s["slot"] for s in SPELLS if s["school"] == c and s["slot"]]
            self.assertEqual(sorted(slots), [1, 2, 3, 4, 5, 6], c)

    def test_existing_anbennar_spells(self):
        by = {s["key"]: s for s in SPELLS}
        self.assertEqual(by["thoughtweave"]["interaction"], "start_compel_interaction")
        self.assertEqual(by["dominate_to_surrender"]["interaction"], "start_dominate_interaction")
        self.assertEqual(by["enhance_ability"]["interaction"], "anb_enhance_ability_interaction")
        self.assertEqual((by["enhance_ability"]["school"], by["enhance_ability"]["level"]), ("transmutation", 1))

    def test_types(self):
        targeted = {s["key"] for s in SPELLS if s["type"] == "targeted"}
        self.assertEqual(targeted, {"ward", "heartstring", "thoughtweave", "dominate_to_surrender", "scry",
                                    "steal_vitality", "contagion", "enhance_ability"})
        for s in SPELLS:
            if s["type"] in ("self", "realm", "war"):
                self.assertTrue(s["modifier"].strip() or s["effect"].strip(), s["key"])


class ValidateTests(unittest.TestCase):
    def test_real_data_valid(self):
        bs.validate(SPELLS)

    def test_rejects_unknown_school(self):
        with self.assertRaises(bs.GeneratorError):
            bs.validate([dict(SPELLS[0], school="evokation")])

    def test_rejects_duplicate(self):
        with self.assertRaises(bs.GeneratorError):
            bs.validate(SPELLS + [dict(SPELLS[0])])


class ArtTests(unittest.TestCase):
    def test_downscale_averages(self):
        px = bytes([255, 0, 0, 255] * 4)  # 2x2 BGRA
        self.assertEqual(bs.downscale(px, 2, 2, 1), bytes([255, 0, 0, 255]))

    def test_copy_art_missing_source(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(bs.GeneratorError):
                bs.copy_art(Path(tmp, "nope"), Path(tmp, "mod"))


class GeneratedTests(unittest.TestCase):
    def test_outputs_balanced_and_headed(self):
        for name in ("modifiers", "triggers", "effects", "sguis"):
            with self.subTest(name):
                text = getattr(bs, name)(SPELLS)
                self.assertTrue(text.startswith("# Anbennar Overhaul: generated by tools/build_spells.py"))
                self.assertTrue(balanced(text))

    def test_cast_effect_pays_progresses_and_cools_down(self):
        b = block(bs.effects(SPELLS), "aov_spell_guidance_cast")
        self.assertIn("aov_mana_change = { AMOUNT = -25 }", b)
        self.assertIn("aov_school_add_progress = { SCHOOL = divination AMOUNT = 25 }", b)
        self.assertIn("set_variable = { name = aov_spell_guidance_cd years = 1 }", b)
        self.assertIn("add_character_modifier = { modifier = aov_spell_guidance years = 1 }", b)
        b3 = block(bs.effects(SPELLS), "aov_spell_chronophage_cast")
        self.assertIn("aov_mana_change = { AMOUNT = -200 }", b3)
        self.assertIn("years = 5", b3)

    def test_necromancy_rolls_dark_magic(self):
        t = bs.effects(SPELLS)
        self.assertIn("aov_dark_magic_roll = yes", block(t, "aov_spell_false_life_cast"))
        self.assertNotIn("aov_dark_magic_roll", block(t, "aov_spell_guidance_cast"))

    def test_castable_requires_mage(self):
        b = block(bs.triggers(SPELLS), "aov_spell_fireball_castable")
        for s in ("aov_is_mage = yes", "aov_spell_fireball_known = yes", "aov_spell_fireball_ready = yes", "aov_mana >= 25"):
            self.assertIn(s, b)
        self.assertIn("aov_school_level_at_least = { SCHOOL = evocation LEVEL = 0 }",
                      block(bs.triggers(SPELLS), "aov_spell_fireball_known"))

    def test_war_spells_need_war(self):
        self.assertIn("is_at_war = yes", block(bs.triggers(SPELLS), "aov_spell_meteor_swarm_castable"))
        self.assertNotIn("is_at_war", block(bs.triggers(SPELLS), "aov_spell_guidance_castable"))

    def test_sgui_only_for_window_spells(self):
        names = set(top_level_blocks(bs.sguis(SPELLS)))
        self.assertIn("aov_spell_guidance_sgui", names)
        self.assertNotIn("aov_spell_heartstring_sgui", names)
        for c in bs.SCHOOLS:
            self.assertIn(f"aov_study_{c}_sgui", names)

    def test_modifier_per_lasting_spell(self):
        names = set(top_level_blocks(bs.modifiers(SPELLS)))
        self.assertIn("aov_spell_combat_ward", names)
        self.assertIn("aov_spell_steal_vitality", names)
        self.assertNotIn("aov_spell_transmute_to_gold", names)  # one-off

    def test_loc_keys(self):
        lc = bs.loc(SPELLS)
        self.assertTrue(lc.startswith("l_english:\n"))
        for s in SPELLS:
            for suffix in ("", "_desc", "_flavour"):
                self.assertIn(f" aov_spell_{s['key']}{suffix}:", lc)
        for c in bs.SCHOOLS:
            for lvl in range(4):
                self.assertIn(f" AOV_SPELL_REQ_{c.upper()}_{lvl}:", lc)

    def test_generated_interactions(self):
        text = bs.interactions(SPELLS)
        self.assertTrue(balanced(text))
        names = set(top_level_blocks(text))
        self.assertEqual(names, {f"aov_spell_{k}_interaction" for k in ("ward", "heartstring", "scry", "steal_vitality", "contagion")})
        for name in names:
            b = block(text, name)
            k = name[len("aov_spell_"):-len("_interaction")]
            self.assertIn("category = interaction_category_spells", b)
            self.assertIn(f"scope:actor = {{ aov_spell_{k}_castable = yes }}", b)
            self.assertIn("scope:recipient = { aov_spell_target_allowed = yes }", b)
            self.assertIn(f"scope:actor = {{ aov_spell_{k}_cast = yes }}", b)

    def test_interaction_loc(self):
        lc = bs.loc(SPELLS)
        for k in ("ward", "heartstring", "scry", "steal_vitality", "contagion"):
            self.assertIn(f" aov_spell_{k}_interaction:", lc)
            self.assertIn(f" aov_spell_{k}_interaction_desc:", lc)

    def test_render_all_paths(self):
        self.assertEqual(set(bs.render_all(SPELLS)), {
            "common/character_interactions/aov_spell_interactions.txt",
            "common/modifiers/aov_spell_modifiers.txt",
            "common/scripted_triggers/aov_spell_triggers.txt",
            "common/scripted_effects/aov_spell_effects.txt",
            "common/scripted_guis/aov_spell_sgui.txt",
            "localization/english/aov_spells_l_english.yml",
        })


if __name__ == "__main__":
    unittest.main()
