"""Artificer inventions: the single source of truth for tools/build_inventions.py.

Content mapped from EU4 Anbennar (see docs/research/2026-10-08-eu4-artificer-inventions.md).
icon is the file name in EU4 Anbennar gfx/interface/privileges/; modifier is a CK3 character modifier body.
"""

INVENTIONS = [
    dict(
        key='arcane_battery_capital_complex',
        category='economic',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc1.dds',
        modifier='character_capital_county_monthly_development_growth_add = 0.2',
        maa=None,
        name='Arcane Battery Capital-Complex',
        desc='A gigantic structure which produces and distributes stabilized damestear batteries for use in our entire capital. Every day, it takes in and processes more damestear than a medieval Sorcerer-King would see in their entire lifetime.',
    ),
    dict(
        key='automated_translator',
        category='economic',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc1.dds',
        modifier='diplomacy = 1\ndifferent_culture_opinion = 10',
        maa=None,
        name='Automated Translator',
        desc='The creation of an accessible automated translator greatly decreases the effort required to prepare diplomats to represent us, allowing us to host a larger (and more capable) diplomatic corps.',
    ),
    dict(
        key='market_mender',
        category='economic',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc1.dds',
        modifier='domain_tax_mult = 0.05\nstewardship = 1',
        maa=None,
        name='Market Mender Victor.I.A.3',
        desc='A marvel of calculations which can intake any amount of data and output averages, predictions on future markets, optimal tax rates, and more. The pinnacle of spreadsheet technology.',
    ),
    dict(
        key='plane_of_water_teleporter',
        category='economic',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeEc1.dds',
        modifier='naval_movement_speed_mult = 0.2\nembarkation_cost_mult = -0.25',
        maa=None,
        name='Plane-of-Water Teleporter',
        desc='Teleporters which allow ships to temporarily enter the Plane of Water, allowing for easier travel in a plane whose distances are much shorter than our own.',
    ),
    dict(
        key='self_cleaning_parchment',
        category='economic',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_MaEc1.dds',
        modifier='monthly_county_control_growth_add = 0.1',
        maa=None,
        name='Self Cleaning Parchment',
        desc='The ability to quickly and easily correct clerical errors in official government documents makes the day-to-day functions of state vastly less complex.',
    ),
    dict(
        key='spell_in_a_box',
        category='economic',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo1.dds',
        modifier='monthly_prestige_gain_mult = 0.05',
        maa=None,
        name='Spell-In-A-Box',
        desc='Pre-cast spells preserved for long periods of time, contained within scrolls, themselves contained within specialized containers.',
    ),
    dict(
        key='brass_prosthesis',
        category='economic',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc2.dds',
        modifier='levy_reinforcement_rate = 0.15',
        maa=None,
        name='Brass Prosthesis',
        desc='Built of brass, these mechanical arms and legs graft onto the spot where a limb has been lost and, although not quite as responsive as the original limb, are still able to move relatively well, and are definitely much more durable.',
    ),
    dict(
        key='chi_cultivation',
        category='economic',
        tier=2,
        faith='faith = faith:devouring_path',
        gnome_only=False,
        icon='Artf_TeMi2.dds',
        modifier='gunpowder_damage_mult = 0.1',
        maa=None,
        name='Chi Extraction Charms',
        desc="A small box with an intricate array of steel and jade allows our artificer regiments to drain chi from prisoners and 'volunteers', and then unleash it in battle.",
    ),
    dict(
        key='gene_food_cultivation',
        category='economic',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_MaEc2.dds',
        modifier='development_growth_factor = 0.1\nsupply_limit_mult = 0.1',
        maa=None,
        name='Gene-Food Cultivation',
        desc='A method which allows artificers to alter the fundamental properties of species of plants; resistance to drought or flood, and capable of producing bumper harvests every time.',
    ),
    dict(
        key='growth_beans',
        category='economic',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_TeEc2.dds',
        modifier='domain_tax_mult = 0.05\ndevelopment_growth_factor = 0.1',
        maa=None,
        name='Growth Beans',
        desc='Growth beans act as very high quality fertilizer, greatly increasing the amount of harvest we can tax.',
    ),
    dict(
        key='subterrenes',
        category='economic',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc2.dds',
        modifier='build_gold_cost = -0.1\nbuild_speed = -0.1',
        maa=None,
        name='Subterrenes',
        desc='Giant drill-vehicles which tunnel beneath the earth, placing supports behind them as they progress through the rock. Allows for far greater underground construction at scale, even for surface-dwellers.',
    ),
    dict(
        key='vendorless_stall',
        category='economic',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_TeEc2.dds',
        modifier='domain_tax_mult = 0.1',
        maa=None,
        name='Vendorless Stall',
        desc='By facilitating the spread of vendorless stalls, we can improve our revenues by allowing people to do more business in the same space of time.',
    ),
    dict(
        key='elemental_locomotives',
        category='economic',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_MaEc3.dds',
        modifier='movement_speed = 0.1\ntravel_speed = 20\ndomain_limit = 1',
        maa=None,
        name='Sparkdrive Locomotives',
        desc='This shockingly fast vehicle can increase our governmental control and improve military capabilities through its ability to move people, goods, and information at speeds previously only possible in dreams and delusions.',
    ),
    dict(
        key='pathway_transmutation',
        category='economic',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc3.dds',
        modifier='monthly_income_mult = 0.1',
        maa=None,
        name='Pathway Transmutation',
        desc="A world-changing innovation in the field of transmutation. By analyzing the magochemical 'pathways' between objects-- in other words, by seeing which objects' magical signatures are closest to each other-- we can transmute vast quantities of one substance into another. The potential applications are endless.",
    ),
    dict(
        key='prefabricated_city_constructors',
        category='economic',
        tier=3,
        faith=None,
        gnome_only=True,
        icon='Artf_MaEc2.dds',
        modifier='development_growth_factor = 0.15\nholding_build_gold_cost = -0.15',
        maa=None,
        name='Prefabricated City Constructors',
        desc='Mass-produced construction materials, enchanted Fabricate spells, and industrial quantities of magical glue, all packed into Boxes of Holding. Upon activation, the Fabrication spells do the work of constructing these prefabricated cities without the need of any additional laborers.',
    ),
    dict(
        key='t_wave_transceivers',
        category='economic',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_BrEc3.dds',
        modifier='diplomacy = 2\nadvantage = 2',
        maa=None,
        name='T-Wave Transceivers',
        desc='T-Wave Transceivers allow any common soldier or commander with the device to talk to anyone linked to the same telepathic wave, allowing military manoeuvres and even entire campaigns to be coordinated like never before!',
    ),
    dict(
        key='ancestral_golems',
        category='military',
        tier=1,
        faith='faith = faith:ancestor_worship',
        gnome_only=False,
        icon='Artf_BrMi1.dds',
        modifier='fort_level = 1\ndefender_holding_advantage = 3',
        maa=None,
        name='Ancestral Guardian Golems',
        desc='Living statues whose presence and shape propels dwarves to fight far more fiercely and far more willingly, and are themselves capable of basic combat to defend a given area.',
    ),
    dict(
        key='artificer_exo_arms',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrMi1.dds',
        modifier='gunpowder_damage_mult = 0.1',
        maa=None,
        name='Artificer Exo Arms',
        desc="Mechanical limbs, powered by clockwork, and controlled through a divination magic-based interface with the user's mind.",
    ),
    dict(
        key='box_of_holding',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeEc1.dds',
        modifier='supply_duration = 0.25',
        maa=None,
        name='Box of Holding',
        desc='Sturdy boxes infused with the magic of traditional bags of holding will make shipping goods across vast distances a breeze.',
    ),
    dict(
        key='commercial_sky_galleons',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_MaMi1.dds',
        modifier='travel_speed = 10\nmonthly_income_mult = 0.03',
        maa=None,
        name='Commercial Sky Galleons',
        desc='Mighty zeppelins powered by the might of steam and gas, opening the skies to all, and revolutionising commerce in the process.',
    ),
    dict(
        key='magic_missile_deployer',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeMi1.dds',
        modifier='gunpowder_toughness_mult = 0.1',
        maa=None,
        name='Magic Missile Deployer',
        desc='These light artillery guns, though complicated, can fire hundreds of unguided magic missiles in mere seconds, preventing our foes from engaging in close-combat.',
    ),
    dict(
        key='portable_turrets',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_MaMi1.dds',
        modifier='siege_phase_time = -0.1\ngunpowder_toughness_mult = 0.05',
        maa=None,
        name='Portable Turrets',
        desc='These turrets can hold their ground and continue fighting even when a man would have fled, and are capable of enhancing enforcing our line and ability to deny a siege defender any outside goods.',
    ),
    dict(
        key='sparkdrive_rifles',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrMi1.dds',
        modifier='gunpowder_damage_mult = 0.15',
        maa=None,
        name='Sparkdrive Rifles',
        desc='The Sparkdrive Rifles are capable of shooting lightning bolts at their enemies; their scarcity means they cannot be used by rank-and-file troops (much to their disappointment) but instead wielded by elite artificer-skirmishers.',
    ),
    dict(
        key='sunbeam_armaments',
        category='military',
        tier=1,
        faith='faith = { religion = religion:bulwari_sun_cults_religion }',
        gnome_only=False,
        icon='Artf_BrMi1.dds',
        modifier='siege_phase_time = -0.2',
        maa=None,
        name='Sunblessed Armaments',
        desc='Storing and channeling the might of the very sun itself against an enemy target, these sunblessed armaments provide a vital weapon for any besieging army.',
    ),
    dict(
        key='vorpal_bullets',
        category='military',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeMi1.dds',
        modifier='maa_damage_mult = 0.05',
        maa=None,
        name='Vorpal Bullets',
        desc='The Vorpal bullet uses a pointed shape and precise enchantments in order to improve its speed and ability to pierce armor, improving the firepower of our armies.',
    ),
    dict(
        key='arcane_blaster',
        category='military',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrMi2.dds',
        modifier='gunpowder_damage_mult = 0.2',
        maa=None,
        name='Arcane Blaster',
        desc='Arcane blasters channel magical power through a steel rig into a concentrated bolt, giving our War Artificers a new and powerful weapon.',
    ),
    dict(
        key='avatar_supersoldier_serum',
        category='military',
        tier=2,
        faith='faith = { religion = religion:cannorian_pantheon_religion }',
        gnome_only=False,
        icon='Artf_BrMi2.dds',
        modifier='gunpowder_toughness_mult = 0.15\nknight_effectiveness_mult = 0.1',
        maa=None,
        name='Avatar Supersoldier Serum',
        desc='The Avatar Supersoldier Serum, though usually fatal to those who use it, grants its users abilities like supernatural strength and agility to leverage against our enemies.',
    ),
    dict(
        key='balloonboost_packs',
        category='military',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrMi2.dds',
        modifier='advantage = 3',
        maa=None,
        name='Balloonboost Packs',
        desc='The use of Balloonboost Packs in reconnaissance will allow our military leaders to respond to enemy movements far more effectively than before.',
    ),
    dict(
        key='coddorran_powered_exosuit',
        category='military',
        tier=2,
        faith=None,
        gnome_only=True,
        icon='Artf_BrMi2.dds',
        modifier='gunpowder_toughness_mult = 0.2',
        maa=None,
        name='Coddorran Powered Exoskeleton',
        desc='Named after the place of their invention, the Coddorran Exosuit allows is a damestear-powered suit of plate with deadly armaments including palm-mounted sparkdrive blasters.',
    ),
    dict(
        key='gu_boats',
        category='military',
        tier=2,
        faith=None,
        gnome_only=True,
        icon='Artf_MaMi2.dds',
        modifier='naval_movement_speed_mult = 0.2\nembarkation_cost_mult = -0.25\nretreat_losses = -0.15',
        maa=None,
        name='G-U Boats',
        desc="G-U Boats can sneak up on enemy ships making privateering easier, as well as enforcing blockades - they can't fight what they can't detect!",
    ),
    dict(
        key='lullaby_cannon',
        category='military',
        tier=2,
        faith='faith = faith:skaldhyrric_faith',
        gnome_only=False,
        icon='Artf_BrMi2.dds',
        modifier='advantage = 3',
        maa=None,
        name='Lullaby Cannon',
        desc='These cannons project the song-spells of skalds across leagues, irresistibly putting enemies to sleep.',
    ),
    dict(
        key='prototype_tanks',
        category='military',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_MaMi2.dds',
        modifier='heavy_cavalry_damage_mult = 0.1',
        maa='aov_prototype_tanks',
        name='Prototype Tanks',
        desc='Large metal war machines can replace small numbers of cavalry, improving our firepower by orders of magnitude.',
    ),
    dict(
        key='wandlocks',
        category='military',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_TeMi2.dds',
        modifier='gunpowder_damage_mult = 0.1\ngunpowder_toughness_mult = 0.05',
        maa=None,
        name='Wandlocks',
        desc="By exchanging the typical gun's paper cartridge with a specialized spell scroll, simple spells can now be cast from the barrel of the gun - from magic missiles to fireballs, to oddly enough, soldiers shooting themselves to apply protective spells!",
    ),
    dict(
        key='war_golems',
        category='military',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_TeMi2.dds',
        modifier='heavy_infantry_damage_mult = 0.1',
        maa='aov_war_golems',
        name='War Golems',
        desc='Stone golems powered by magic can serve as an effective shock force due to their durable construction.',
    ),
    dict(
        key='artillery_autoloader',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_MaMi3.dds',
        modifier='siege_phase_time = -0.15\nsiege_weapon_max_size_add = 1',
        maa=None,
        name='Artillery Autoloader',
        desc='A machine that automatically reloads a cannon with minimal user input. This drastically reduces reload times, improving artillery firepower in the process.',
    ),
    dict(
        key='bioartificed_ascension',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_BrMi3.dds',
        modifier='gunpowder_toughness_mult = 0.25',
        maa=None,
        name='Bioartificed Ascension',
        desc="The biological transmutation of our soldiers into horrifically-powerful forms. The permanent shapes of dragons, giants, and more have all become available to us: and this is without mentioning the simple possibilities of making soldiers' skins tougher, their muscles larger, and their bodies more capable of resisting pain and shock.",
    ),
    dict(
        key='black_damestear_bullets',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_MaMi3.dds',
        modifier='maa_damage_mult = 0.05\nmaa_toughness_mult = 0.05',
        maa=None,
        name='Black Damestear Bullets',
        desc='Following the typical bluntness of the Machinery School of artifice, black damestear bullets are simple but devastatingly effective invention. Ordinary bullets given cores of black damestear, they are capable of penetrating most magical defenses and stripping the power from mages that they hit.',
    ),
    dict(
        key='damestear_reactor_megacannon',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeMi3.dds',
        modifier='martial = 1',
        maa='aov_damestear_megacannon',
        name='Damestear Reactor Megacannon',
        desc='A cannon, built out of mithril and insulated with porcelain, which channels the mana of damestear into a beam of unbelievable power. The final evolution of the Sparkdrive, which can shoot beams of energy that decimate entire battlefields.',
    ),
    dict(
        key='demonflame_flamethrowers',
        category='military',
        tier=3,
        faith='faith = { religion = religion:xhazobkult_religion }',
        gnome_only=False,
        icon='Artf_BrMi3.dds',
        modifier='gunpowder_damage_mult = 0.15\ndread_decay_mult = -0.1',
        maa=None,
        name='Demonflame Flamethrowers',
        desc="Massive weapons that fling demonfire at our foes shall give our artificer regiments a fraction of the Xhazobine's own fiery strength.",
    ),
    dict(
        key='military_sky_galleons',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_MaMi3.dds',
        modifier='movement_speed = 0.15\nadvantage = 5',
        maa=None,
        name='Military Sky Galleons',
        desc='These new flying ships are able to change the face of warfare as we know it, capable of shooting from their elevated positions to great effect.',
    ),
    dict(
        key='naval_mageshields',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeEc3.dds',
        modifier='embarkation_cost_mult = -0.3\nnaval_movement_speed_mult = 0.1',
        maa=None,
        name='Naval Mageshields',
        desc='A coating, imbued with abjuration magic, allows a magical shield to be projected along any ship, from bow to stern.',
    ),
    dict(
        key='personal_mageshields',
        category='military',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeMi3.dds',
        modifier='gunpowder_toughness_mult = 0.2\nhealth = 0.25',
        maa=None,
        name='Personal Mageshields',
        desc='We can now stably project mageshields to protect the individual, allowing our war artificers to shrug off the standard projectiles and deadly blows.',
    ),
    dict(
        key='apparitional_communicator',
        category='society',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo1.dds',
        modifier='monthly_prestige = 1',
        maa=None,
        name='Apparitional Communicator',
        desc='By sponsoring a variant of the T-wave transmitter which transmits images as well as sound we can improve our standing in the eyes of the world.',
    ),
    dict(
        key='centipedal_chests',
        category='society',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo1.dds',
        modifier='travel_speed = 15\ntravel_danger = -5',
        maa=None,
        name='Centipedal Chests',
        desc='Living chests which are able to move around and carry goods, scuttling around on a 100 little legs, and fiercely loyal to their owners.',
    ),
    dict(
        key='conversation_calibrator',
        category='society',
        tier=1,
        faith=None,
        gnome_only=True,
        icon='Artf_BrSo2.dds',
        modifier='different_culture_opinion = 10\ngeneral_opinion = 3',
        maa=None,
        name='Conversation Calibrator',
        desc='Devices using the power of illusion magic to create the appearance of speech that may be more comprehensible for non-gnomish understanding.',
    ),
    dict(
        key='fey_spray',
        category='society',
        tier=1,
        faith='faith = { religion = religion:fey_religion }',
        gnome_only=False,
        icon='Artf_TeSo1.dds',
        modifier='county_opinion_add = 5',
        maa=None,
        name='Fey Spray',
        desc='The ability to keep the Fey away without harming them is very popular with those who have grown tired of their mischief, and the spray does not cause undue offense to these mystical beings.',
    ),
    dict(
        key='living_mirrors',
        category='society',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo1.dds',
        modifier='cultural_acceptance_gain_mult = 0.25\ncounty_opinion_add = 5',
        maa=None,
        name='Living Mirrors',
        desc='Exerting influence on the Living Mirror business will allow us to easily broadcast propaganda, as well as better distracting potential malcontents.',
    ),
    dict(
        key='mystic_ciphers',
        category='society',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo1.dds',
        modifier='enemy_hostile_scheme_success_chance_add = -10\nowned_hostile_scheme_success_chance_add = 5',
        maa=None,
        name='Mystic Ciphers',
        desc='Brand new magical cyphers allow us to bring our secrecy to whole new levels, making it harder than ever to identify our foreign spies or discover state secrets.',
    ),
    dict(
        key='sending_stones',
        category='society',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo1.dds',
        modifier='diplomacy = 1\ncouncillor_opinion = 10',
        maa=None,
        name='Sending Stones',
        desc='Magical stones, created through artifice, facilitate the transmission of communications across long distances at instant speed.',
    ),
    dict(
        key='viewcatcher',
        category='society',
        tier=1,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo1.dds',
        modifier='monthly_dynasty_prestige_mult = 0.1',
        maa=None,
        name='Viewcatcher',
        desc='A handheld machine, able to capture images for printing in a single instant, to be preserved forever.',
    ),
    dict(
        key='arithmatons',
        category='society',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo2.dds',
        modifier='domain_tax_mult = 0.1\nvassal_tax_mult = 0.1',
        maa=None,
        name='Arithmatons',
        desc='The Arithmatons can perform arithmetic far faster and far more accurately than most men, making many fields with heavy mathematics remarkably simpler.',
    ),
    dict(
        key='empire_engine',
        category='society',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo2.dds',
        modifier='title_creation_cost_mult = -0.15',
        maa=None,
        name='Empire Engine',
        desc="An engine which uses Wish magic from Bulwar, Runewriting from dwarves and giants, and Fey relics from Eordand and the Deepwoods to metaphysically imbue your nation with the concept of 'Power.' Its inventors are pretty sure it works: and even if it doesn't, enough people think it does for it to work in practice anyways.",
    ),
    dict(
        key='game_of_khet',
        category='society',
        tier=2,
        faith='faith = { religion = religion:khetism_religion }',
        gnome_only=False,
        icon='Artf_TeSo2.dds',
        modifier='vassal_opinion = 5\ncounty_opinion_add = 5',
        maa=None,
        name='Game of the Khet',
        desc='An ancient game played by the Khet, using stone tablets imbued with the images of fearsome monsters. Now, through artifice, it can be distributed in the form of cards among our people, allowing the powerful and common alike to settle their disputes through a far less violent, and far more entertaining, form of duelling.',
    ),
    dict(
        key='mirage_detector_3000',
        category='society',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo2.dds',
        modifier='faith_conversion_piety_cost_mult = -0.15\nmonthly_piety_gain_mult = 0.1',
        maa=None,
        name='Miracle Detector 3000',
        desc="A completely objective, fact-based device which calculates levels of 'Divinity,' 'Power,' and 'Morality' for each religion in the world, and calculates a sum of these three as 'God-Points.' It just so happens that the religion with the highest number of 'God-Points'... is ours! Isn't it great that we're correct about the world?",
    ),
    dict(
        key='remedial_tinctures',
        category='society',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_MaSo2.dds',
        modifier='hard_casualty_modifier = -0.1\nhealth = 0.25',
        maa=None,
        name='Remedial Tinctures',
        desc="These kits contain unique potions, self-tightening tourniquets, and all required to get a soldier off of Nerat's doorstep and back to the battlefield in scarce hours.",
    ),
    dict(
        key='think_thought_transmitters',
        category='society',
        tier=2,
        faith=None,
        gnome_only=False,
        icon='Artf_BrSo2.dds',
        modifier='general_opinion = 5\ndiplomacy = 1',
        maa=None,
        name='The Think-Thought Transmitters',
        desc="A machine which attaches to the mind, body, and soul, and beams thoughts directly to other people. These thoughts expand past the boundary of mere 'words': with the Thinking Transmitters, everything from memories, to emotions, to patterns of thinking can be expressed without language!",
    ),
    dict(
        key='bureaucratizer',
        category='society',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo3.dds',
        modifier='domain_limit = 1\nvassal_limit = 10',
        maa=None,
        name='The Bureaucratizer',
        desc='A machine which feeds performance reviews, test scores, and job reports to a temporarily mind-wiped bureaucrat. Without any loyalties or context to pull from, the bureaucrat can only use the information given to them when determining who shall be appointed to various administrative posts across our nation.',
    ),
    dict(
        key='crierless_crier_device',
        category='society',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo3.dds',
        modifier='stewardship = 2\nmonthly_county_control_growth_add = 0.2',
        maa=None,
        name='Crierless Crier Device',
        desc='Large, portable machines capable of artificially recording and reproducing sounds, to be broadcast in public spaces.',
    ),
    dict(
        key='negotiation_nexus',
        category='society',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo3.dds',
        modifier='diplomacy_per_prestige_level = 1',
        maa=None,
        name='Negotiation Nexus',
        desc='A machine which reads the minds and behaviors of all parties in a negotiation, tabulates what each person wants, and then gives our negotiating parties access to the analyzed data. Aids in all types of negotiations and peace-deals.',
    ),
    dict(
        key='runethought_network',
        category='society',
        tier=3,
        faith=None,
        gnome_only=False,
        icon='Artf_TeSo3.dds',
        modifier='cultural_acceptance_gain_mult = 0.35\ncultural_head_fascination_mult = 0.1',
        maa=None,
        name='The Runethought Network',
        desc='A network of runic towers, each engraved with aspects of our language and culture, which are set up across our nation. When activated through Halessi spirit-magics, these towers imbue their runes into the minds of our citizens. Each of them learns our language, our values, and our ideals, whether or not they want to.',
    ),
]
