# generated by tools/import_eu4_monuments.py; edit bulwar_hand.py, not this file

MONUMENTS = [{'eu4_key': 'anzarzax_palace',
  'source': 'anbennar',
  'name': 'Arzax Eklu',
  'desc': 'Buried amidst the sandy hills of Anzarzax lay the last, crumbling edifice of a once-grand '
          'construction - the Eternal White Palace, the Arzax Eklu. Constructed in the latter years of the '
          'Bulwari Age of Monsters by packlord Arzax, the palace served as the heart of the Ever-Richer '
          'Kingdom of Arzax, a territorially small yet exceedingly wealthy state born from the waning '
          'influence of the kingdoms of Uak and Proxacha. The marble opulence of the Arxax Eklu stood in '
          'harsh contrast to the withering drylands it was built upon, its unorthodox location chosen '
          "specifically to discredit Arzax's rivals, who claimed it was daft to build a palace in a desert. "
          'Ultimately the rise of the Xhazobine would see the palace utterly destroyed, its corpulent '
          'occupants put to the torch and its marble walls scattered. Yet its legacy endured, such that '
          "whenever a gnoll looked upon fine marble they called it 'arzax'.",
  'levels': ['aov_monument_anzarzax_palace_01',
             'aov_monument_anzarzax_palace_02',
             'aov_monument_anzarzax_palace_03'],
  'barony': 'b_anzarzax',
  'province': 590,
  'start_level': 0,
  'category': 'palace',
  'gate': 'culture = { has_cultural_pillar = heritage_gnollish }',
  'gate_desc': 'Gnollish',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'monthly_county_control_growth_add': 0.125},
             'character_modifier': {'vassal_tax_contribution_mult': 0.075},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: province_event = { id = flavour_tluukt.57 }']},
            {'province_modifier': {},
             'county_modifier': {'supply_limit_mult': 0.25, 'monthly_county_control_growth_add': 0.125},
             'character_modifier': {'vassal_tax_contribution_mult': 0.125, 'diplomacy': 1},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: province_event = { id = flavour_tluukt.58 }']},
            {'province_modifier': {},
             'county_modifier': {'development_growth_factor': 0.15, 'supply_limit_mult': 0.5},
             'character_modifier': {'vassal_tax_contribution_mult': 0.15, 'diplomacy': 2},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['diplomatic_upkeep: EU4 relation slots; no CK3 equivalent',
                         'on_upgraded: province_event = { id = flavour_tluukt.59 }']}],
  'art': None,
  'notes': ['gate atom tag:F74 ignored (no CK3 equivalent)',
            'mission-spawned in EU4 (start province read from a commented start)',
            'Balance cap: EU4 tier 3 adds a flat supply_limit of 40 (county supply_limit_mult 10.25 through '
            'the table); level 3 gets supply_limit_mult 0.5.']},
 {'eu4_key': 'ash_palace',
  'source': 'anbennar',
  'name': 'The Ash Palace',
  'desc': 'The sprawling palace complex nowadays known as the Ash Palace of Sareyand has a long and storied '
          'history. Once the site of a grandiose Djinn palace during the time of the Darkness Sultanates, '
          'the palace of Proxacha Eklu was erected on its ruins during the Age of Monsters, as the heart of '
          'the gnollish capital of Raxaklu. After the fall of the gnollish kingdom, the palace ruins stood '
          'untouched for many centuries due to the superstitious fear and resentment of the local human '
          'Bulwari, the city around it eventually razed to the ground by the Red Xhaz. Only after Jaher '
          'liberated Bulwar was the area finally resettled again. Eledas Sarelzuir founded Sareyand and '
          'built a palace on the hill overlooking his new city, incidentally choosing the location of both '
          "previous palace complexes. This palace would earn the epithet 'Ash Palace' after a failed "
          'assassination attempt left the palace a charred ruin and a young Jexis, the later Phoenix '
          'Empress, disfigured for life. After the first Cinder War,a limited reconstruction began, aimed at '
          'rendering one wing of the sprawling palace complex inhabitable again as an official residence of '
          'the Sarelzuir dynasty. Despite a checkered history in the last several centuries, the Ash Palace '
          'has over the millennia been chosen again and again as the seat of empires, its location making it '
          'a natural choice for anyone wishing to rule all of Bulwar and beyond. And like embers within the '
          'ashes, the fires of conquest can easily be rekindled by anyone seated on the sunfire throne of '
          'the Ash Palace.',
  'levels': ['aov_monument_ash_palace_01', 'aov_monument_ash_palace_02', 'aov_monument_ash_palace_03'],
  'barony': 'b_sareyand',
  'province': 625,
  'start_level': 1,
  'category': 'palace',
  'gate': 'OR = { faith.religion = religion:bulwari_sun_cults_religion culture = { has_cultural_pillar = '
          'heritage_bulwari } culture = { has_cultural_pillar = heritage_gnollish } culture = '
          'culture:sun_elvish culture = { has_cultural_pillar = heritage_elven } }',
  'gate_desc': 'Bulwari Sun Cults, Bulwari, Gnollish, Sun Elvish, Elven',
  'tiers': [{'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'domain_limit': 1},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['local_state_maintenance_modifier: EU4 states; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = ash_palace.tt',
                         'on_upgraded: if owner = { mission_completed = mulen_successful_venture }: '
                         'set_province_flag = roost_allowed',
                         'on_upgraded: if owner = { mission_completed = mulen_successful_venture }: '
                         'custom_tooltip = ash_palace_roost_tt',
                         'on_upgraded: if owner = { is_or_was_tag = { tag = F33 } }: '
                         'F80_se_monument_copy_modifier_effect = { required_mission = '
                         'F80_mission_not_so_far_anymore monument = ash_palace tier = 1 }']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'domain_limit': 2},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['local_state_maintenance_modifier: EU4 states; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = ash_palace_golden_way.tt',
                         'on_upgraded: if owner = { is_or_was_tag = { tag = F33 } }: '
                         'F80_se_monument_copy_modifier_effect = { required_mission = '
                         'F80_mission_not_so_far_anymore monument = ash_palace tier = 2 }']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'domain_limit': 2},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['local_state_maintenance_modifier: EU4 states; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = ash_palace_tier_3.tt',
                         'on_upgraded: every_owned_province = { limit = { has_province_modifier = '
                         'golden_highway } add_province_modifier = { name = golden_highway_v2 duration = -1 '
                         'hidden = yes } }',
                         'on_upgraded: if is_or_was_tag = { tag = F33 }: random_known_country = { limit = { '
                         'is_or_was_tag = { tag = F80 } } if = { limit = { exists = yes mission_completed = '
                         'F80_mission_not_so_far_anymore } every_owned_province = { limit = { '
                         'has_province_modifier = golden_highway } add_province_modifier = { name = '
                         'golden_highway_v2 duration = -1 hidden = yes } } } }',
                         'on_upgraded: if owner = { is_or_was_tag = { tag = F33 } }: '
                         'F80_se_monument_copy_modifier_effect = { required_mission = '
                         'F80_mission_not_so_far_anymore monument = ash_palace tier = 3 }']}],
  'art': None,
  'notes': ['gate atom flag:ash_palace_enabled ignored (no CK3 equivalent)',
            'gate atom tag:F52 ignored (no CK3 equivalent)',
            'gate atom religion:yudunyovi ignored (no CK3 equivalent)',
            'Balance cap: EU4 governing capacity +100/175/250 is domain_limit 4/7/10 through the table; '
            "capped at 1/2/2 (Cannor's largest is 2)."]},
 {'eu4_key': 'dasmati_halls_of_reverence',
  'source': 'cannorian',
  'name': 'Dasmati Halls of Reverence',
  'desc': 'The Halls of Reverence are where the Maqeti people buried their former kings, honored for their '
          'achievements in the struggle against the gnollish slavers that once hunted them.',
  'levels': ['aov_monument_dasmati_halls_of_reverence_01',
             'aov_monument_dasmati_halls_of_reverence_02',
             'aov_monument_dasmati_halls_of_reverence_03'],
  'barony': 'b_dasmatus',
  'province': 5668,
  'start_level': 1,
  'category': 'tomb',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_bulwari } faith.religion = '
          'religion:bulwari_sun_cults_religion }',
  'gate_desc': 'Bulwari, Bulwari Sun Cults',
  'tiers': [{'province_modifier': {'fort_level': 1},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.1, 'monthly_legitimacy_add': 0.0625},
             'on_complete': '',
             'cost': 300,
             'days': 1800,
             'dropped': ['republican_tradition: government-specific twin of legitimacy (translated); EU4 '
                         'gives only the one that applies',
                         'devotion: government-specific twin of legitimacy (translated); EU4 gives only the '
                         'one that applies',
                         'horde_unity: government-specific twin of legitimacy (translated); EU4 gives only '
                         'the one that applies',
                         'meritocracy: government-specific twin of legitimacy (translated); EU4 gives only '
                         'the one that applies']},
            {'province_modifier': {'fort_level': 1},
             'county_modifier': {'levy_size': 0.0625},
             'character_modifier': {'monthly_prestige': 0.25, 'monthly_legitimacy_add': 0.125},
             'on_complete': '',
             'cost': 800,
             'days': 3600,
             'dropped': ['republican_tradition: government-specific twin of legitimacy (translated); EU4 '
                         'gives only the one that applies',
                         'devotion: government-specific twin of legitimacy (translated); EU4 gives only the '
                         'one that applies',
                         'horde_unity: government-specific twin of legitimacy (translated); EU4 gives only '
                         'the one that applies',
                         'meritocracy: government-specific twin of legitimacy (translated); EU4 gives only '
                         'the one that applies',
                         'establish_order_cost: EU4 subject interaction; no CK3 equivalent']},
            {'province_modifier': {'fort_level': 2},
             'county_modifier': {'levy_size': 0.25, 'build_gold_cost': -0.125},
             'character_modifier': {'monthly_prestige': 0.5, 'monthly_legitimacy_add': 0.25},
             'on_complete': '',
             'cost': 1600,
             'days': 7200,
             'dropped': ['republican_tradition: government-specific twin of legitimacy (translated); EU4 '
                         'gives only the one that applies',
                         'devotion: government-specific twin of legitimacy (translated); EU4 gives only the '
                         'one that applies',
                         'horde_unity: government-specific twin of legitimacy (translated); EU4 gives only '
                         'the one that applies',
                         'meritocracy: government-specific twin of legitimacy (translated); EU4 gives only '
                         'the one that applies',
                         'establish_order_cost: EU4 subject interaction; no CK3 equivalent']}],
  'art': 'gfx/interface/great_projects/great_project_dasmati_halls_of_reverence.dds',
  'notes': []},
 {'eu4_key': 'ebbusubtu',
  'source': 'anbennar',
  'name': 'Ebbušubtu',
  'desc': 'Rising like a mirage above the Salahad, ancient Ebbušubtu towers. This westernmost peak of the '
          'Paravimvata range is known to the Bulwari as the Mountain of Clear Sight. The mountain itself is '
          'riddled with the remains of an abandoned djinn palace. These ruins were shunned by the local '
          'Mašnsih and only sporadically entered by harpy squatters, until Andrellion of the Desert Legion '
          'was brought here by his harpy allies. There he established his headquarters, and with the rise of '
          'the Jadd, the palace has been restored and expanded, the spiritual center of the Jaddari Legion. '
          'The palace contains many grand halls and terraces carved from the rock, with secluded gardens and '
          'awe-inspiring views littered throughout its heights. While many pilgrims arrive every day, only a '
          'few attempt to ascend the Endless Stair, ending in a colossal platform atop a lesser peak, from '
          'which the pilgrims can view the sun rising over the summit of Ebbušubtu, where it is said Jaddar '
          'received his revelations.',
  'levels': ['aov_monument_ebbusubtu_01', 'aov_monument_ebbusubtu_02', 'aov_monument_ebbusubtu_03'],
  'barony': 'b_ebbusubtu',
  'province': 2909,
  'start_level': 1,
  'category': 'temple',
  'gate': '',
  'gate_desc': '',
  'tiers': [{'province_modifier': {'garrison_size': 0.1},
             'county_modifier': {'development_growth_factor': 0.05, 'levy_reinforcement_rate': 0.15},
             'character_modifier': {'monthly_piety': 0.5},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {'garrison_size': 0.2},
             'county_modifier': {'development_growth_factor': 0.1, 'levy_reinforcement_rate': 0.25},
             'character_modifier': {'monthly_piety': 0.75, 'faith_conversion_piety_cost_mult': -0.1},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = bulwar_flavour.301.tta',
                         'on_upgraded: set_global_flag = ebbusubtu_pilg_timer',
                         'on_upgraded: country_event = { id = bulwar_flavour.301 }']},
            {'province_modifier': {'garrison_size': 0.2},
             'county_modifier': {'development_growth_factor': 0.15, 'levy_reinforcement_rate': 0.25},
             'character_modifier': {'monthly_piety': 1, 'faith_conversion_piety_cost_mult': -0.1},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = bulwar_flavour.301.ttb',
                         'on_upgraded: country_event = { id = bulwar_flavour.301 }',
                         'on_upgraded: jadd_holy_order_reformed = yes']}],
  'art': 'gfx/interface/great_projects/great_project_ebbusubtu.dds',
  'notes': ['gate atom religion:the_jadd ignored (no CK3 equivalent)',
            'Gate decision: left open. EU4 gates it on the Jadd, which arises centuries after 1022; any '
            'holder may use it.',
            'Balance cap: EU4 fervor +1/+2 and tolerance give monthly_piety 0.5/1/2; capped at 0.5/0.75/1.']},
 {'eu4_key': 'eduz_ginakku',
  'source': 'anbennar',
  'name': 'Eduz-Ginakku',
  'desc': "On the northern shore of the Saluraš, connected to old Aqatbar by Kalešin's Bridge, lies the "
          'temple city of Eduz-Ginakku, also called the Great Library of Aqatbar by foreigners. While the '
          'true origins of the temple-library are uncertain, many favor the theory that it was Birsartan the '
          'Scribe, who brought the Sun Cult to Bahar, who founded the temple. Over the centuries, '
          'Eduz-Ginakku grew to include not only the central temple complex, but also countless scriptoria, '
          'libraries, and workshops, as well as housing for the clergy. The temple-garden surrounding the '
          'central Ziggurat with its famed Altar of the Truth is unique as well, as papyrus reeds and a vast '
          'array of flowers used in the production of ink dyes are grown there, instead of the more '
          "traditionally grown decorative plants. One quarter of the library district is occupied by Zheh's "
          'palace-fortress, built by the gnollish matriarch Zheh who came to Aqatbar for plunder but fell in '
          'love with the amassed knowledge found in Eduz-Ginakku and became a famed patron of the literary '
          'arts. Eduz-Ginakku has been one of if not the most prominent center of scholarship and learning '
          'in all of Bulwar, and has been the undisputed religious center of eastern Bahar for millennia. It '
          'is here where Cannorians desiring to sip from the fountain of wisdom of Bulwari civilization come '
          'to broaden their horizons.',
  'levels': ['aov_monument_eduz_ginakku_01', 'aov_monument_eduz_ginakku_02', 'aov_monument_eduz_ginakku_03'],
  'barony': 'b_azka_trigranas',
  'province': 536,
  'start_level': 1,
  'category': 'library',
  'gate': 'faith.religion = religion:bulwari_sun_cults_religion',
  'gate_desc': 'Bulwari Sun Cults',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'monthly_county_control_growth_add': 0.05},
             'character_modifier': {'monthly_learning_lifestyle_xp_gain_mult': 0.02},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['institution_spread_from_true_faith: EU4 institutions; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {'monthly_county_control_growth_add': 0.1},
             'character_modifier': {'monthly_learning_lifestyle_xp_gain_mult': 0.06,
                                    'clergy_opinion': 5,
                                    'different_culture_opinion': 10},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['institution_spread_from_true_faith: EU4 institutions; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: add_building = cathedral']},
            {'province_modifier': {},
             'county_modifier': {'monthly_county_control_growth_add': 0.1},
             'character_modifier': {'monthly_learning_lifestyle_xp_gain_mult': 0.1,
                                    'clergy_opinion': 7.5,
                                    'different_culture_opinion': 10},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['institution_spread_from_true_faith: EU4 institutions; no CK3 equivalent',
                         'free_dip_policy: EU4 policies; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: add_building = university',
                         'on_upgraded: custom_tooltip = eduz_ginakku.tt',
                         'on_upgraded: every_owned_province = { limit = { has_building = university } '
                         'add_province_modifier = { name = eduz_ginakku_university duration = -1 hidden = '
                         'yes } }']}],
  'art': 'gfx/interface/great_projects/great_project_eduz_ginakku.dds',
  'notes': ['gate atom tag:U17 ignored (no CK3 equivalent)',
            'gate atom tag:F52 ignored (no CK3 equivalent)',
            'gate atom religion:yudunyovi ignored (no CK3 equivalent)',
            'gate atom flag:eduz_mission_bypass_flag ignored (no CK3 equivalent)']},
 {'eu4_key': 'eka_idulnazzar',
  'source': 'anbennar',
  'name': 'Eka-Idulnazzar',
  'desc': "The Eka-Idulnazzar - translated to 'Palace Whose Halls Shine with Wisdom' - was founded to break "
          'the hold of the insular magi clans over the treasure trove of Bulwari magic knowledge as well as '
          'to overcome the chasm between elven and human magi fostered by the Jexisian Statutes. The '
          'ultimate goal of the institution was thus to usher in a new age of cooperative innovation for '
          'Bulwari magic. It swiftly became the premier magical academy in all of Bulwar, counting not just '
          'elves and humans, but harpies, gnolls and goblins amongst its students. The academic interests of '
          'the magi-scholars assembled there were not limited to Bulwari magic and the genie wish magic '
          'which preceded it, however. Sun Elven spells, dwarven rune magic, harpy song magic and even '
          'goblin proto-artificery and gnollish shamanistic rites became subjects of study there. The '
          'Eka-Idulnazzar follows traditional Zanite architectural convention and is arranged around a vast '
          'central courtyard. Radiating outward from this central court is a veritable city within the city, '
          'comprising lecture halls, training rooms, libraries, dormitories and residences for the resident '
          'scholars.',
  'levels': ['aov_monument_eka_idulnazzar_01',
             'aov_monument_eka_idulnazzar_02',
             'aov_monument_eka_idulnazzar_03'],
  'barony': 'b_zandazar',
  'province': 609,
  'start_level': 0,
  'category': 'academy',
  'gate': '',
  'gate_desc': '',
  'tiers': [{'province_modifier': {'garrison_size': 0.1},
             'county_modifier': {'development_growth_factor': 0.15},
             'character_modifier': {'monthly_magic_lifestyle_xp_gain_mult': 0.06},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: clr_country_flag = extended_conj_2',
                         'on_upgraded: if any_hired_mercenary_company = { template = merc_leashed_elementals '
                         '}: random_hired_mercenary_company = { limit = { template = merc_leashed_elementals '
                         '} disband_mercenary_company = THIS }',
                         'on_upgraded: custom_tooltip = eka_idulnazzar.tt',
                         'on_upgraded: if owner = { is_or_was_tag = { tag = F33 } }: '
                         'F80_se_monument_copy_modifier_effect = { required_mission = '
                         'F80_mission_the_palace_of_wisdom monument = eka_idulnazzar tier = 1 }']},
            {'province_modifier': {'garrison_size': 0.2},
             'county_modifier': {'development_growth_factor': 0.25},
             'character_modifier': {'monthly_magic_lifestyle_xp_gain_mult': 0.13},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['max_estate_spell_levels: EU4 estate system; CK3 has no estates',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: if owner = { is_or_was_tag = { tag = F33 } }: '
                         'F80_se_monument_copy_modifier_effect = { required_mission = '
                         'F80_mission_the_palace_of_wisdom monument = eka_idulnazzar tier = 2 }']},
            {'province_modifier': {'garrison_size': 0.25},
             'county_modifier': {'development_growth_factor': 0.25},
             'character_modifier': {'monthly_magic_lifestyle_xp_gain_mult': 0.2},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['max_estate_spell_levels: EU4 estate system; CK3 has no estates',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = give_magical_infrastructure_perm_bypass',
                         'on_upgraded: if owner = { is_or_was_tag = { tag = F33 } }: '
                         'F80_se_monument_copy_modifier_effect = { required_mission = '
                         'F80_mission_the_palace_of_wisdom monument = eka_idulnazzar tier = 3 }']}],
  'art': 'gfx/interface/great_projects/great_project_eka_idulnazzar.dds',
  'notes': []},
 {'eu4_key': 'ger_bexamurr',
  'source': 'anbennar',
  'name': 'Ger-Bexamurr',
  'desc': 'Located in Windsculpt Pass, far away from any settlement, the Ger-Bexamurr is a Xhazobkultist '
          'temple complex. It contains several buildings and altars within a circular layout, interrupted by '
          'a small black stone wall. Below the temple lies a vast and complex network of tunnels, a massive '
          'labyrinth in which no light can be lit. It is said that demons walk through the tunnels, killing '
          'and eating all those who they deem unworthy. In the centre of the labyrinth lies the Talazdvoger, '
          'the border with death itself: a black, bottomless pit where the remains of those sacrificed are '
          'thrown, a place fit for the Pits of Grilax, a place out of myth. The priests believe that the pit '
          'feeds on the demonic power of the dead, and once it satisfies its hunger, it will create a breach '
          'between the realm of Xhazob and the material plane. While most Xhazobkultists will principally '
          'sacrifice anyone to their demonic masters, the priests of the Ger-Bexamurr only sacrifice those '
          'who possess a great demonic power. They sacrifice living and dead beings alike, and it is said '
          'that in antiquity they managed to retrieve the remains of the Xhazobine, sacrificing her remains '
          'to the Talazdvoger.',
  'levels': ['aov_monument_ger_bexamurr_01', 'aov_monument_ger_bexamurr_02', 'aov_monument_ger_bexamurr_03'],
  'barony': 'b_windsculpt_pass',
  'province': 6712,
  'start_level': 0,
  'category': 'temple',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_gnollish } faith.religion = '
          'religion:xhazobkult_religion }',
  'gate_desc': 'Gnollish, Xhazobkult',
  'tiers': [{'province_modifier': {'garrison_size': 0.1},
             'county_modifier': {},
             'character_modifier': {'faith_conversion_piety_cost_mult': -0.1},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: if owner = { has_estate_privilege = estate_mages_moment_of_felflame '
                         '}: custom_tooltip = zokka_ger_bexamurr_1_tt',
                         'on_upgraded: else: custom_tooltip = ger_bexamurr_1_tt',
                         'on_upgraded: custom_tooltip = ger_bexamurr_demonic_cost_tt',
                         'on_upgraded: add_or_extend_country_modifier_indefinitely = { name = '
                         'ger_bexamurr_reach_across_the_talazdvoger duration = 3650 }']},
            {'province_modifier': {'garrison_size': 0.15},
             'county_modifier': {},
             'character_modifier': {'faith_conversion_piety_cost_mult': -0.1, 'monthly_piety': 0.5},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = ger_bexamurr_2_tt',
                         'on_upgraded: custom_tooltip = ger_bexamurr_demonic_cost_tt',
                         'on_upgraded: add_or_extend_country_modifier_indefinitely = { name = '
                         'ger_bexamurr_reach_across_the_talazdvoger duration = 3650 }']},
            {'province_modifier': {'garrison_size': 0.25},
             'county_modifier': {},
             'character_modifier': {'faith_conversion_piety_cost_mult': -0.2, 'monthly_piety': 1},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = ger_bexamurr_3_tt',
                         'on_upgraded: custom_tooltip = ger_bexamurr_demonic_cost_tt',
                         'on_upgraded: add_or_extend_country_modifier_indefinitely = { name = '
                         'ger_bexamurr_reach_across_the_talazdvoger duration = 3650 }']}],
  'art': None,
  'notes': []},
 {'eu4_key': 'mount_lazzaward',
  'source': 'anbennar',
  'name': 'Mount Lazzaward',
  'desc': 'Mount Lazzaward, also known as Mount Serrukur, is a sacred mountain located in the lower slopes '
          'of the Serpentspine in the lands of the Gelkar kingdom of Lawaššar. The mountain is home to '
          'Lahmaš the Wise-master, leader of the Lamassus and one of the Sun Cult Erbatraši, as well as '
          'several clans of Kurešimi, mages that practice the art of Inscription. The mountain, believed to '
          'be the result of Wish or unknown magic, is completely made of Lapis Lazuli, with large veins of '
          'pyrite inclusions that give the mountain a dim glow during daytime. The top of the mountain is '
          'permanently covered by snow. Millennia ago, Lahmaš made its residence near the top of the '
          'mountain, and since then, a massive temple complex has been built, home to priests, scribes, and '
          "Lahmaš' students in the ways of Bulwari magic, and In the roots of the mountains lies "
          'Kurešim-kišbar, the city of the Wishcrafters, where most of the best mages and artisans from all '
          'of Bulwar practice the art of Inscription, the fabrication of magic items.',
  'levels': ['aov_monument_mount_lazzaward_01',
             'aov_monument_mount_lazzaward_02',
             'aov_monument_mount_lazzaward_03'],
  'barony': 'b_lawassar',
  'province': 2956,
  'start_level': 0,
  'category': 'temple',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_bulwari } culture = culture:sun_elvish culture '
          '= { has_cultural_pillar = heritage_elven } }',
  'gate_desc': 'Bulwari, Sun Elvish, Elven',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'tax_mult': 0.03, 'building_slot_add': 1},
             'character_modifier': {},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.06, 'building_slot_add': 1},
             'character_modifier': {},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: if owner = { NOT = { tag = F29 } }: country_event = { id = '
                         'bulwar_flavour.137 days = 1 }',
                         'on_upgraded: if owner = { tag = F78 }: custom_tooltip = '
                         'permanently_increases_our_artifice_points_by_5_tt']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.09, 'building_slot_add': 1},
             'character_modifier': {},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['allowed_num_of_manufactories: EU4 manufactories; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: if owner = { NOT = { tag = F29 } }: custom_tooltip = '
                         'mount_lazzaward_tt',
                         'on_upgraded: if owner = { NOT = { tag = F29 } }: set_country_flag = '
                         'mount_lazzaward_mage_reward_flag',
                         'on_upgraded: if owner = { NOT = { tag = F29 } }: set_country_flag = '
                         'mount_lazzaward_artificer_reward_flag',
                         'on_upgraded: if owner = { NOT = { tag = F29 } }; if NOT = { is_subject_of = F29 }: '
                         'overlord = { set_country_flag = mount_lazzaward_mage_reward_flag set_country_flag '
                         '= mount_lazzaward_artificer_reward_flag }',
                         'on_upgraded: if owner = { tag = F78 }: custom_tooltip = '
                         'permanently_increases_our_artifice_points_by_10_tt']}],
  'art': 'gfx/interface/great_projects/great_project_mount_lazzaward.dds',
  'notes': ['gate atom tag:F29 ignored (no CK3 equivalent)',
            'gate atom flag:zokka_lazzaward_flag ignored (no CK3 equivalent)',
            'gate atom flag:hyti_love_lahmas ignored (no CK3 equivalent)',
            'gate atom tag:F78 ignored (no CK3 equivalent)',
            'gate atom flag:allow_lazzaward_usage ignored (no CK3 equivalent)',
            'gate atom culture:zanlibi ignored (no CK3 equivalent)']},
 {'eu4_key': 'ovdal_tungr_port_hold',
  'source': 'dwarven',
  'name': 'Port-Hold of Ovdal Tûngr',
  'desc': 'The Copper Dwarves of Ovdal Tûngr stand out amongst all the dwarves of Halann - not just those '
          'within the Serpentspine - as being unusually adept and capable at sea. While most dwarves have a '
          'great dislike and even fear of large bodies of open water, the Copper Dwarves prove that this '
          'fear is hardly something that is genetic to the Dwarven race, and are some of the best sailors in '
          'all of both Bulwar and Cannor.',
  'levels': ['aov_monument_ovdal_tungr_port_hold_01',
             'aov_monument_ovdal_tungr_port_hold_02',
             'aov_monument_ovdal_tungr_port_hold_03'],
  'barony': 'b_irovar',
  'province': 526,
  'start_level': 1,
  'category': 'port',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_dwarven } culture = { has_cultural_pillar = '
          'heritage_kobold } }',
  'gate_desc': 'Dwarven, Kobold',
  'tiers': [{'province_modifier': {'fort_level': 1},
             'county_modifier': {'levy_reinforcement_rate': 0.0625, 'levy_size': 0.0625},
             'character_modifier': {},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['navy_tradition_decay: EU4 ship design/flagships; CK3 has no navies']},
            {'province_modifier': {'fort_level': 1},
             'county_modifier': {'levy_reinforcement_rate': 0.125, 'levy_size': 0.125},
             'character_modifier': {},
             'on_complete': 'barony.holder = { save_scope_as = aov_monument_patron create_character = { '
                            'employer = scope:aov_monument_patron culture = '
                            'scope:aov_monument_patron.culture faith = scope:aov_monument_patron.faith age = '
                            '{ 30 50 } gender_female_chance = 50 dynasty = none trait = education_martial_3 '
                            'martial = { 14 18 } random_traits = yes } }',
             'cost': 1400,
             'days': 3600,
             'dropped': ['ship_durability: EU4 ship design/flagships; CK3 has no navies',
                         'flagship_durability: EU4 ship design/flagships; CK3 has no navies',
                         'navy_tradition_decay: EU4 ship design/flagships; CK3 has no navies']},
            {'province_modifier': {'fort_level': 2, 'defender_holding_advantage': 4},
             'county_modifier': {'levy_reinforcement_rate': 0.25, 'levy_size': 0.25},
             'character_modifier': {},
             'on_complete': '',
             'cost': 2800,
             'days': 7200,
             'dropped': ['ship_durability: EU4 ship design/flagships; CK3 has no navies',
                         'flagship_durability: EU4 ship design/flagships; CK3 has no navies',
                         'navy_tradition_decay: EU4 ship design/flagships; CK3 has no navies',
                         'on_upgraded: add_country_modifier = { name = ovdal_tungr_port_hold_ship_durability '
                         'duration = 5475 }']}],
  'art': 'gfx/interface/great_projects/great_project_ovdal_tungr_port_hold.dds',
  'notes': ['gate requirement dwarven_monuments_has_dig_level_2_or_higher dropped (hold dig level: no CK3 '
            'equivalent until hold digging exists)',
            'gate atom culture_group:goblin ignored (no CK3 equivalent)',
            'gate atom culture_group:orcish ignored (no CK3 equivalent)',
            'gate atom culture:mossmouth_ogre ignored (no CK3 equivalent)']},
 {'eu4_key': 'quartz_cothon',
  'source': 'anbennar',
  'name': 'Quartz Cothon',
  'desc': 'The coast of the Far Salahad along the Gulf of Rahen is a desolate and forbidding landscape. Sand '
          'dunes and stony arid plains stretch from the shore to the horizon. But hidden among this barren '
          "coastline is a true marvel. A day's travel east from the coastal town of Daqalm, the barren "
          'cliffs along the coast are separated by a broad channel, hidden from view by strategically placed '
          'rock outcroppings until a ship is almost right upon it. A vessel entering this channel will soon '
          'arrive at a perfectly circular gargantuan harbor, capable of hosting an entire fleet. This is the '
          'fabled Quartz Cothon. Its wharves, buildings and walkways are fashioned not from the local '
          'sandstone but from blindingly white marble, inlaid with massive veins of quartz. These quartz '
          'veins form perfectly geometrical patterns and lend the cothon its name. Opposite the channel '
          'entrance, a white marble tower, almost delicate despite its size, stretches towards the sky and '
          'overlooks the harbor. All along the harbor front, basins are carved into the marble, easily '
          'adaptable as drydocks. And surrounding the cothon on all sides are buildings with an austere '
          'beauty supported by towering marble columns. Despite their finely wrought construction, these '
          'buildings appear to be intended as shipyards and storehouses for raw materials and trade goods '
          'alike. Who created this marvel - Djinn, God-king or other entity - has been lost to the mists of '
          'time, and the cothon itself has been discovered and then abandoned during times of conflict '
          'multiple times over the millennia. Yet whenever it has been freed from the shifting sand dunes '
          'that tend to bury it when left unattended, it is undeniably the finest harbor in the westernmost '
          'Gulf of Rahen.',
  'levels': ['aov_monument_quartz_cothon_01',
             'aov_monument_quartz_cothon_02',
             'aov_monument_quartz_cothon_03'],
  'barony': 'b_daqalm',
  'province': 2925,
  'start_level': 0,
  'category': 'port',
  'gate': '',
  'gate_desc': '',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'levy_reinforcement_rate': 0.025},
             'character_modifier': {'embarkation_cost_mult': -0.15, 'monthly_income_mult': 0.025},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: if NOT = { province_has_center_of_trade_of_level = 1 }: '
                         'center_of_trade = 1']},
            {'province_modifier': {'build_speed': -0.125},
             'county_modifier': {'levy_reinforcement_rate': 0.0625},
             'character_modifier': {'embarkation_cost_mult': -0.25, 'monthly_income_mult': 0.0375},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['trade_steering: EU4 trade nodes/merchants/colonies; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {'build_speed': -0.25},
             'county_modifier': {'levy_reinforcement_rate': 0.125},
             'character_modifier': {'embarkation_cost_mult': -0.35, 'monthly_income_mult': 0.05},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['trade_steering: EU4 trade nodes/merchants/colonies; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: add_building = grand_shipyard',
                         'on_upgraded: if religion_group = bulwari: define_admiral = { shock = 3 fire = 2 '
                         'manuever = 4 siege = 2 name = "Kryt Sunspear" female = yes }',
                         'on_upgraded: else: define_admiral = { shock = 3 fire = 2 manuever = 4 siege = 2 '
                         'name = "Kryt Skullchomper" female = yes }']}],
  'art': None,
  'notes': []},
 {'eu4_key': 'queens_throne',
  'source': 'anbennar',
  'name': "The Queen's Throne",
  'desc': "Nestled deep within the Harpy Hills lies the seat of imperial Harpy power, the Queen's Throne. A "
          'colossal city built atop one of the many mountains in this region, the roost boasts four primary '
          'layers, with access between in the form of large staircases and ramps. The first; a level '
          'populated by non-Harpy subjects. Here humans, goblins and other vassal races reside and work, and '
          'it is also the primary trading hub of the roost. The second; harpy residences. This predominantly '
          'consists of housing unwalled to the open air, allowing for easy access from the skies, with wide '
          'platforms providing ease of use for both harpies and their mates. The third; the military '
          'district. In this district one finds innumerable barracks and training grounds, the officer '
          'schools, and the garrison that cast their watchful eyes across the surrounding hills. From the '
          'skies, they can monitor for miles in every direction for threat, harassing enemy movements with '
          "easy retreat in the case of danger. The fourth and final level; the Queen's Palace and the "
          'administration. It is from here that the Queendom is run; representatives of both the flocks and '
          'the non-harpies meet and petition the Queen in these halls. This level also serves as the housing '
          "of the Matriarch and their family. All of the Queen's children born here have the chance of one "
          "day rising to the very top of the Queendom, should they be lucky enough to gain the Matriarch's "
          'favor.',
  'levels': ['aov_monument_queens_throne_01',
             'aov_monument_queens_throne_02',
             'aov_monument_queens_throne_03'],
  'barony': 'b_heunthume',
  'province': 660,
  'start_level': 0,
  'category': 'palace',
  'gate': 'culture = { has_cultural_pillar = heritage_harpy }',
  'gate_desc': 'Harpy',
  'tiers': [{'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.3},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = harpy_roost_1_more_monument_tt',
                         'on_upgraded: if NOT = { has_country_flag = '
                         'harpy_roost_queens_throne_has_tier_1_free_roost }: set_country_flag = '
                         'harpy_roost_queens_throne_has_tier_1_free_roost',
                         'on_upgraded: if NOT = { has_country_flag = '
                         'harpy_roost_queens_throne_has_tier_1_free_roost }: '
                         'harpy_roost_se_allow_construction_of_extra_roost = yes']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.6},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['development_cost_in_primary_culture: EU4 development cost by culture; CK3 '
                         'development growth is a county modifier',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = harpy_roost_2_more_monument_tt',
                         'on_upgraded: if NOT = { has_country_flag = '
                         'harpy_roost_queens_throne_has_tier_2_free_roost }: set_country_flag = '
                         'harpy_roost_queens_throne_has_tier_2_free_roost',
                         'on_upgraded: if NOT = { has_country_flag = '
                         'harpy_roost_queens_throne_has_tier_2_free_roost }: '
                         'harpy_roost_se_allow_construction_of_extra_roost = yes']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.9},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['development_cost_in_primary_culture: EU4 development cost by culture; CK3 '
                         'development growth is a county modifier',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = harpy_roost_3_more_monument_tt',
                         'on_upgraded: if NOT = { has_country_flag = '
                         'harpy_roost_queens_throne_has_tier_3_free_roost }: set_country_flag = '
                         'harpy_roost_queens_throne_has_tier_3_free_roost',
                         'on_upgraded: if NOT = { has_country_flag = '
                         'harpy_roost_queens_throne_has_tier_3_free_roost }: '
                         'harpy_roost_se_allow_construction_of_extra_roost = yes',
                         'on_upgraded: every_known_country = { limit = { culture_group = harpy } '
                         'reverse_add_casus_belli = { target = PREV type = cb_vassalize_mission months = 600 '
                         '} }']}],
  'art': 'gfx/interface/great_projects/great_project_queens_throne.dds',
  'notes': []},
 {'eu4_key': 'suhuskar',
  'source': 'anbennar',
  'name': 'Suhuškar',
  'desc': 'The Djinn Palace of Suhuškar is located west of the city of Nebar in the hilly countryside on the '
          'southern banks of the Suran river. Half-buried within the shale hills, the accessible areas still '
          'stand tall and seemingly untouched by the passage of time, a testament to the skill of its genie '
          'architects. Many theories abound regarding this monumental reminder of the very origins of '
          'Bulwari history. Some scholars even consider it the last remnant of the Djinn palace city of '
          'Ilu-Abbašlam, the capital of the Šedu Sultanates, left on the material plane. Within the upper '
          'levels of the palace, the Sultan of Suhuškar, leader of the Kigkasil brotherhood of adventurers '
          'and by tradition always a Mirzizig air planetouched, holds court. Here, the brothers - and '
          'sisters - of the brotherhood make use of the training facilities to hone their skills, recuperate '
          'from arduous quests and revel in the raucous company of their fellow brethren. But only a small '
          'fraction of the sprawling palace has been claimed by mortal occupants. Beneath the surface level, '
          'deep within the rocky soil, the palace stretches on for uncounted miles and levels. And within '
          'this vast ruined dungeon, many an enterprising Kigkasil has made their fortune by uncovering a '
          'genie relic, or has found their untimely end.',
  'levels': ['aov_monument_suhuskar_01', 'aov_monument_suhuskar_02', 'aov_monument_suhuskar_03'],
  'barony': 'b_traz_suran',
  'province': 612,
  'start_level': 0,
  'category': 'palace',
  'gate': '',
  'gate_desc': '',
  'tiers': [{'province_modifier': {'garrison_size': 0.1},
             'county_modifier': {},
             'character_modifier': {'knight_effectiveness_mult': 0.05, 'mercenary_hire_cost_mult': -0.05},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = suhuskar_tooltip_1']},
            {'province_modifier': {'garrison_size': 0.2},
             'county_modifier': {},
             'character_modifier': {'knight_effectiveness_mult': 0.1, 'mercenary_hire_cost_mult': -0.075},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = suhuskar_tooltip_2']},
            {'province_modifier': {'garrison_size': 0.2},
             'county_modifier': {},
             'character_modifier': {'knight_effectiveness_mult': 0.15, 'mercenary_hire_cost_mult': -0.1},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = suhuskar_tooltip_2',
                         'on_upgraded: custom_tooltip = suhuskar_tooltip_3']}],
  'art': None,
  'notes': []}]

EXCLUDED = {'heros_gate': "dungeon: spawned by EU4's hold-digging events; belongs to the Dwarven Hold Digging system",
 'jorkad_dam': "dungeon: spawned by EU4's hold-digging events; belongs to the Dwarven Hold Digging system",
 'queens_throne_skewered_drake': "dungeon: spawned by EU4's hold-digging events; belongs to the Dwarven Hold "
                                 'Digging system'}
