# generated by tools/import_eu4_monuments.py; edit salahad_hand.py, not this file

MONUMENTS = [{'eu4_key': 'aur_kes_akasik',
  'source': 'anbennar',
  'name': 'Aur-Kes-Akasik',
  'desc': 'Carved into the face of the mighty Akasi mountains is an ancient palace from a bygone era. It was '
          'one of many palaces created and held by the giants, until the mighty Storm Queens overthrew them '
          'with the help of the Fangaulan king Aro. After expelling the giants from Akasik, the Storm Queens '
          'reshaped the once unassuming palace into the greatest in North Sarhal; the mountains themselves '
          'were molded to form new chambers of the palace and grant it the eternal embrace of the mother. '
          'The Storm Queens brought forth many fresh springs from the earth to create wondrous gardens and '
          'an ever-running hydraulic system, and set in place powerful enchantments that still stir spring '
          'breezes through the many open spaces of the palace. While before the splintering of Akasik the '
          'palace was the primary court of many kings and queens, in recent times it has served as a '
          'pilgrimage site for the faithful and the planetouched of Akasik, bringing a semblance of '
          'centralization to an otherwise splintered faith.',
  'levels': ['aov_monument_aur_kes_akasik_01',
             'aov_monument_aur_kes_akasik_02',
             'aov_monument_aur_kes_akasik_03'],
  'barony': 'b_desh_al_deshak',
  'province': 383,
  'start_level': 0,
  'category': 'palace',
  'gate': '',
  'gate_desc': '',
  'tiers': [{'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_piety': 0.5, 'different_faith_county_opinion_mult': -0.15},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_piety': 1, 'different_faith_county_opinion_mult': -0.15},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: change_trade_goods = paper']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_piety': 1, 'different_faith_county_opinion_mult': -0.2},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = aur_kes_akasik_tip1']}],
  'art': None,
  'notes': []},
 {'eu4_key': 'bronze_dragon_academy',
  'source': 'anbennar',
  'name': 'Bronze Dragon Academy',
  'desc': 'During the reign of Aakhet the Bronze, no group was more loyal to the dragon than the Ahati. '
          'Their reverence for him went beyond his status as the ruler of Kheterata, attempting to harness '
          'the power of a dragon within themselves to increase their fighting power. Although it has been '
          'some time since his disappearance, this martial academy has been constructed to give the Ahati '
          'renewed purpose; a place for them to hone their skills as they did in centuries past.',
  'levels': ['aov_monument_bronze_dragon_academy_01',
             'aov_monument_bronze_dragon_academy_02',
             'aov_monument_bronze_dragon_academy_03'],
  'barony': 'b_aakheta',
  'province': 466,
  'start_level': 0,
  'category': 'academy',
  'gate': '',
  'gate_desc': '',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'levy_size': 0.05},
             'character_modifier': {'siege_phase_time': -0.1},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {'levy_size': 0.075},
             'character_modifier': {'siege_phase_time': -0.1, 'vassal_opinion': 1.25},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {'levy_size': 0.1},
             'character_modifier': {'siege_phase_time': -0.15, 'vassal_opinion': 2.5},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = bronze_dragon_academy_tooltip',
                         'on_upgraded: add_country_modifier = { name = bronze_dragon_academy_modifier '
                         'duration = -1 hidden = yes }']}],
  'art': None,
  'notes': []},
 {'eu4_key': 'deshak_temple_of_the_elements',
  'source': 'cannorian',
  'name': 'Temple of the Elements',
  'desc': 'Established by an unknown ancient civilization long before Deshak was founded, the Temple of the '
          'Elements is claimed to have been built on the site where the Planetouched first came to '
          'existence. It continues to stand as one of the most prominent houses of worship in Akan.',
  'levels': ['aov_monument_deshak_temple_of_the_elements_01',
             'aov_monument_deshak_temple_of_the_elements_02',
             'aov_monument_deshak_temple_of_the_elements_03'],
  'barony': 'b_deshak',
  'province': 382,
  'start_level': 1,
  'category': 'temple',
  'gate': 'OR = { faith.religion = religion:khetism_religion faith = faith:mother_akasik culture = { '
          'has_cultural_pillar = heritage_kheteratan } culture = { has_cultural_pillar = heritage_akasi } '
          'culture = { has_cultural_pillar = heritage_gnollish } culture = culture:delta_gnomish culture = '
          'culture:sun_elvish culture = culture:castanorian }',
  'gate_desc': 'Khetism, Mother Akasik, Kheteratan, Akasi, Gnollish, Delta Gnomish, Sun Elvish, Castanorian',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'tax_mult': 0.05},
             'character_modifier': {'faith_conversion_piety_cost_mult': -0.05},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': []},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.075},
             'character_modifier': {'faith_conversion_piety_cost_mult': -0.2, 'monthly_piety': 0.5},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': ['on_upgraded: add_permanent_province_modifier = { name = religious_center duration '
                         '= -1 }']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.125},
             'character_modifier': {'faith_conversion_piety_cost_mult': -0.25, 'monthly_piety': 1},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': []}],
  'art': 'gfx/interface/great_projects/great_project_deshak_temple_of_the_elements.dds',
  'notes': []},
 {'eu4_key': 'ekha_harbor',
  'source': 'cannorian',
  'name': 'Ekha Harbor',
  'desc': 'The Ekhan people have always lived and died with their existences focused on the sea, and the '
          'great Ekhan Harbor exemplifies this. Ekhan sailors and ships have always proven themselves to be '
          'quite strong indeed.',
  'levels': ['aov_monument_ekha_harbor_01', 'aov_monument_ekha_harbor_02', 'aov_monument_ekha_harbor_03'],
  'barony': 'b_ekha',
  'province': 402,
  'start_level': 1,
  'category': 'port',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_kheteratan } culture = { has_cultural_pillar = '
          'heritage_akasi } culture = { has_cultural_pillar = heritage_gnollish } culture = '
          'culture:delta_gnomish culture = culture:sun_elvish culture = culture:castanorian }',
  'gate_desc': 'Kheteratan, Akasi, Gnollish, Delta Gnomish, Sun Elvish, Castanorian',
  'tiers': [{'province_modifier': {'build_speed': -0.05},
             'county_modifier': {'levy_size': 0.0625},
             'character_modifier': {},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': []},
            {'province_modifier': {'build_speed': -0.1},
             'county_modifier': {'levy_size': 0.125},
             'character_modifier': {'naval_movement_speed_mult': 0.075},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': []},
            {'province_modifier': {'build_speed': -0.165, 'building_slot_add': 1},
             'county_modifier': {'levy_size': 0.25},
             'character_modifier': {'naval_movement_speed_mult': 0.15},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': []}],
  'art': 'gfx/interface/great_projects/great_project_ekha_harbor.dds',
  'notes': []},
 {'eu4_key': 'elikhet_pyramid',
  'source': 'anbennar',
  'name': 'Great Pyramid of Elikhet',
  'desc': 'The Tomb of Elikhet, being the resting place of the most powerful and famous Khet known, is one '
          'of the holiest sites in Khetism beyond the Sorrow itself. Atop this tomb a great pyramid has been '
          'constructed, acting both as a layer of protection for the tomb itself, as well as a projection of '
          "Elikhet's awe inspiring might. It stands as both a reminder of the will of the Khet as well as a "
          'monument to their glory.',
  'levels': ['aov_monument_elikhet_pyramid_01',
             'aov_monument_elikhet_pyramid_02',
             'aov_monument_elikhet_pyramid_03'],
  'barony': 'b_kheterat',
  'province': 475,
  'start_level': 0,
  'category': 'tomb',
  'gate': 'OR = { faith.religion = religion:khetism_religion faith = faith:elikhetist }',
  'gate_desc': 'Khetism, Elikhetist',
  'tiers': [{'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.1},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.3, 'faith_conversion_piety_cost_mult': -0.05},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {},
             'character_modifier': {'monthly_prestige': 0.5, 'faith_conversion_piety_cost_mult': -0.1},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = elikhet_pyramid_tooltip']}],
  'art': None,
  'notes': []},
 {'eu4_key': 'koroshesh_grain_port',
  'source': 'cannorian',
  'name': 'Grain Port of Koroshesh',
  'desc': "The Port of Koroshesh is the main location for all exports from the Mother's Sorrow Estuary, and "
          'the main location where Kheteratan grain is shipped to Cannor. Regardless of what happens to the '
          'North Salahad, the grain must flow.',
  'levels': ['aov_monument_koroshesh_grain_port_01',
             'aov_monument_koroshesh_grain_port_02',
             'aov_monument_koroshesh_grain_port_03'],
  'barony': 'b_kaashesh',
  'province': 503,
  'start_level': 0,
  'category': 'port',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_kheteratan } culture = { has_cultural_pillar = '
          'heritage_akasi } culture = { has_cultural_pillar = heritage_gnollish } culture = '
          'culture:delta_gnomish culture = culture:sun_elvish culture = culture:castanorian }',
  'gate_desc': 'Kheteratan, Akasi, Gnollish, Delta Gnomish, Sun Elvish, Castanorian',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'tax_mult': 0.055, 'development_growth_factor': 0.1},
             'character_modifier': {'embarkation_cost_mult': -0.1},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['transport_hull_size_modifier: EU4 ship design/flagships; CK3 has no navies']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.11, 'development_growth_factor': 0.2},
             'character_modifier': {'embarkation_cost_mult': -0.2},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': ['transport_hull_size_modifier: EU4 ship design/flagships; CK3 has no navies',
                         'disengagement_chance: EU4 ship design/flagships; CK3 has no navies']},
            {'province_modifier': {'building_slot_add': 1},
             'county_modifier': {'tax_mult': 0.199, 'development_growth_factor': 0.3},
             'character_modifier': {'embarkation_cost_mult': -0.33},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': ['transport_hull_size_modifier: EU4 ship design/flagships; CK3 has no navies',
                         'disengagement_chance: EU4 ship design/flagships; CK3 has no navies',
                         'on_upgraded: add_permanent_province_modifier = { name = grain_production_improved '
                         'duration = -1 }']}],
  'art': 'gfx/interface/great_projects/great_project_koroshesh_grain_port.dds',
  'notes': ['Placement: Koroshesh (c_koroshesh) has one barony, taken by the Grand Library; the Grain Port '
            'is in b_kaashesh, a coastal county of the same duchy (d_sopotremit) and EU4 area.']},
 {'eu4_key': 'koroshesh_library',
  'source': 'anbennar',
  'name': 'Grand Library of Koroshesh',
  'desc': "The Great Library of Koroshesh, built during the early years of Elikhet's reign, is one of, if "
          'not the greatest, centers of knowledge and learning in Halann. The library itself is just the '
          'heart of a massive complex that stands towering above the city harbor. It is formed by the many '
          'institutions that have congregated around it through the ages, including a great zoo and '
          'countless lecture halls, student residences and art expositions. Its seemingly infinite shelves '
          'contain the wisdom of five millennia, and it would take another five to read just the titles of '
          'all the works it houses. No field of knowledge lacks a place in the Library, and any contribution '
          'of the slightest significance soon finds its way to its shelves. The Library has produced some of '
          'the brightest minds of all history, and it is expected that it will continue to do so for '
          'centuries to come.',
  'levels': ['aov_monument_koroshesh_library_01',
             'aov_monument_koroshesh_library_02',
             'aov_monument_koroshesh_library_03'],
  'barony': 'b_koroshesh',
  'province': 463,
  'start_level': 1,
  'category': 'library',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_kheteratan } culture = { has_cultural_pillar = '
          'heritage_gnollish } culture = culture:delta_gnomish }',
  'gate_desc': 'Kheteratan, Gnollish, Delta Gnomish',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'development_growth_factor': 0.02},
             'character_modifier': {'monthly_lifestyle_xp_gain_mult': 0.025},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {'development_growth_factor': 0.04},
             'character_modifier': {'monthly_lifestyle_xp_gain_mult': 0.05},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: change_innovativeness = 5',
                         'on_upgraded: if is_or_was_tag = { tag = F60 } mission_completed = '
                         'F60_the_great_library: increase_magic_experience = { unmodified_amount = 100 }']},
            {'province_modifier': {},
             'county_modifier': {'development_growth_factor': 0.1},
             'character_modifier': {'monthly_lifestyle_xp_gain_mult': 0.1},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['candidate_random_bonus: EU4 republican elections; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: change_innovativeness = 10',
                         'on_upgraded: if is_or_was_tag = { tag = F60 } mission_completed = '
                         'F60_the_great_library: increase_magic_experience = { unmodified_amount = 100 }']}],
  'art': None,
  'notes': ['gate atom tag:F29 ignored (no CK3 equivalent)',
            'gate atom flag:zokka_library_flag ignored (no CK3 equivalent)']},
 {'eu4_key': 'krahgradir',
  'source': 'anbennar',
  'name': 'Krahgradir',
  'desc': 'Few gnolls are as famous - or infamous, depending on whom you ask - as Krah. Renowned for his '
          "success as a slaver, his name became synonymous with the very word 'slaver' in the gnollish "
          'tongue. Countless legends surround him, from tales of his secret treasure hoard hidden in the '
          'jungles of Horashesh to his profound influence on gnollish culture and tradition, rivaled only by '
          'that of the Xhazobines. Yet it is not only legends and traditions that endure. In the open fields '
          'of the Gol Savanna stands the Krahilzin - meaning "Slaver\'s Camp" - the place where Krah is said '
          'to have originated, where he rose to prominence, where he returned after every successful raid, '
          'and, most importantly, where the bulk of his slave trades and deals were conducted. But the '
          "camp's true marvel lies at its heart: the Krahgradir, a jagged tower rising above mounds of "
          'plundered and blood-traded wealth - ancient coins, precious metals, piles of gold and gemstones '
          "glittering like a dragon's hoard. To this day, both camp and tower stand inviolate. Not even the "
          'most savage or demonic of gnollish warlords dare raid or desecrate it, for seizing Krahgradir is '
          "to claim more than riches - it is to grasp at Krah's shadow. Every self-respecting Gnollish "
          'warlord dreams of matching even half his mastery over others. And for them, to amass enough '
          "wealth to contribute to the tower's riches, immortalizing one's name alongside Krah's, is the "
          'ultimate aspiration.',
  'levels': ['aov_monument_krahgradir_01', 'aov_monument_krahgradir_02', 'aov_monument_krahgradir_03'],
  'barony': 'b_krahilzin',
  'province': 4701,
  'start_level': 1,
  'category': 'monument',
  'gate': 'culture = { has_cultural_pillar = heritage_gnollish }',
  'gate_desc': 'Gnollish',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'tax_mult': 0.045, 'supply_limit_mult': 0.05},
             'character_modifier': {'vassal_opinion': 5},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.09, 'supply_limit_mult': 0.1},
             'character_modifier': {'vassal_opinion': 10},
             'on_complete': '',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = krahgradir_slave_bonus_1_tooltip',
                         'on_upgraded: every_owned_province = { limit = { trade_goods = slaves } '
                         'add_province_modifier = { name = krahgradir_slave_bonus_1 duration = -1 hidden = '
                         'yes } }',
                         'on_upgraded: center_of_trade = 1']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.15, 'supply_limit_mult': 0.2},
             'character_modifier': {'vassal_opinion': 12.5},
             'on_complete': '',
             'cost': 2000,
             'days': 1800,
             'dropped': ['monarch_power_tribute: EU4 tributaries; no CK3 equivalent',
                         'on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = krahgradir_slave_bonus_2_tooltip',
                         'on_upgraded: every_owned_province = { limit = { has_province_modifier = '
                         'krahgradir_slave_bonus_1 } remove_province_modifier = krahgradir_slave_bonus_1 '
                         'add_province_modifier = { name = krahgradir_slave_bonus_2 duration = -1 hidden = '
                         'yes } }']}],
  'art': None,
  'notes': []},
 {'eu4_key': 'water_dreams_oasis',
  'source': 'anbennar',
  'name': 'Oasis of Water Dreams',
  'desc': 'Deep within the western reaches of the Salahad rises a jagged sandstone plateau riven by a '
          'network of narrow ravines. At its heart, hidden behind a labyrinth of sandstone canyons, lies the '
          'blue marvel of the desert, the Oasis of Water Dreams: a network of clear spring pools whose water '
          'nourishes a verdant paradise in this otherwise inhospitable land. Shielded from the glare of the '
          'desert sun by the surrounding steep cliffs, it has since time immemorial been a refuge and place '
          'of rest for all who traverse these parts of the Salahad. Called Jisugo Loban by the Mukarron '
          'tribe native to these lands, and Gortarkhitanda by their gnollish overlords, the Oasis of Water '
          'Dreams is not only a vital resupply stop for all who wish to traverse the unforgiving desert, but '
          'also the home of an ancient temple complex that is sacred to all, be they Fangaulan, Akasi or '
          'Gnoll. Hewn into the cliff faces surrounding the oasis are easily defendable access points to the '
          'subterranean network of temples and sanctuaries carved into the sandstone over the past '
          'millennia. The flowers blooming on the shore of the oasis ponds provide the pollen used by a '
          'hardy species of desert bee to produce a unique hallucinogenic honey, a treasured ritual '
          'substance for religious ceremonies held in the oasis temple and beyond. Guarding this unique '
          'sanctuary since before the rise of the second Fangaulan Empire are the Bermine Basugo, the Guides '
          'of the Dream, an order of planetouched sworn to defend the sanctity of the temples of Jisugo '
          'Loban and all who seek shelter there.',
  'levels': ['aov_monument_water_dreams_oasis_01',
             'aov_monument_water_dreams_oasis_02',
             'aov_monument_water_dreams_oasis_03'],
  'barony': 'b_rostgrax',
  'province': 6098,
  'start_level': 1,
  'category': 'temple',
  'gate': 'OR = { faith = faith:mother_akasik culture = { has_cultural_pillar = heritage_fangaulan } culture '
          '= { has_cultural_pillar = heritage_akasi } culture = { has_cultural_pillar = heritage_gnollish } '
          '}',
  'gate_desc': 'Mother Akasik, Fangaulan, Akasi, Gnollish',
  'tiers': [{'province_modifier': {'hostile_raid_time': 0.5},
             'county_modifier': {'supply_limit_mult': 0.125},
             'character_modifier': {'monthly_piety': 0.5, 'monthly_income_mult': 0.02},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = water_dreams_oasis_tier_1_tt']},
            {'province_modifier': {},
             'county_modifier': {'supply_limit_mult': 0.125, 'hostile_raid_time': 0.5},
             'character_modifier': {'monthly_piety': 0.5, 'monthly_income_mult': 0.04},
             'on_complete': 'barony.holder = { save_scope_as = aov_monument_patron create_character = { '
                            'employer = scope:aov_monument_patron culture = '
                            'scope:aov_monument_patron.culture faith = scope:aov_monument_patron.faith age = '
                            '{ 30 50 } gender_female_chance = 50 dynasty = none trait = education_martial_3 '
                            'martial = { 14 18 } random_traits = yes } }',
             'cost': 1000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: custom_tooltip = water_dreams_oasis_tier_2_tt',
                         'on_upgraded: if has_estate_privilege = oasis_of_water_dreams_privilege: '
                         'every_owned_province = { limit = { has_province_modifier = '
                         'oasis_of_water_dreams_fmk_mod1 } remove_province_modifier = '
                         'oasis_of_water_dreams_fmk_mod1 add_province_modifier = { name = '
                         'oasis_of_water_dreams_fmk_mod2 duration = -1 } }']},
            {'province_modifier': {},
             'county_modifier': {'tax_mult': 0.3, 'supply_limit_mult': 0.125, 'hostile_raid_time': 0.5},
             'character_modifier': {'monthly_piety': 1, 'monthly_income_mult': 0.04},
             'on_complete': 'barony.holder = { save_scope_as = aov_monument_patron create_character = { '
                            'employer = scope:aov_monument_patron culture = '
                            'scope:aov_monument_patron.culture faith = scope:aov_monument_patron.faith age = '
                            '{ 30 50 } gender_female_chance = 50 dynasty = none trait = education_martial_3 '
                            'martial = { 14 18 } random_traits = yes } }',
             'cost': 2000,
             'days': 1800,
             'dropped': ['on_upgraded: on_sarhal_monument_upgraded = yes',
                         'on_upgraded: change_trade_goods = incense',
                         'on_upgraded: custom_tooltip = water_dreams_oasis_tier_3_tt',
                         'on_upgraded: if has_estate_privilege = oasis_of_water_dreams_privilege: '
                         'every_owned_province = { limit = { has_province_modifier = '
                         'oasis_of_water_dreams_fmk_mod2 } remove_province_modifier = '
                         'oasis_of_water_dreams_fmk_mod2 add_province_modifier = { name = '
                         'oasis_of_water_dreams_fmk_mod3 duration = -1 } }']}],
  'art': None,
  'notes': ['gate atom religion:fangaulan_pantheon ignored (no CK3 equivalent)',
            'gate atom religion:kvangahga ignored (no CK3 equivalent)',
            'gate atom culture:dunesole_ogre ignored (no CK3 equivalent)',
            'Balance cap: county tax_mult reduced from 0.5 to 0.3 and hostile_raid_time from 0.75 to 0.5 '
            '(Theodosian Walls) at level 3.']},
 {'eu4_key': 'zornartakel_naval_harbor',
  'source': 'cannorian',
  'name': 'Zornartakel Naval Shipyard',
  'desc': "The Zornartakel Naval Harbor at Baqtkhet's Retreat is an extensive military harbor designed to be "
          'a complete installation for the construction of ships, the training of sailors, and the harboring '
          'of freight. The position of the Naval Harbor on the southern side of the island of Elzina allows '
          'for natural protection against sudden storms in the Sea of Eliz, or from enemy fleets.',
  'levels': ['aov_monument_zornartakel_naval_harbor_01',
             'aov_monument_zornartakel_naval_harbor_02',
             'aov_monument_zornartakel_naval_harbor_03'],
  'barony': 'b_rosutaaru',
  'province': 494,
  'start_level': 0,
  'category': 'port',
  'gate': 'OR = { culture = { has_cultural_pillar = heritage_kheteratan } culture = { has_cultural_pillar = '
          'heritage_akasi } culture = { has_cultural_pillar = heritage_gnollish } culture = '
          'culture:delta_gnomish culture = culture:sun_elvish culture = culture:castanorian }',
  'gate_desc': 'Kheteratan, Akasi, Gnollish, Delta Gnomish, Sun Elvish, Castanorian',
  'tiers': [{'province_modifier': {},
             'county_modifier': {'levy_reinforcement_rate': 0.0625, 'levy_size': 0.0625},
             'character_modifier': {'embarkation_cost_mult': -0.1},
             'on_complete': '',
             'cost': 400,
             'days': 1800,
             'dropped': ['allowed_marine_fraction: EU4 marines; no CK3 equivalent',
                         'on_upgraded: change_province_name = "Zornartakel"',
                         'on_upgraded: rename_capital = "Zornartakel"',
                         'on_upgraded: change_trade_goods = naval_supplies']},
            {'province_modifier': {},
             'county_modifier': {'levy_reinforcement_rate': 0.125, 'tax_mult': 0.05, 'levy_size': 0.125},
             'character_modifier': {'embarkation_cost_mult': -0.15},
             'on_complete': '',
             'cost': 1000,
             'days': 3600,
             'dropped': ['allowed_marine_fraction: EU4 marines; no CK3 equivalent']},
            {'province_modifier': {},
             'county_modifier': {'levy_reinforcement_rate': 0.25, 'tax_mult': 0.1, 'levy_size': 0.25},
             'character_modifier': {'embarkation_cost_mult': -0.25},
             'on_complete': '',
             'cost': 2000,
             'days': 7200,
             'dropped': ['allowed_marine_fraction: EU4 marines; no CK3 equivalent']}],
  'art': 'gfx/interface/great_projects/great_project_zornartakel_naval_harbor.dds',
  'notes': []}]

EXCLUDED = {'arskitse_evil_karassk': 'not on the CK3 map: no CK3 title matches its EU4 province',
 'aur_kes_akasik_S90': 'variant of aur_kes_akasik: an EU4 event turns that project into this one; built as '
                       'aur_kes_akasik',
 'esuvrem': 'not on the CK3 map: no CK3 title matches its EU4 province',
 'great_merfolk_canal': 'canal: no CK3 canal mechanic'}
