"""Generate the new Cannor monument buildings, province history and localization.

Source: tools/data/monuments/<region>.py (monument data) and translation.py (icons). Rerun after editing them:

    python -I tools/build_monuments.py --region cannor

Only building levels whose key Anbennar does not define are written here.
"""

import argparse
import importlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # python -I does not add the script's folder
from data.monuments import translation  # noqa: E402

SUBMOD = Path(__file__).resolve().parent.parent
ANBENNAR_CK3 = SUBMOD.parent / "anbennar-ck3-dev-master"
HEADER = "# Anbennar Overhaul: generated by tools/build_monuments.py from tools/data/monuments/; do not edit by hand.\n"
ROMAN = {1: "", 2: " (II)", 3: " (III)"}
BLOCKS = ("province_modifier", "county_modifier", "character_modifier")
DROPPED_NOTE = " Some effects of the original Europa Universalis IV project have no Crusader Kings III equivalent and are omitted."


NL = "\n"


class GeneratorError(Exception):
    pass


def anbennar_keys(root: Path = ANBENNAR_CK3) -> set:
    keys = set()
    for f in (Path(root) / "common" / "buildings").glob("*.txt"):
        keys.update(re.findall(r"^([A-Za-z0-9_]+)\s*=\s*\{", f.read_text(encoding="utf-8-sig"), re.M))
    return keys


def load_monuments(region: str) -> list:
    return importlib.import_module(f"data.monuments.{region}").MONUMENTS


def num(v) -> str:
    s = f"{float(v):.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("", "-0") else s


def building(m: dict, level: int, key: str, next_key) -> str:
    tier = m["tiers"][level - 1]
    out = [f"{key} = {{", f"\tconstruction_time = {tier['days']}", "",
           f'\ttype_icon = "{translation.ICONS[m["category"]]}"', "",
           "\tcan_construct_potential = {", "\t\tbuilding_requirement_tribal = no", "\t}", ""]
    if m["gate"]:
        tt = f"aov_monument_{m['eu4_key']}_gate"
        for name in ("can_construct", "is_enabled"):
            out += [f"\t{name} = {{", "\t\tscope:holder = {", f"\t\t\tcustom_tooltip = {{", f"\t\t\t\ttext = {tt}",
                    f"\t\t\t\t{m['gate']}", "\t\t\t}", "\t\t}", "\t}", ""]
    out += [f"\tcost_gold = {tier['cost']}", ""]
    for block in BLOCKS:
        mods = tier[block]
        if mods:
            out.append(f"\t{block} = {{")
            out += [f"\t\t{k} = {num(v)}" for k, v in mods.items()]
            out += ["\t}", ""]
    if tier["on_complete"].strip():
        out += ["\ton_complete = {", f"\t\t{tier['on_complete'].strip()}", "\t}", ""]
    if next_key:
        out += [f"\tnext_building = {next_key}", ""]
    out += ["\tai_value = {", "\t\tbase = 100", "\t}", "", "\ttype = special", "}", ""]
    return "\n".join(out)


def written_levels(monuments: list, known: set):
    """Yield (monument, level, key, next_key) for every level this generator writes."""
    for m in monuments:
        keys = m["levels"]
        for i, key in enumerate(keys):
            if key not in known:
                yield m, i + 1, key, (keys[i + 1] if i + 1 < len(keys) else None)


def buildings(monuments: list, known: set) -> str:
    return HEADER + "\n" + "\n".join(building(*a) for a in written_levels(monuments, known))


def history(monuments: list, known: set) -> str:
    out = [HEADER]
    for m in monuments:
        first = m["levels"][0]
        if first in known:
            continue
        lines = [f"{m['province']} = {{", "\t1000.1.1 = {", f"\t\tspecial_building_slot = {first}"]
        if m["start_level"] == 1:
            lines.append(f"\t\tspecial_building = {first}")
        lines += ["\t}", "}", ""]
        out.append(NL.join(lines))
    return NL.join(out)


def q(text: str) -> str:
    return text.replace('"', "'")


def loc(monuments: list, known: set) -> str:
    out = ["l_english:"]
    for m, level, key, _ in written_levels(monuments, known):
        name = m["name"] if m["levels"][0] == "castle_dameris_01" else m["name"] + ROMAN[level]
        desc = m["desc"] + (DROPPED_NOTE if m["tiers"][level - 1]["dropped"] else "")
        out.append(f' building_{key}: "{q(name)}"')
        out.append(f' building_{key}_desc: "{q(desc)}"')
    for m, level, key, _ in written_levels(monuments, known):  # tiger wants a type name for every level key
        out.append(f' building_type_{key}: "$building_{key}$"')
        out.append(f' building_type_{key}_desc: "$building_{key}_desc$"')
    for m in monuments:
        if m["gate"]:
            out.append(f' aov_monument_{m["eu4_key"]}_gate: "{q("Built and used by: " + m["gate_desc"])}"')
    return "\n".join(out) + "\n"


def render_all(region: str, root: Path = ANBENNAR_CK3) -> dict:
    monuments = load_monuments(region)
    known = anbennar_keys(root)
    return {
        f"common/buildings/aov_monuments_{region}.txt": buildings(monuments, known),
        f"history/provinces/aov_monuments_{region}.txt": history(monuments, known),
        f"localization/english/aov_monuments_{region}_l_english.yml": loc(monuments, known),
    }


def write_all(files: dict, root: Path) -> None:
    for rel, text in files.items():
        out = Path(root) / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\xef\xbb\xbf" + text.replace("\r\n", "\n").encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--region", default="cannor")
    args = parser.parse_args()
    try:
        files = render_all(args.region)
        write_all(files, SUBMOD)
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    print(f"wrote {len(files)} files")


if __name__ == "__main__":
    main()
