"""Regenerate gui/window_county_view.gui for Anbennar Overhaul.

The county view can only be changed by overriding the whole file, so the submod ships a copy with a second
holding-illustration background after the vanilla one: it draws the EU4 monument painting when the province
has a monument (custom loc AovMonumentIllustration, tools/build_monuments.py). The copy is taken from
Anbennar's gui/window_county_view.gui if Anbennar ships one, otherwise from the game. Rerun this after every
CK3 patch and Anbennar update:

    python -I tools/build_county_view_override.py [--anbennar PATH] [--game PATH]
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # python -I does not add the script's folder
from build_hud_override import GeneratorError, brace_delta  # noqa: E402

MARKER = "# Anbennar Overhaul"
REL_PATH = Path("gui/window_county_view.gui")
ANCHOR = "HoldingView.GetHolding.GetIllustration"
CUSTOM = "HoldingView.GetProvince.Custom('AovMonumentIllustration')"

SUBMOD = Path(__file__).resolve().parent.parent
DEFAULT_ANBENNAR = SUBMOD.parent / "anbennar-ck3-dev-master"
DEFAULT_GAME = Path("C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")

# Drawn over the holding illustration with the same mask; the custom loc is empty without a monument.
BLOCK = [
    f"{MARKER}: monument painting",
    "background = {",
    f"\tvisible = \"[Not( StringIsEmpty( {CUSTOM} ) )]\"",
    f"\ttexture = \"[{CUSTOM}]\"",
    "\talpha = 0.95",
    "",
    "\tfittype = centercrop",
    "",
    "\tmodify_texture = {",
    '\t\ttexture = "gfx/interface/window_county/mask_holding_illustration.dds"',
    "\t\tblend_mode = alphamultiply",
    "\t\talpha = 0.95",
    "\t}",
    "}",
]


def insert(text: str) -> str:
    if "AovMonumentIllustration" in text:
        raise GeneratorError("source already contains the monument illustration; is it a generated file?")
    lines = text.split("\n")
    try:
        anchor = next(i for i, l in enumerate(lines) if ANCHOR in l)
    except StopIteration:
        raise GeneratorError(f"anchor '{ANCHOR}' not found; did a CK3 or Anbennar update change the county view?")
    try:
        start = next(i for i in range(anchor, -1, -1) if lines[i].strip() == "background = {")
    except StopIteration:
        raise GeneratorError("no 'background = {' opens the holding illustration")
    depth = 0
    for end in range(start, len(lines)):
        depth += brace_delta(lines[end])
        if depth == 0:
            break
    else:
        raise GeneratorError("unbalanced braces in the holding illustration background")
    indent = lines[start][: len(lines[start]) - len(lines[start].lstrip("\t"))]
    lines[end + 1:end + 1] = [""] + [indent + l if l else "" for l in BLOCK]
    return "\n".join(lines)


def build(raw: bytes) -> bytes:
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    crlf = "\r\n" in text
    text = insert(text.replace("\r\n", "\n"))
    header = (
        f"{MARKER}: generated by tools/build_county_view_override.py from {REL_PATH.as_posix()}.\n"
        f"{MARKER}: do not edit by hand; edit the script and rerun it.\n"
    )
    text = header + text
    if crlf:
        text = text.replace("\n", "\r\n")
    return (b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8")


def find_source(anbennar: Path, game: Path) -> Path:
    for root in (anbennar, game):
        path = root / REL_PATH
        if path.is_file():
            return path
    raise GeneratorError(f"no {REL_PATH.as_posix()} in {anbennar} or {game}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--anbennar", type=Path, default=DEFAULT_ANBENNAR)
    parser.add_argument("--game", type=Path, default=DEFAULT_GAME)
    args = parser.parse_args()
    try:
        src = find_source(args.anbennar, args.game)
        data = build(src.read_bytes())
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    out = SUBMOD / REL_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    print(f"wrote {out} (from {src})")


if __name__ == "__main__":
    main()
