"""Generate the per-invention Artificery files from tools/data/inventions.py.

Every file written here repeats one block per invention, so it is generated rather than written by hand.
Rerun after editing tools/data/inventions.py:

    python -I tools/build_inventions.py [--eu4 PATH]

--eu4 is EU4 Anbennar's Workshop folder, used to copy the invention icons.
"""

import argparse
import importlib.util
import re
import shutil
import sys
from pathlib import Path

SUBMOD = Path(__file__).resolve().parent.parent
DATA = SUBMOD / "tools" / "data" / "inventions.py"
DEFAULT_EU4 = Path("C:/Program Files (x86)/Steam/steamapps/workshop/content/236850/1385440355")
EU4_ICONS = Path("gfx/interface/privileges")
ICON_DIR = "gfx/interface/icons/aov_inventions"
HEADER = "# Anbennar Overhaul: generated by tools/build_inventions.py from tools/data/inventions.py; do not edit by hand.\n"

CATEGORIES = ("economic", "military", "society")
ERAS = {1: "culture_era_early_medieval", 2: "culture_era_high_medieval", 3: "culture_era_late_medieval"}
MODIFIER_ICON = {"economic": "stewardship_positive", "military": "martial_positive", "society": "diplomacy_positive"}
FAITHS = {
    "faith = faith:ancestor_worship",
    "faith = { religion = religion:bulwari_sun_cults_religion }",
    "faith = { religion = religion:fey_religion }",
    "faith = faith:devouring_path",
    "faith = { religion = religion:cannorian_pantheon_religion }",
    "faith = faith:skaldhyrric_faith",
    "faith = { religion = religion:khetism_religion }",
    "faith = { religion = religion:xhazobkult_religion }",
}
MAA_KEYS = {"aov_prototype_tanks", "aov_war_golems", "aov_damestear_megacannon"}
OFFERS = 3


class GeneratorError(Exception):
    pass


def load_inventions(path: Path = DATA) -> list:
    spec = importlib.util.spec_from_file_location("aov_inventions_data", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.INVENTIONS


def validate(invs: list) -> None:
    keys = [i["key"] for i in invs]
    if len(set(keys)) != len(keys):
        raise GeneratorError("duplicate invention keys")
    for i in invs:
        k = i["key"]
        if not re.fullmatch(r"[a-z0-9_]+", k):
            raise GeneratorError(f"{k}: bad key")
        if i["category"] not in CATEGORIES:
            raise GeneratorError(f"{k}: bad category {i['category']}")
        if i["tier"] not in ERAS:
            raise GeneratorError(f"{k}: bad tier {i['tier']}")
        if i["faith"] is not None and i["faith"] not in FAITHS:
            raise GeneratorError(f"{k}: faith trigger not in allow-list: {i['faith']}")
        if i["maa"] is not None and i["maa"] not in MAA_KEYS:
            raise GeneratorError(f"{k}: unknown MaA {i['maa']}")
        if not re.fullmatch(r"Artf_\w+\.dds", i["icon"]):
            raise GeneratorError(f"{k}: bad icon {i['icon']}")
        if not i["modifier"].strip() or not i["name"] or not i["desc"]:
            raise GeneratorError(f"{k}: empty modifier, name or desc")
        if '"' in i["name"] + i["desc"]:
            raise GeneratorError(f"{k}: double quote in name or desc")


def of(invs, category=None, tier=None):
    return [i for i in invs if (category is None or i["category"] == category) and (tier is None or i["tier"] == tier)]


def any_of(name: str, comment: str, invs: list, cond) -> str:
    lines = "\n".join(f"\t\t{cond(i)}" for i in invs)
    return f"# {comment}\n{name} = {{\n\tOR = {{\n{lines}\n\t}}\n}}\n"


def chain(invs: list, limit, effect) -> str:
    parts = []
    for n, i in enumerate(invs):
        kw = "if" if n == 0 else "else_if"
        parts.append(f"\t{kw} = {{\n\t\tlimit = {{ {limit(i)} }}\n\t\t{effect(i)}\n\t}}")
    return "\n".join(parts)


def draw(invs: list, cond, effect, depth: int = 1) -> str:
    t = "\t" * depth
    opts = "\n".join(f"{t}\t1 = {{\n{t}\t\ttrigger = {{ {cond(i)} }}\n{t}\t\t{effect(i)}\n{t}\t}}" for i in invs)
    return f"{t}random_list = {{\n{opts}\n{t}}}"


def offered(i) -> str:
    c, k = i["category"], i["key"]
    return " ".join(
        f"AND = {{ has_variable = aov_tech_offer_{c}_{n} var:aov_tech_offer_{c}_{n} = flag:{k} }}" for n in range(1, OFFERS + 1)
    )


def modifiers(invs: list) -> str:
    out = [HEADER]
    for i in invs:
        body = "\n".join("\t" + line.strip() for line in i["modifier"].splitlines() if line.strip())
        out.append(f"aov_invention_{i['key']} = {{\n\ticon = {MODIFIER_ICON[i['category']]}\n{body}\n}}\n")
    return "\n".join(out)


def triggers(invs: list) -> str:
    out = [HEADER, "# All triggers are character scope (the ruler).\n"]
    for i in invs:
        k = i["key"]
        visible = [i["faith"]] if i["faith"] else []
        if i["gnome_only"]:
            visible.append("culture = { has_cultural_pillar = heritage_gnomish }")
        visible = visible or ["always = yes"]
        vis = "\n".join(f"\t{v}" for v in visible)
        out.append(
            f"aov_invention_{k}_visible = {{\n{vis}\n}}\n"
            f"aov_invention_{k}_unlocked = {{\n\tculture = {{ has_cultural_era_or_later = {ERAS[i['tier']]} }}\n}}\n"
            f"aov_invention_{k}_available = {{\n\taov_invention_{k}_visible = yes\n\taov_invention_{k}_unlocked = yes\n}}\n"
            f"aov_invention_{k}_discovered = {{\n\thas_variable = aov_inv_{k}\n}}\n"
            f"aov_invention_{k}_active = {{\n\thas_variable = aov_inv_{k}\n\tvar:aov_inv_{k} = 2\n}}\n"
            f"aov_invention_{k}_discoverable = {{\n\taov_invention_{k}_available = yes\n\tNOT = {{ has_variable = aov_inv_{k} }}\n}}\n"
            f"aov_invention_{k}_activatable = {{\n\thas_variable = aov_inv_{k}\n\tvar:aov_inv_{k} = 1\n\taov_invention_{k}_available = yes\n}}\n"
            f"aov_invention_{k}_offered = {{\n\tOR = {{ {offered(i)} }}\n}}\n"
        )
    out.append(any_of("aov_inventions_any_discovered", "Has discovered at least one invention", invs,
                      lambda i: f"aov_invention_{i['key']}_discovered = yes"))
    out.append(f"# Something is left to discover in the unlocked tiers\naov_inventions_any_discoverable = {{\n\tOR = {{\n"
               + "\n".join(f"\t\taov_inventions_{c}_discoverable = yes" for c in CATEGORIES) + "\n\t}\n}\n")
    for c in CATEGORIES:
        out.append(any_of(f"aov_inventions_{c}_discoverable", f"Something {c} is left to discover", of(invs, c),
                          lambda i: f"aov_invention_{i['key']}_discoverable = yes"))
        out.append(any_of(f"aov_inventions_{c}_unoffered_discoverable", f"A {c} invention could still be offered", of(invs, c),
                          lambda i: f"AND = {{ aov_invention_{i['key']}_discoverable = yes NOT = {{ aov_invention_{i['key']}_offered = yes }} }}"))
    out.append(any_of("aov_inventions_any_activatable", "A discovered invention could be activated", invs,
                      lambda i: f"aov_invention_{i['key']}_activatable = yes"))
    for t in (1, 2, 3):
        out.append(any_of(f"aov_inventions_t{t}_activatable", f"A tier {t} invention could be activated", of(invs, tier=t),
                          lambda i: f"aov_invention_{i['key']}_activatable = yes"))
        for c in CATEGORIES:
            out.append(any_of(f"aov_inventions_t{t}_{c}_activatable", f"A tier {t} {c} invention could be activated",
                              of(invs, c, t), lambda i: f"aov_invention_{i['key']}_activatable = yes"))
    return "\n".join(out)


def values(invs: list) -> str:
    active = "\n".join(f"\tif = {{ limit = {{ aov_invention_{i['key']}_active = yes }} add = 1 }}" for i in invs)
    newest = "\n".join(
        f"\tif = {{ limit = {{ aov_invention_{i['key']}_active = yes has_variable = aov_inv_{i['key']}_order }} min = var:aov_inv_{i['key']}_order }}"
        for i in invs
    )
    return (
        HEADER
        + f"\n# Character scope: number of active inventions\naov_invention_active_count = {{\n\tvalue = 0\n{active}\n}}\n"
        + f"\n# Character scope: highest activation order among active inventions\naov_invention_newest_order = {{\n\tvalue = 0\n{newest}\n}}\n"
    )


def effects(invs: list) -> str:
    out = [HEADER, "# All effects are character scope (the ruler).\n"]
    for i in invs:
        k = i["key"]
        out.append(
            f"aov_invention_{k}_discover = {{\n"
            f"\tset_variable = {{ name = aov_inv_{k} value = 1 }}\n"
            f"\tset_variable = {{ name = aov_last_discovered value = flag:{k} }}\n}}\n"
            f"aov_invention_{k}_activate = {{\n"
            f"\tif = {{ limit = {{ NOT = {{ has_variable = aov_inv_activation_counter }} }} set_variable = {{ name = aov_inv_activation_counter value = 0 }} }}\n"
            f"\tchange_variable = {{ name = aov_inv_activation_counter add = 1 }}\n"
            f"\tset_variable = {{ name = aov_inv_{k} value = 2 }}\n"
            f"\tset_variable = {{ name = aov_inv_{k}_order value = var:aov_inv_activation_counter }}\n"
            f"\tif = {{\n\t\tlimit = {{ NOT = {{ has_variable = aov_artificery_dormant }} NOT = {{ has_character_modifier = aov_invention_{k} }} }}\n"
            f"\t\tadd_character_modifier = {{ modifier = aov_invention_{k} }}\n\t}}\n}}\n"
            f"aov_invention_{k}_deactivate = {{\n"
            f"\tset_variable = {{ name = aov_inv_{k} value = 1 }}\n"
            f"\tremove_variable = aov_inv_{k}_order\n"
            f"\tif = {{ limit = {{ has_character_modifier = aov_invention_{k} }} remove_character_modifier = aov_invention_{k} }}\n}}\n"
        )

    disc = lambda i: f"aov_invention_{i['key']}_discoverable = yes"  # noqa: E731
    discover = lambda i: f"aov_invention_{i['key']}_discover = yes"  # noqa: E731
    out.append(f"# Brillites: a random undiscovered available invention\naov_inventions_discover_random = {{\n{draw(invs, disc, discover)}\n}}\n")
    for c in CATEGORIES:
        out.append(f"# Mechanists: a random undiscovered available {c} invention\n"
                   f"aov_inventions_discover_random_{c} = {{\n{draw(of(invs, c), disc, discover)}\n}}\n")
        rolls = []
        for n in range(1, OFFERS + 1):
            cond = lambda i: f"aov_invention_{i['key']}_discoverable = yes NOT = {{ aov_invention_{i['key']}_offered = yes }}"  # noqa: E731
            setv = lambda i, n=n: f"set_variable = {{ name = aov_tech_offer_{c}_{n} value = flag:{i['key']} }}"  # noqa: E731
            rolls.append(f"\tif = {{\n\t\tlimit = {{ aov_inventions_{c}_unoffered_discoverable = yes }}\n{draw(of(invs, c), cond, setv, 2)}\n\t}}")
        clears = "\n".join(f"\tremove_variable = aov_tech_offer_{c}_{n}" for n in range(1, OFFERS + 1))
        out.append(f"# Technomancers: roll up to {OFFERS} {c} offers for this research cycle\n"
                   f"aov_inventions_roll_offers_{c} = {{\n{clears}\n\tset_variable = aov_tech_offers_rolled_{c}\n" + "\n".join(rolls) + "\n}\n")
        out.append(f"# AI: start Technomancer research on one of the rolled {c} offers\n"
                   f"aov_inventions_ai_start_technomancers_{c} = {{\n"
                   + draw(of(invs, c), lambda i: f"aov_invention_{i['key']}_offered = yes aov_invention_{i['key']}_discoverable = yes",
                          lambda i, c=c: f"aov_artificery_start_technomancers_research = {{ CATEGORY = {c} TARGET = {i['key']} }}")
                   + "\n}\n")

    out.append("# Technomancers: discover the chosen target if it is still discoverable\naov_inventions_discover_research_target = {\n"
               + chain(invs, lambda i: f"var:aov_research_target = flag:{i['key']} aov_invention_{i['key']}_discoverable = yes", discover)
               + "\n}\n")
    out.append("# Discovery event option: activate what was just discovered\naov_inventions_activate_last_discovered = {\n"
               + chain(invs, lambda i: f"has_variable = aov_last_discovered var:aov_last_discovered = flag:{i['key']} aov_invention_{i['key']}_activatable = yes",
                       lambda i: f"aov_invention_{i['key']}_activate = yes")
               + "\n}\n")
    out.append("# Dormancy: remove every invention modifier\naov_inventions_suspend_all = {\n"
               + "\n".join(f"\tif = {{ limit = {{ has_character_modifier = aov_invention_{i['key']} }} remove_character_modifier = aov_invention_{i['key']} }}" for i in invs)
               + "\n}\n")
    out.append("# Dormancy ended: restore the modifiers of active inventions\naov_inventions_resume_all = {\n"
               + "\n".join(f"\tif = {{ limit = {{ aov_invention_{i['key']}_active = yes NOT = {{ has_character_modifier = aov_invention_{i['key']} }} }} add_character_modifier = {{ modifier = aov_invention_{i['key']} }} }}" for i in invs)
               + "\n}\n")
    out.append("# Over the slot maximum: deactivate the most recently activated invention (no cooldown)\naov_inventions_deactivate_newest = {\n"
               + chain(invs, lambda i: f"aov_invention_{i['key']}_active = yes has_variable = aov_inv_{i['key']}_order var:aov_inv_{i['key']}_order = aov_invention_newest_order",
                       lambda i: f"aov_invention_{i['key']}_deactivate = yes")
               + "\n}\n")

    inherit = []
    for i in invs:
        k = i["key"]
        inherit.append(
            f"\tif = {{\n\t\tlimit = {{ scope:aov_predecessor = {{ aov_invention_{k}_active = yes }} NOT = {{ aov_invention_{k}_active = yes }} }}\n"
            f"\t\taov_invention_{k}_activate = yes\n\t}}\n"
            f"\telse_if = {{\n\t\tlimit = {{ scope:aov_predecessor = {{ has_variable = aov_inv_{k} }} NOT = {{ has_variable = aov_inv_{k} }} }}\n"
            f"\t\tset_variable = {{ name = aov_inv_{k} value = 1 }}\n\t}}"
        )
    for c in CATEGORIES:
        copies = "\n".join(
            f"\t\tif = {{ limit = {{ scope:aov_predecessor = {{ has_variable = aov_tech_offer_{c}_{n} }} }} "
            f"set_variable = {{ name = aov_tech_offer_{c}_{n} value = scope:aov_predecessor.var:aov_tech_offer_{c}_{n} }} }}"
            for n in range(1, OFFERS + 1)
        )
        inherit.append(
            f"\tif = {{\n\t\tlimit = {{ scope:aov_predecessor = {{ has_variable = aov_tech_offers_rolled_{c} }} NOT = {{ has_variable = aov_tech_offers_rolled_{c} }} }}\n"
            f"\t\tset_variable = aov_tech_offers_rolled_{c}\n{copies}\n\t}}"
        )
    out.append("# Heir scope; scope:aov_predecessor is the dead ruler. Union of discoveries; their active inventions become active.\n"
               "aov_inventions_inherit = {\n" + "\n".join(inherit) + "\n}\n")

    tiers = []
    for n, t in enumerate((3, 2, 1)):
        kw = "if" if n == 0 else "else_if"
        tiers.append(f"\t{kw} = {{\n\t\tlimit = {{ aov_inventions_t{t}_activatable = yes }}\n\t\taov_inventions_ai_activate_tier_{t} = yes\n\t}}")
    out.append("# AI: activate the highest-tier discovered invention\naov_inventions_ai_activate_best = {\n" + "\n".join(tiers) + "\n}\n")
    act = lambda i: f"aov_invention_{i['key']}_activatable = yes"  # noqa: E731
    activate = lambda i: f"aov_invention_{i['key']}_activate = yes"  # noqa: E731
    for t in (1, 2, 3):
        out.append(
            f"# AI: tier {t}, Military at war, Economic at peace, otherwise any\naov_inventions_ai_activate_tier_{t} = {{\n"
            f"\tif = {{\n\t\tlimit = {{ is_at_war = yes aov_inventions_t{t}_military_activatable = yes }}\n{draw(of(invs, 'military', t), act, activate, 2)}\n\t}}\n"
            f"\telse_if = {{\n\t\tlimit = {{ is_at_war = no aov_inventions_t{t}_economic_activatable = yes }}\n{draw(of(invs, 'economic', t), act, activate, 2)}\n\t}}\n"
            f"\telse = {{\n{draw(of(invs, tier=t), act, activate, 2)}\n\t}}\n}}\n"
        )
    return "\n".join(out)


def custom_loc(invs: list) -> str:
    def entry(name, var):
        texts = "\n".join(
            f"\ttext = {{\n\t\ttrigger = {{ has_variable = {var} var:{var} = flag:{i['key']} }}\n\t\tlocalization_key = aov_invention_{i['key']}\n\t}}"
            for i in invs
        )
        return f"{name} = {{\n\ttype = character\n{texts}\n}}\n"
    return HEADER + "\n" + entry("AovLastDiscoveredName", "aov_last_discovered") + "\n" + entry("AovResearchTargetName", "aov_research_target")


def loc(invs: list) -> str:
    out = ["l_english:", " # " + HEADER.strip("# \n")]
    for i in invs:
        k = i["key"]
        out.append(f' aov_invention_{k}: "{i["name"]}"')
        out.append(f' aov_invention_{k}_desc: "{i["desc"]}"')
        out.append(f' aov_invention_{k}_tt: "#T $aov_invention_{k}$#!\\n#weak $AOV_CATEGORY_{i["category"].upper()}$, $AOV_TIER_{i["tier"]}$#!\\n\\n$aov_invention_{k}_desc$"')
        out.append(f' aov_invention_{k}_subtitle: "$AOV_CATEGORY_{i["category"].upper()}$, $AOV_TIER_{i["tier"]}$"')
    return "\n".join(out) + "\n"


ROOT = "GuiScope.SetRoot( GetPlayer.MakeScope ).End"


def sg(k: str, s: str) -> str:
    return f"GetScriptedGui('aov_inv_{k}_{s}_sgui')"


def sguis(invs: list) -> str:
    out = [HEADER]
    for i in invs:
        k, c = i["key"], i["category"]
        out.append(
            f"aov_inv_{k}_visible_sgui = {{\n\tscope = character\n\tis_shown = {{ aov_invention_{k}_visible = yes }}\n}}\n"
            f"aov_inv_{k}_unlocked_sgui = {{\n\tscope = character\n\tis_shown = {{ aov_invention_{k}_unlocked = yes }}\n}}\n"
            f"aov_inv_{k}_undiscovered_sgui = {{\n\tscope = character\n\tis_shown = {{ aov_invention_{k}_unlocked = yes NOT = {{ aov_invention_{k}_discovered = yes }} }}\n}}\n"
            f"aov_inv_{k}_activate_sgui = {{\n\tscope = character\n"
            f"\tis_shown = {{ aov_invention_{k}_discovered = yes NOT = {{ aov_invention_{k}_active = yes }} }}\n"
            f"\tis_valid = {{ aov_invention_{k}_available = yes aov_artificery_has_free_slot = yes }}\n"
            f"\teffect = {{ aov_invention_{k}_activate = yes }}\n}}\n"
            f"aov_inv_{k}_deactivate_sgui = {{\n\tscope = character\n"
            f"\tis_shown = {{ aov_invention_{k}_active = yes }}\n"
            f"\teffect = {{\n\t\taov_invention_{k}_deactivate = yes\n\t\taov_artificery_start_slot_cooldown = yes\n\t}}\n}}\n"
            f"# Clicking the invention box: activate, or deactivate if active\n"
            f"aov_inv_{k}_toggle_sgui = {{\n\tscope = character\n"
            f"\tis_valid = {{\n\t\taov_invention_{k}_discovered = yes\n"
            f"\t\ttrigger_if = {{\n\t\t\tlimit = {{ NOT = {{ aov_invention_{k}_active = yes }} }}\n"
            f"\t\t\taov_invention_{k}_available = yes\n\t\t\taov_artificery_has_free_slot = yes\n\t\t}}\n\t}}\n"
            f"\teffect = {{\n"
            f"\t\tif = {{\n\t\t\tlimit = {{ aov_invention_{k}_active = yes }}\n"
            f"\t\t\taov_invention_{k}_deactivate = yes\n\t\t\taov_artificery_start_slot_cooldown = yes\n\t\t}}\n"
            f"\t\telse = {{ aov_invention_{k}_activate = yes }}\n\t}}\n}}\n"
            f"aov_inv_{k}_offered_sgui = {{\n\tscope = character\n\tis_shown = {{ aov_invention_{k}_offered = yes aov_invention_{k}_discoverable = yes }}\n}}\n"
            f"aov_inv_{k}_research_sgui = {{\n\tscope = character\n"
            f"\tis_valid = {{ aov_artificery_can_sponsor = {{ FACTION = technomancers }} aov_invention_{k}_discoverable = yes }}\n"
            f"\teffect = {{ aov_artificery_start_technomancers_research = {{ CATEGORY = {c} TARGET = {k} }} }}\n}}\n"
            f"# Never executed: its tooltip shows the invention's effects\n"
            f"aov_inv_{k}_effects_sgui = {{\n\tscope = character\n\teffect = {{ add_character_modifier = {{ modifier = aov_invention_{k} }} }}\n}}\n"
        )
    return "\n".join(out)


SECTIONS = ("society", "economic", "military")  # EU4 order
PER_ROW = 5


def ind(text: str, n: int) -> str:
    pad = "\t" * n
    return "".join(pad + line if line.strip() else line for line in text.splitlines(True))


def shown(k: str, s: str) -> str:
    return f"{sg(k, s)}.IsShown( {ROOT} )"


def valid(k: str, s: str) -> str:
    return f"{sg(k, s)}.IsValid( {ROOT} )"


def tooltip_type(i) -> str:
    k, t = i["key"], i["tier"]
    paras = [
        ("", f"aov_invention_{k}_desc"),
        ("", f"[{sg(k, 'effects')}.BuildTooltip( {ROOT} )]"),
        (f"Not( {shown(k, 'unlocked')} )", f"AOV_INV_LOCKED_TIER_{t}_TT"),
        (shown(k, "undiscovered"), "AOV_INV_UNDISCOVERED_TT"),
        (f"And( {shown(k, 'activate')}, {valid(k, 'activate')} )", "AOV_INV_CLICK_ACTIVATE"),
        (f"And( {shown(k, 'activate')}, Not( {valid(k, 'activate')} ) )", "AOV_INV_NO_FREE_SLOT"),
        (shown(k, "deactivate"), "AOV_INV_CLICK_DEACTIVATE"),
    ]
    body = "".join(
        "cooltip_paragraph = {\n" + (f'\tvisible = "[{vis}]"\n' if vis else "") + f'\ttext = "{text}"\n}}\n'
        for vis, text in paras
    )
    return (
        f"type aov_invention_{k}_tooltip = object_tooltip_pop_out {{\n"
        f'\tblockoverride "title_text" {{\n\t\ttext = "aov_invention_{k}"\n\t\tdefault_format = "#T"\n\t}}\n\n'
        f'\tblockoverride "subtitle_text" {{\n\t\ttext = "aov_invention_{k}_subtitle"\n\t}}\n\n'
        f'\tblockoverride "concept_link" {{\n\t\tvisible = no\n\t}}\n\n'
        f'\tblockoverride "main_description" {{\n\t\tvbox = {{\n\t\t\tlayoutpolicy_horizontal = expanding\n\t\t\tspacing = 8\n\n'
        + ind(body, 3)
        + "\t\t}\n\t}\n}\n"
    )


def box(i) -> str:
    """EU4-style invention box: click to activate, click again to deactivate."""
    k = i["key"]
    tex = f"{ICON_DIR}/{i['icon']}"
    discovered = f"Or( {shown(k, 'activate')}, {shown(k, 'deactivate')} )"
    greyed = lambda vis, alpha: (  # noqa: E731
        f"\t\ticon = {{\n"
        f'\t\t\tvisible = "[{vis}]"\n'
        f"\t\t\tparentanchor = center\n"
        f"\t\t\tsize = {{ 63 60 }}\n"
        f'\t\t\ttexture = "{tex}"\n'
        f'\t\t\teffectname = "GreyedOut"\n'
        f"\t\t\talpha = {alpha}\n"
        f"\t\t}}\n"
    )
    return (
        f"widget = {{\n"
        f'\tname = "aov_inv_box_{k}"\n'
        f'\tvisible = "[{shown(k, "visible")}]"\n'
        f"\tsize = {{ 72 70 }}\n\n"
        f"\tselection_glow = {{\n"
        f'\t\tvisible = "[{shown(k, "deactivate")}]"\n'
        f"\t}}\n\n"
        f"\tbutton_standard_clean = {{\n"
        f"\t\tsize = {{ 100% 100% }}\n"
        f'\t\tdown = "[{shown(k, "deactivate")}]"\n'
        f'\t\tonclick = "[{sg(k, "toggle")}.Execute( {ROOT} )]"\n\n'
        f"\t\ttooltipwidget = {{\n\t\t\taov_invention_{k}_tooltip = {{}}\n\t\t}}\n\n"
        f"\t\ticon = {{\n"
        f'\t\t\tvisible = "[{discovered}]"\n'
        f"\t\t\tparentanchor = center\n"
        f"\t\t\tsize = {{ 63 60 }}\n"
        f'\t\t\ttexture = "{tex}"\n'
        f"\t\t}}\n\n"
        f"\t\t# Undiscovered\n"
        + greyed(shown(k, "undiscovered"), "0.6")
        + f"\n\t\t# Locked: the tier's era is not reached yet\n"
        + greyed(f"Not( {shown(k, 'unlocked')} )", "0.25")
        + f"\t}}\n"
        f"}}\n"
    )


def section(invs: list, tier: int, category: str) -> str:
    """A framed group of boxes with a header, like EU4's Society/Economic/Military Inventions."""
    members = of(invs, category, tier)
    rows = []
    for n in range(0, len(members), PER_ROW):
        rows.append("hbox = {\n\tspacing = 6\n\n" + ind("\n".join(box(i) for i in members[n:n + PER_ROW]), 1) + "}\n")
    return (
        f"vbox = {{\n"
        f'\tname = "aov_inventions_t{tier}_{category}"\n'
        f"\tlayoutpolicy_horizontal = expanding\n"
        f"\tmargin = {{ 12 10 }}\n"
        f"\tmargin_bottom = 14\n"
        f"\tspacing = 6\n\n"
        f"\tbackground = {{\n\t\tusing = Background_Area_With_Header\n\t}}\n\n"
        f"\ttext_single = {{\n"
        f'\t\ttext = "AOV_INVENTIONS_SECTION_{category.upper()}"\n'
        f"\t\tusing = Font_Type_Flavor\n"
        f"\t\tusing = Font_Size_Medium\n"
        f'\t\tdefault_format = "#T"\n'
        f"\t\tmargin_bottom = 6\n"
        f"\t\talign = center|nobaseline\n"
        f"\t}}\n\n"
        + ind("\n".join(rows), 1)
        + "}\n"
    )


def offer_option(i) -> str:
    """A Technomancer proposal, drawn as an event option."""
    k = i["key"]
    return (
        f"button_event_standard = {{\n"
        f'\tname = "aov_inv_offer_{k}"\n'
        f'\tvisible = "[{shown(k, "offered")}]"\n'
        f"\tsize = {{ 460 38 }}\n"
        f'\tenabled = "[{valid(k, "research")}]"\n'
        f'\tonclick = "[{sg(k, "research")}.Execute( {ROOT} )]"\n'
        f"\tonclick = \"[GetVariableSystem.Clear( 'aov_research_popup' )]\"\n\n"
        f"\ttooltipwidget = {{\n\t\taov_invention_{k}_tooltip = {{}}\n\t}}\n\n"
        f"\thbox = {{\n"
        f"\t\tmargin_left = 8\n"
        f"\t\tmargin_right = 12\n"
        f"\t\tspacing = 8\n\n"
        f'\t\ticon = {{\n\t\t\tsize = {{ 34 32 }}\n\t\t\ttexture = "{ICON_DIR}/{i["icon"]}"\n\t\t}}\n\n'
        f'\t\ttext_single = {{\n\t\t\tlayoutpolicy_horizontal = expanding\n\t\t\ttext = "aov_invention_{k}"\n\t\t\tmax_width = 330\n\t\t\talign = left|nobaseline\n\t\t}}\n\n'
        f'\t\ttext_single = {{\n\t\t\ttext = "AOV_RESEARCH_COST"\n\t\t\talign = right|nobaseline\n\t\t}}\n'
        f"\t}}\n"
        f"}}\n"
    )


def gui(invs: list) -> str:
    parts = [HEADER, "\ntypes AovInventions\n{\n"]
    parts.append("\t# Hover tooltip of an invention's box and Technomancer proposal\n")
    parts.extend(ind(tooltip_type(i), 1) + "\n" for i in invs)
    for t in (1, 2, 3):
        body = "\n".join(section(invs, t, c) for c in SECTIONS)
        parts.append(f"\t# Tier {t} tab of the Inventions tab\n\ttype aov_inventions_tier_{t} = vbox {{\n\t\tspacing = 10\n\n" + ind(body, 2) + "\t}\n\n")
    for c in CATEGORIES:
        body = "\n".join(offer_option(i) for i in of(invs, c))
        parts.append(f"\t# Technomancer proposals in the {c} field\n\ttype aov_inventions_offers_{c} = vbox {{\n\t\tspacing = 4\n\n" + ind(body, 2) + "\t}\n\n")
    parts.append("}\n")
    return "".join(parts)


def render_all(invs: list) -> dict:
    return {
        "common/modifiers/aov_invention_modifiers.txt": modifiers(invs),
        "common/scripted_triggers/aov_invention_triggers.txt": triggers(invs),
        "common/script_values/aov_invention_values.txt": values(invs),
        "common/scripted_effects/aov_invention_effects.txt": effects(invs),
        "common/scripted_guis/aov_invention_sgui.txt": sguis(invs),
        "common/customizable_localization/aov_invention_custom_loc.txt": custom_loc(invs),
        "gui/aov_inventions_generated.gui": gui(invs),
        "localization/english/aov_inventions_l_english.yml": loc(invs),
    }


def write_all(files: dict, root: Path) -> None:
    for rel, text in files.items():
        out = root / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\xef\xbb\xbf" + text.replace("\r\n", "\n").encode("utf-8"))


def copy_icons(invs: list, eu4: Path, root: Path) -> None:
    src_dir = eu4 / EU4_ICONS
    names = sorted({i["icon"] for i in invs})
    missing = [n for n in names if not (src_dir / n).is_file()]
    if missing:
        raise GeneratorError(f"EU4 icons not found in {src_dir}: {', '.join(missing)}")
    dst = root / ICON_DIR
    dst.mkdir(parents=True, exist_ok=True)
    for n in names:
        shutil.copyfile(src_dir / n, dst / n)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--eu4", type=Path, default=DEFAULT_EU4)
    args = parser.parse_args()
    try:
        invs = load_inventions()
        validate(invs)
        files = render_all(invs)
        write_all(files, SUBMOD)
        copy_icons(invs, args.eu4, SUBMOD)
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    print(f"wrote {len(files)} files and {len({i['icon'] for i in invs})} icons for {len(invs)} inventions")


if __name__ == "__main__":
    main()
