"""Generate the new Cannor monument buildings, province history and localization.

Source: tools/data/monuments/<region>.py (monument data) and translation.py (icons). Rerun after editing them:

    python -I tools/build_monuments.py --region cannor

Building levels whose key Anbennar does not define are written to aov_monuments_<region>.txt. Levels Anbennar does
define are re-emitted, with the EU4 tier lines inserted, in zz_aov_monument_overrides_<region>.txt (single-object
overrides that load after Anbennar); they copy Anbennar's current definition, so rerun after an Anbennar update.
"""

import argparse
import importlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # python -I does not add the script's folder
from data.monuments import translation  # noqa: E402

SUBMOD = Path(__file__).resolve().parent.parent
ANBENNAR_CK3 = SUBMOD.parent / "anbennar-ck3-dev-master"
GAME = Path("C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")
HEADER = "# Anbennar Overhaul: generated by tools/build_monuments.py from tools/data/monuments/; do not edit by hand.\n"
ROMAN = {1: "", 2: " (II)", 3: " (III)"}
BLOCKS = ("province_modifier", "county_modifier", "character_modifier")
DROPPED_NOTE = " Some effects of the original Europa Universalis IV project have no Crusader Kings III equivalent and are omitted."


NL = "\n"


class GeneratorError(Exception):
    pass


def anbennar_keys(root: Path = ANBENNAR_CK3) -> set:
    keys = set()
    for f in (Path(root) / "common" / "buildings").glob("*.txt"):
        keys.update(re.findall(r"^([A-Za-z0-9_]+)\s*=\s*\{", f.read_text(encoding="utf-8-sig"), re.M))
    return keys


def strip_comment(line: str) -> str:
    return line.split("#", 1)[0]


def anbennar_definition(root, key: str) -> str:
    """Anbennar's text for building `key`, from `key = {` to the matching `}` (raises GeneratorError if absent)."""
    head = re.compile(rf"^{re.escape(key)}\s*=\s*\{{")
    for f in sorted((Path(root) / "common" / "buildings").glob("*.txt")):
        lines = f.read_text(encoding="utf-8-sig").splitlines()
        for i, line in enumerate(lines):
            if head.match(line):
                depth = 0
                for j in range(i, len(lines)):
                    code = strip_comment(lines[j])
                    depth += code.count("{") - code.count("}")
                    if depth <= 0:
                        return NL.join(lines[i:j + 1]) + NL
                raise GeneratorError(f"unbalanced braces in Anbennar building {key}")
    raise GeneratorError(f"Anbennar building {key} not found in common/buildings")


def depths_of(lines: list) -> list:
    """Brace depth before each line."""
    out, depth = [], 0
    for line in lines:
        out.append(depth)
        code = strip_comment(line)
        depth += code.count("{") - code.count("}")
    return out


def find_block(lines: list, name: str):
    """(start, closing-brace) line indexes of the depth-1 block `name = {`, or None."""
    depths = depths_of(lines)
    for i, line in enumerate(lines):
        if depths[i] == 1 and re.match(rf"\t{name}\s*=\s*\{{", line):
            if i + 1 < len(depths) and depths[i + 1] == 1:
                raise GeneratorError(f"{name} opens and closes on one line: {line.strip()}")
            for j in range(i + 1, len(lines)):
                if depths[j] == 1:
                    return i, j - 1  # j is the line after the closing brace
    return None


def insert_point(lines: list) -> int:
    """Index of the depth-1 `type = ` line (new blocks go before it); falls back to the closing brace."""
    depths = depths_of(lines)
    for i, line in enumerate(lines):
        if depths[i] == 1 and re.match(r"\ttype\s*=", line):
            return i
    return len(lines) - 1


NUMBER = re.compile(r"-?\d+(\.\d+)?")


def parse_values(text: str) -> dict:
    """name -> raw right-hand side for `name = value` and `@name = value` lines of a script_values file."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"@?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^#\s][^#]*?)\s*(#.*)?$", line)
        if m:
            out.setdefault(m.group(1), m.group(2))
    return out


def load_values(root: Path = ANBENNAR_CK3) -> dict:
    """Building values; Anbennar's 00_building_values.txt first, the game's as a fallback for missing names."""
    out = {}
    for base in (Path(root), GAME):
        f = base / "common" / "script_values" / "00_building_values.txt"
        if f.is_file():
            for k, v in parse_values(f.read_text(encoding="utf-8-sig")).items():
                out.setdefault(k, v)
    return out


def resolve(raw: str, values: dict, seen=()) -> float:
    """Numeric value of a script value (number, `name`, `@name`, `@[expression]`); ValueError when it cannot be resolved."""
    raw = raw.strip()
    if NUMBER.fullmatch(raw):
        return float(raw)
    if raw.startswith("@["):
        if not raw.endswith("]"):
            raise ValueError(f"bad expression {raw}")
        raw = raw[2:-1]
    elif raw.startswith("@"):
        raw = raw[1:]
    if not re.fullmatch(r"[A-Za-z0-9_.+\-*/() ]+", raw):
        raise ValueError(f"not a plain expression: {raw}")

    def name(m):
        word = m.group(0)
        if NUMBER.fullmatch(word):
            return word
        if word in seen:
            raise ValueError(f"circular value {word}")
        if word not in values:
            raise ValueError(f"unknown name {word}")
        return f"({resolve(values[word], values, seen + (word,))!r})"

    expr = re.sub(r"[A-Za-z_][A-Za-z0-9_]*|\d+(\.\d+)?", name, raw)
    try:
        return float(eval(expr, {"__builtins__": {}}, {}))  # only digits and + - * / ( ) remain
    except Exception as e:
        raise ValueError(f"cannot evaluate {raw}: {e}")


def merge_modifier(lines: list, name: str, k: str, v, values: dict, note: str, warnings: list, key: str):
    """If the modifier block already has `k`, sum into that line (True) or leave it with a comment (also True); else False."""
    start, end = find_block(lines, name)
    for i in range(start + 1, end):
        m = re.match(rf"(\s*){re.escape(k)}\s*=\s*([^#\s]+)", lines[i])
        if m:
            indent, old = m.group(1), m.group(2)
            try:
                total = resolve(old, values) + float(v)
            except ValueError as e:
                msg = f"{k} {old} not added ({e})"
                warnings.append(f"{key} tier {note.rsplit(' ', 1)[1]}: {msg}")
                lines[i + 1:i + 1] = [f"{indent}{note} {msg}"]
                return True
            lines[i:i + 1] = [f"{indent}{note} (+{num(v)} to {old} = {num(total - float(v))})",
                              f"{indent}{k} = {num(total)}"]
            return True
    return False


def override(base_text: str, key: str, tier: dict, next_key, n: int, values=None, warnings=None) -> str:
    """Anbennar's definition of `key` with the EU4 tier `n` effects inserted and next_building set."""
    values = values or {}
    warnings = [] if warnings is None else warnings
    lines = base_text.rstrip(NL).split(NL)
    lines[0] = f"{key} = {{"  # drop any trailing comment on the opening line
    note = f"# Anbennar Overhaul: EU4 tier {n}"
    for name in BLOCKS:
        mods = tier[name]
        if not mods:
            continue
        found = find_block(lines, name)
        if found:
            new = []
            for k, v in mods.items():
                if not merge_modifier(lines, name, k, v, values, note, warnings, key):
                    new.append(f"\t\t{k} = {num(v)}")
            if new:
                end = find_block(lines, name)[1]
                lines[end:end] = [f"\t\t{note}"] + new
        else:
            at = insert_point(lines)
            lines[at:at] = [f"\t{name} = {{", f"\t\t{note}"] + [f"\t\t{k} = {num(v)}" for k, v in mods.items()] + ["\t}", ""]
    if tier["on_complete"].strip():
        found = find_block(lines, "on_complete")
        body = [f"\t\t{note}", f"\t\t{tier['on_complete'].strip()}"]
        if found:
            lines[found[1]:found[1]] = body
        else:
            at = insert_point(lines)
            lines[at:at] = ["\ton_complete = {"] + body + ["\t}", ""]
    if next_key:
        depths = depths_of(lines)
        line = f"\tnext_building = {next_key} {note}"
        for i, l in enumerate(lines):
            if depths[i] == 1 and re.match(r"\tnext_building\s*=", l):
                lines[i] = line
                break
        else:
            at = insert_point(lines)
            lines[at:at] = [line, ""]
    return NL.join(lines) + NL


def load_monuments(region: str) -> list:
    return importlib.import_module(f"data.monuments.{region}").MONUMENTS


def num(v) -> str:
    s = f"{float(v):.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("", "-0") else s


def building(m: dict, level: int, key: str, next_key, icon=None) -> str:
    tier = m["tiers"][level - 1]
    icon = icon or translation.ICONS[m["category"]]
    out = [f"{key} = {{", f"\tconstruction_time = {tier['days']}", "",
           f'\ttype_icon = "{icon}"', "",
           "\tcan_construct_potential = {", "\t\tbuilding_requirement_tribal = no", "\t}", ""]
    if m["gate"]:
        tt = f"aov_monument_{m['eu4_key']}_gate"
        for name in ("can_construct", "is_enabled"):
            out += [f"\t{name} = {{", "\t\tscope:holder = {", f"\t\t\tcustom_tooltip = {{", f"\t\t\t\ttext = {tt}",
                    f"\t\t\t\t{m['gate']}", "\t\t\t}", "\t\t}", "\t}", ""]
    out += [f"\tcost_gold = {tier['cost']}", ""]
    for block in BLOCKS:
        mods = tier[block]
        if mods:
            out.append(f"\t{block} = {{")
            out += [f"\t\t{k} = {num(v)}" for k, v in mods.items()]
            out += ["\t}", ""]
    if tier["on_complete"].strip():
        out += ["\ton_complete = {", f"\t\t{tier['on_complete'].strip()}", "\t}", ""]
    if next_key:
        out += [f"\tnext_building = {next_key}", ""]
    out += ["\tai_value = {", "\t\tbase = 100", "\t}", "", "\ttype = special", "}", ""]
    return "\n".join(out)


def written_levels(monuments: list, known: set):
    """Yield (monument, level, key, next_key) for every level this generator writes."""
    for m in monuments:
        keys = m["levels"]
        for i, key in enumerate(keys):
            if key not in known:
                yield m, i + 1, key, (keys[i + 1] if i + 1 < len(keys) else None)


def chain_icon(m: dict, known: set, root):
    """type_icon of the chain's tier-1 Anbennar level, or None when the chain starts with a new building."""
    first = m["levels"][0]
    if first not in known:
        return None
    found = re.search(r'type_icon\s*=\s*"([^"]+)"', anbennar_definition(root, first))
    return found.group(1) if found else None


def buildings(monuments: list, known: set, root: Path = ANBENNAR_CK3) -> str:
    return HEADER + "\n" + "\n".join(building(m, lvl, key, nxt, chain_icon(m, known, root))
                                     for m, lvl, key, nxt in written_levels(monuments, known))


def overrides(monuments: list, known: set, root: Path = ANBENNAR_CK3) -> str:
    out = [HEADER]
    values, warnings = load_values(root), []
    for m in monuments:
        keys = m["levels"]
        for i, key in enumerate(keys):
            if key in known:
                nxt = keys[i + 1] if i + 1 < len(keys) else None
                out.append(override(anbennar_definition(root, key), key, m["tiers"][i], nxt, i + 1, values, warnings))
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)
    return "\n".join(out)


def history(monuments: list, known: set) -> str:
    out = [HEADER]
    for m in monuments:
        first = m["levels"][0]
        if first in known:
            continue
        lines = [f"{m['province']} = {{", "\t1000.1.1 = {", f"\t\tspecial_building_slot = {first}"]
        if m["start_level"] == 1:
            lines.append(f"\t\tspecial_building = {first}")
        lines += ["\t}", "}", ""]
        out.append(NL.join(lines))
    return NL.join(out)


def q(text: str) -> str:
    return text.replace('"', "'")


def loc(monuments: list, known: set, root: Path = ANBENNAR_CK3) -> str:
    out = ["l_english:"]
    for m, level, key, _ in written_levels(monuments, known):
        name = m["name"] if m["levels"][0] == "castle_dameris_01" else m["name"] + ROMAN[level]
        desc = m["desc"] + (DROPPED_NOTE if m["tiers"][level - 1]["dropped"] else "")
        out.append(f' building_{key}: "{q(name)}"')
        out.append(f' building_{key}_desc: "{q(desc)}"')
    for m, level, key, _ in written_levels(monuments, known):  # tiger wants a type name for every level key
        out.append(f' building_type_{key}: "$building_{key}$"')
        out.append(f' building_type_{key}_desc: "$building_{key}_desc$"')
    anb_loc = NL.join(f.read_text(encoding="utf-8-sig") for f in (Path(root) / "localization" / "english").glob("*.yml"))
    for m in monuments:  # tiger wants a type description for overridden keys too; fill Anbennar's gaps
        for key in m["levels"]:
            if key in known and f" building_type_{key}_desc:" not in anb_loc:
                out.append(f' building_type_{key}_desc: "$building_{key}_desc$"')
    for m in monuments:
        if m["gate"]:
            out.append(f' aov_monument_{m["eu4_key"]}_gate: "{q("Built and used by: " + m["gate_desc"])}"')
    return "\n".join(out) + "\n"


def render_all(region: str, root: Path = ANBENNAR_CK3) -> dict:
    monuments = load_monuments(region)
    known = anbennar_keys(root)
    return {
        f"common/buildings/aov_monuments_{region}.txt": buildings(monuments, known, root),
        f"common/buildings/zz_aov_monument_overrides_{region}.txt": overrides(monuments, known, root),
        f"history/provinces/aov_monuments_{region}.txt": history(monuments, known),
        f"localization/english/aov_monuments_{region}_l_english.yml": loc(monuments, known, root),
    }


def write_all(files: dict, root: Path) -> None:
    for rel, text in files.items():
        out = Path(root) / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\xef\xbb\xbf" + text.replace("\r\n", "\n").encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--region", default="cannor")
    args = parser.parse_args()
    try:
        files = render_all(args.region)
        write_all(files, SUBMOD)
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    print(f"wrote {len(files)} files")


if __name__ == "__main__":
    main()
