"""Regenerate common/holdings/00_holdings.txt for Anbennar Overhaul.

CK3 holdings can only be overridden as a whole file, so the submod ships a full copy of
Anbennar's 00_holdings.txt with the overhaul's buildings added to the holding build lists.
Run this after updating the base Anbennar mod so the copy matches the new version:

    python tools/build_holdings_override.py [path/to/anbennar/mod/folder]

The base path defaults to ../anbennar-ck3-dev-master next to this submod.
"""

import sys
from pathlib import Path

# holding type -> buildings the overhaul adds to its build list
ADDITIONS = {
    "castle_holding": ["artificer_academy_01"],
    "city_holding": ["artificer_academy_01"],
}
MARKER = "# Anbennar Overhaul"
REL_PATH = Path("common/holdings/00_holdings.txt")

SUBMOD = Path(__file__).resolve().parent.parent


def add_buildings(text: str, holding: str, buildings: list[str]) -> str:
    lines = text.split("\n")
    try:
        start = next(i for i, l in enumerate(lines) if l.strip().startswith(f"{holding} = {{"))
        list_start = next(i for i in range(start, len(lines)) if l_is(lines[i], "buildings = {"))
    except StopIteration:
        sys.exit(f"error: could not find '{holding}' buildings list in base file")

    # Walk to the closing brace of the buildings block
    depth = 0
    for end in range(list_start, len(lines)):
        depth += lines[end].count("{") - lines[end].count("}")
        if depth == 0:
            break
    else:
        sys.exit(f"error: unbalanced braces in '{holding}' buildings list")

    existing = {l.split("#")[0].strip() for l in lines[list_start:end]}
    new = [f"\t\t{b} {MARKER}" for b in buildings if b not in existing]
    lines[end:end] = new
    return "\n".join(lines)


def l_is(line: str, prefix: str) -> bool:
    return line.strip().startswith(prefix)


def main() -> None:
    base = Path(sys.argv[1]) if len(sys.argv) > 1 else SUBMOD.parent / "anbennar-ck3-dev-master"
    src = base / REL_PATH
    if not src.is_file():
        sys.exit(f"error: base holdings file not found: {src}")

    raw = src.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    crlf = "\r\n" in text
    text = text.replace("\r\n", "\n")

    for holding, buildings in ADDITIONS.items():
        text = add_buildings(text, holding, buildings)

    header = (
        f"{MARKER}: generated by tools/build_holdings_override.py from Anbennar's {REL_PATH.as_posix()}.\n"
        f"{MARKER}: do not edit by hand; edit ADDITIONS in the script and rerun it.\n"
    )
    text = header + text
    if crlf:
        text = text.replace("\n", "\r\n")

    out = SUBMOD / REL_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes((b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8"))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
