"""Regenerate gui/hud.gui for Anbennar Overhaul.

The HUD tab bar can only be changed by overriding the whole hud.gui, so the submod ships a copy
with the Artificery main tab inserted directly below the Situations tab. The copy is taken from
Anbennar's gui/hud.gui if Anbennar ships one, otherwise from the game. Rerun this after every
CK3 patch and Anbennar update:

    python -I tools/build_hud_override.py [--anbennar PATH] [--game PATH]
"""

import argparse
import sys
from pathlib import Path

MARKER = "# Anbennar Overhaul"
BEGIN = f"{MARKER}: begin Artificery tab"
END = f"{MARKER}: end Artificery tab"
ANCHOR = 'name = "tab_situation"'
TAB_NAME = "tab_aov_artificery"
TEXTURE = "gfx/interface/skinned/hud_maintab/aov_maintab_artificery.dds"  # EU4 Anbennar research_artificery.dds
REL_PATH = Path("gui/hud.gui")

SUBMOD = Path(__file__).resolve().parent.parent
DEFAULT_ANBENNAR = SUBMOD.parent / "anbennar-ck3-dev-master"
DEFAULT_GAME = Path("C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")

# Inserted after the Situations tab, indented like the sibling widgets
BLOCK = [
    BEGIN,
    "widget_hud_main_tab = {",
    f'\tname = "{TAB_NAME}"',
    "\tvisible = \"[GetScriptedGui('aov_artificery_available').IsShown( GuiScope.SetRoot( GetPlayer.MakeScope ).End )]\"",
    "",
    '\tblockoverride "maintab_button"',
    "\t{",
    f'\t\ttexture = "{TEXTURE}"',
    "\t\t# Opening then closing a game view closes any open vanilla main tab, which would hide this window",
    "\t\tonclick = \"[ToggleGameView( 'decisions' )]\"",
    "\t\tonclick = \"[CloseGameView( 'decisions' )]\"",
    "\t\tonclick = \"[GetVariableSystem.Toggle( 'aov_artificery_window' )]\"",
    '\t\ttooltip = "AOV_ARTIFICERY_BUTTON"',
    "\t\tdown = \"[GetVariableSystem.Exists( 'aov_artificery_window' )]\"",
    "\t}",
    "}",
    END,
]


class GeneratorError(Exception):
    pass


def brace_delta(line: str) -> int:
    """Count '{' minus '}' outside double-quoted strings and '#' comments."""
    delta = 0
    in_string = False
    for ch in line:
        if ch == '"':
            in_string = not in_string
        elif in_string:
            continue
        elif ch == "#":
            break
        elif ch == "{":
            delta += 1
        elif ch == "}":
            delta -= 1
    return delta


def insert_tab(text: str) -> str:
    if TAB_NAME in text:
        raise GeneratorError(f"source already contains '{TAB_NAME}'; is it a generated file?")
    lines = text.split("\n")
    try:
        anchor = next(i for i, l in enumerate(lines) if l.strip() == ANCHOR)
    except StopIteration:
        raise GeneratorError(f"anchor '{ANCHOR}' not found; did a CK3 patch rename the Situations tab?")
    try:
        start = next(i for i in range(anchor, -1, -1) if lines[i].strip() == "widget_hud_main_tab = {")
    except StopIteration:
        raise GeneratorError("no 'widget_hud_main_tab = {' opens the Situations tab")

    depth = 0
    for end in range(start, len(lines)):
        depth += brace_delta(lines[end])
        if depth == 0:
            break
    else:
        raise GeneratorError("unbalanced braces in the Situations tab widget")

    indent = lines[start][: len(lines[start]) - len(lines[start].lstrip("\t"))]
    block = [""] + [indent + l if l else "" for l in BLOCK]
    lines[end + 1:end + 1] = block
    return "\n".join(lines)


def build(raw: bytes) -> bytes:
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    crlf = "\r\n" in text
    text = insert_tab(text.replace("\r\n", "\n"))
    header = (
        f"{MARKER}: generated by tools/build_hud_override.py from {REL_PATH.as_posix()}.\n"
        f"{MARKER}: do not edit by hand; edit the script and rerun it.\n"
    )
    text = header + text
    if crlf:
        text = text.replace("\n", "\r\n")
    return (b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8")


def find_source(anbennar: Path, game: Path) -> Path:
    for root in (anbennar, game):
        path = root / REL_PATH
        if path.is_file():
            return path
    raise GeneratorError(f"no {REL_PATH.as_posix()} in {anbennar} or {game}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--anbennar", type=Path, default=DEFAULT_ANBENNAR)
    parser.add_argument("--game", type=Path, default=DEFAULT_GAME)
    args = parser.parse_args()
    try:
        src = find_source(args.anbennar, args.game)
        data = build(src.read_bytes())
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    out = SUBMOD / REL_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    print(f"wrote {out} (from {src})")


if __name__ == "__main__":
    main()
