"""Regenerate gui/window_character_lifestyle.gui for Anbennar Overhaul.

The lifestyle window can only be changed by overriding the whole file, so the submod ships a copy
with a magic_lifestyle branch added next to every wanderer_lifestyle branch (XP bar colours and the
unspent-points icon), using the magic art. The copy is taken from Anbennar's
gui/window_character_lifestyle.gui if Anbennar ships one, otherwise from the game. Rerun this after
every CK3 patch and Anbennar update:

    python -I tools/build_lifestyle_override.py [--anbennar PATH] [--game PATH]
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_hud_override import GeneratorError, brace_delta  # noqa: E402

MARKER = "# Anbennar Overhaul: magic lifestyle"
HEADER_MARKER = "# Anbennar Overhaul"
ANCHOR = "EqualTo_string( Lifestyle.GetKey, 'wanderer_lifestyle' )"
EXPECTED_ANCHORS = 3
TEXTURES = {
    "gfx/interface/progressbars/progress_brown.dds": "gfx/interface/progressbars/aov_progress_magic.dds",
    "gfx/interface/progressbars/progress_brown_bg.dds": "gfx/interface/progressbars/aov_progress_magic_bg.dds",
    "gfx/interface/icons/lifestyles_perks/node_wanderer.dds": "gfx/interface/icons/lifestyles_perks/node_magic.dds",
}
REL_PATH = Path("gui/window_character_lifestyle.gui")

SUBMOD = Path(__file__).resolve().parent.parent
DEFAULT_ANBENNAR = SUBMOD.parent / "anbennar-ck3-dev-master"
DEFAULT_GAME = Path("C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")

TEXTURE_LINE = re.compile(r'^(\s*(?:texture|progresstexture|noprogresstexture)\s*=\s*)"([^"]*)"')


def magic_copy(block: list[str], indent: str) -> list[str]:
    out = [indent + MARKER]
    for line in block:
        line = line.replace("'wanderer_lifestyle'", "'magic_lifestyle'")
        m = TEXTURE_LINE.match(line)
        if m:
            path = m.group(2)
            if path not in TEXTURES:
                raise GeneratorError(f"no magic replacement for texture '{path}' in a wanderer_lifestyle block")
            line = line[: m.start(2)] + TEXTURES[path] + line[m.end(2):]
        out.append(line)
    return out


def insert_magic(text: str) -> str:
    if "'magic_lifestyle'" in text:
        raise GeneratorError("source already contains 'magic_lifestyle'; is it a generated file?")
    lines = text.split("\n")
    anchors = [i for i, l in enumerate(lines) if ANCHOR in l]
    if len(anchors) != EXPECTED_ANCHORS:
        raise GeneratorError(
            f"expected {EXPECTED_ANCHORS} wanderer_lifestyle anchors, found {len(anchors)}; did a CK3 patch change the lifestyle window?"
        )
    for anchor in reversed(anchors):
        try:
            start = next(i for i in range(anchor, -1, -1) if lines[i].rstrip().endswith("= {"))
        except StopIteration:
            raise GeneratorError(f"no block opens before the anchor on line {anchor + 1}")
        depth = 0
        for end in range(start, len(lines)):
            depth += brace_delta(lines[end])
            if depth == 0:
                break
        else:
            raise GeneratorError(f"unbalanced braces in the block at line {start + 1}")
        if end < anchor:
            raise GeneratorError(f"anchor on line {anchor + 1} is not inside the block that precedes it")
        indent = lines[start][: len(lines[start]) - len(lines[start].lstrip("\t"))]
        lines[end + 1:end + 1] = [""] + magic_copy(lines[start:end + 1], indent)
    return "\n".join(lines)


def build(raw: bytes) -> bytes:
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    crlf = "\r\n" in text
    text = insert_magic(text.replace("\r\n", "\n"))
    header = (
        f"{HEADER_MARKER}: generated by tools/build_lifestyle_override.py from {REL_PATH.as_posix()}.\n"
        f"{HEADER_MARKER}: do not edit by hand; edit the script and rerun it.\n"
    )
    text = header + text
    if crlf:
        text = text.replace("\n", "\r\n")
    return (b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8")


def find_source(anbennar: Path, game: Path) -> Path:
    for root in (anbennar, game):
        path = root / REL_PATH
        if path.is_file():
            return path
    raise GeneratorError(f"no {REL_PATH.as_posix()} in {anbennar} or {game}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--anbennar", type=Path, default=DEFAULT_ANBENNAR)
    parser.add_argument("--game", type=Path, default=DEFAULT_GAME)
    args = parser.parse_args()
    try:
        src = find_source(args.anbennar, args.game)
        data = build(src.read_bytes())
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    out = SUBMOD / REL_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    print(f"wrote {out} (from {src})")


if __name__ == "__main__":
    main()
