"""Generate the great-project monument buildings, province history and localization, region by region.

Source: tools/data/monuments/<region>.py (monument data) and translation.py (icons). Rerun after editing them:

    python -I tools/build_monuments.py [--region cannor|dwarovar]   (default: every region)

Building levels whose key Anbennar does not define are written to aov_monuments_<region>.txt. Levels Anbennar does
define are re-emitted, with the EU4 tier lines inserted, in zz_aov_monument_overrides_<region>.txt (single-object
overrides that load after Anbennar); they copy Anbennar's current definition, so rerun after an Anbennar update.
The new upper levels of a chain that starts with an Anbennar building are copies of the chain's top Anbennar level
(an upgrade replaces the previous level's effects in CK3), with that EU4 tier merged in the same way.

The data is validated first (placement, names, icons, modifier keys, an effect on every level); any problem raises
GeneratorError naming the monument. The illustration custom loc is shared by every region, so it is always
built from all of them (render_shared), which also checks that no province holds monuments from two regions.
"""

import argparse
import importlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # python -I does not add the script's folder
from data.monuments import translation  # noqa: E402
import eu4_monuments  # noqa: E402
from build_spells import read_bgra, write_bgra  # noqa: E402

SUBMOD = Path(__file__).resolve().parent.parent
ANBENNAR_CK3 = SUBMOD.parent / "anbennar-ck3-dev-master"
GAME = Path("C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")
HEADER = "# Anbennar Overhaul: generated by tools/build_monuments.py from tools/data/monuments/; do not edit by hand.\n"
ROMAN = {1: "", 2: " (II)", 3: " (III)"}
BLOCKS = ("province_modifier", "county_modifier", "character_modifier")
DROPPED_NOTE = " Some effects of the original Europa Universalis IV project have no Crusader Kings III equivalent and are omitted."


NL = "\n"
ART_DIR = "gfx/interface/illustrations/aov_monuments"
REGIONS = ("cannor", "dwarovar")
SHARED = "common/customizable_localization/aov_monument_illustration.txt"


# ai_value of every generated level: vanilla's special-building pattern (00_special_buildings.txt), base 100, the
# category's preference modifier, and no special building while the holding has a free building slot.
AI_PREFERENCE = {
    "fortress": "culture_likely_to_fortify_modifier",
    "castle": "culture_likely_to_fortify_modifier",
    "temple": "ai_pious_building_preference_modifier",
}
AI_GUARD = ["\t\tmodifier = { # Fill all building slots before going for special buildings", "\t\t\tfactor = 0",
            "\t\t\tfree_building_slots > 0", "\t\t}"]


class GeneratorError(Exception):
    pass


def anbennar_keys(root: Path = ANBENNAR_CK3) -> set:
    keys = set()
    for f in (Path(root) / "common" / "buildings").glob("*.txt"):
        keys.update(re.findall(r"^([A-Za-z0-9_]+)\s*=\s*\{", f.read_text(encoding="utf-8-sig"), re.M))
    return keys


def strip_comment(line: str) -> str:
    return line.split("#", 1)[0]


def anbennar_definition(root, key: str) -> str:
    """Anbennar's text for building `key`, from `key = {` to the matching `}` (raises GeneratorError if absent)."""
    head = re.compile(rf"^{re.escape(key)}\s*=\s*\{{")
    for f in sorted((Path(root) / "common" / "buildings").glob("*.txt")):
        lines = f.read_text(encoding="utf-8-sig").splitlines()
        for i, line in enumerate(lines):
            if head.match(line):
                depth = 0
                for j in range(i, len(lines)):
                    code = strip_comment(lines[j])
                    depth += code.count("{") - code.count("}")
                    if depth <= 0:
                        return NL.join(lines[i:j + 1]) + NL
                raise GeneratorError(f"unbalanced braces in Anbennar building {key}")
    raise GeneratorError(f"Anbennar building {key} not found in common/buildings")


def depths_of(lines: list) -> list:
    """Brace depth before each line."""
    out, depth = [], 0
    for line in lines:
        out.append(depth)
        code = strip_comment(line)
        depth += code.count("{") - code.count("}")
    return out


def find_block(lines: list, name: str):
    """(start, closing-brace) line indexes of the depth-1 block `name = {`, or None."""
    depths = depths_of(lines)
    for i, line in enumerate(lines):
        if depths[i] == 1 and re.match(rf"\t{name}\s*=\s*\{{", line):
            if i + 1 < len(depths) and depths[i + 1] == 1:
                raise GeneratorError(f"{name} opens and closes on one line: {line.strip()}")
            for j in range(i + 1, len(lines)):
                if depths[j] == 1:
                    return i, j - 1  # j is the line after the closing brace
    return None


def insert_point(lines: list) -> int:
    """Index of the depth-1 `type = ` line (new blocks go before it); falls back to the closing brace."""
    depths = depths_of(lines)
    for i, line in enumerate(lines):
        if depths[i] == 1 and re.match(r"\ttype\s*=", line):
            return i
    return len(lines) - 1


NUMBER = re.compile(r"-?\d+(\.\d+)?")
# Highest fort_level a merged level may reach unless Anbennar's own value is higher: vanilla's strongest special
# building (alamut_castle_02) has 8. The rest goes to SURPLUS_KEY on the same level.
FORT_LEVEL_CAP = 8
SURPLUS_KEY = "defender_holding_advantage"


def parse_values(text: str) -> dict:
    """name -> raw right-hand side for `name = value` and `@name = value` lines of a script_values file."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"@?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^#\s][^#]*?)\s*(#.*)?$", line)
        if m:
            out.setdefault(m.group(1), m.group(2))
    return out


def load_values(root: Path = ANBENNAR_CK3) -> dict:
    """Building values; Anbennar's 00_building_values.txt first, the game's as a fallback for missing names."""
    out = {}
    for base in (Path(root), GAME):
        f = base / "common" / "script_values" / "00_building_values.txt"
        if f.is_file():
            for k, v in parse_values(f.read_text(encoding="utf-8-sig")).items():
                out.setdefault(k, v)
    return out


def resolve(raw: str, values: dict, seen=()) -> float:
    """Numeric value of a script value (number, `name`, `@name`, `@[expression]`); ValueError when it cannot be resolved."""
    raw = raw.strip()
    if NUMBER.fullmatch(raw):
        return float(raw)
    if raw.startswith("@["):
        if not raw.endswith("]"):
            raise ValueError(f"bad expression {raw}")
        raw = raw[2:-1]
    elif raw.startswith("@"):
        raw = raw[1:]
    if not re.fullmatch(r"[A-Za-z0-9_.+\-*/() ]+", raw):
        raise ValueError(f"not a plain expression: {raw}")

    def name(m):
        word = m.group(0)
        if NUMBER.fullmatch(word):
            return word
        if word in seen:
            raise ValueError(f"circular value {word}")
        if word not in values:
            raise ValueError(f"unknown name {word}")
        return f"({resolve(values[word], values, seen + (word,))!r})"

    expr = re.sub(r"[A-Za-z_][A-Za-z0-9_]*|\d+(\.\d+)?", name, raw)
    try:
        return float(eval(expr, {"__builtins__": {}}, {}))  # only digits and + - * / ( ) remain
    except Exception as e:
        raise ValueError(f"cannot evaluate {raw}: {e}")


def merge_modifier(lines: list, name: str, k: str, v, values: dict, note: str, warnings: list, key: str):
    """If the modifier block already has `k`, sum into that line (True) or leave it with a comment (also True); else False.
    A summed fort_level is capped at max(FORT_LEVEL_CAP, Anbennar's value); the surplus goes to
    defender_holding_advantage in the same block (Anbennar's fort level and advantage tiers have the same numbers)."""
    start, end = find_block(lines, name)
    for i in range(start + 1, end):
        m = re.match(rf"(\s*){re.escape(k)}\s*=\s*([^#\s]+)", lines[i])
        if m:
            indent, old = m.group(1), m.group(2)
            try:
                base = resolve(old, values)
            except ValueError as e:
                msg = f"{k} {old} not added ({e})"
                warnings.append(f"{key} tier {note.rsplit(' ', 1)[1]}: {msg}")
                lines[i + 1:i + 1] = [f"{indent}{note} {msg}"]
                return True
            total, surplus, capped = base + float(v), 0.0, ""
            if k == "fort_level" and total > max(FORT_LEVEL_CAP, base):
                surplus, total = total - max(FORT_LEVEL_CAP, base), max(FORT_LEVEL_CAP, base)
                capped = f", capped at {num(total)}; {num(surplus)} moved to {SURPLUS_KEY}"
            lines[i:i + 1] = [f"{indent}{note} (+{num(v)} to {old} = {num(base)}{capped})",
                              f"{indent}{k} = {num(total)}"]
            if surplus and not merge_modifier(lines, name, SURPLUS_KEY, surplus, values, note, warnings, key):
                end = find_block(lines, name)[1]
                lines[end:end] = [f"{indent}{note} (fort_level above {num(total)})", f"{indent}{SURPLUS_KEY} = {num(surplus)}"]
            return True
    return False


def override(base_text: str, key: str, tier: dict, next_key, n: int, values=None, warnings=None) -> str:
    """Anbennar's definition of `key` with the EU4 tier `n` effects inserted and next_building set."""
    values = values or {}
    warnings = [] if warnings is None else warnings
    lines = base_text.rstrip(NL).split(NL)
    lines[0] = f"{key} = {{"  # drop any trailing comment on the opening line
    note = f"# Anbennar Overhaul: EU4 tier {n}"
    for name in BLOCKS:
        mods = tier[name]
        if not mods:
            continue
        found = find_block(lines, name)
        if found:
            noted = False
            for k, v in mods.items():
                if not merge_modifier(lines, name, k, v, values, note, warnings, key):
                    end = find_block(lines, name)[1]
                    lines[end:end] = ([] if noted else [f"\t\t{note}"]) + [f"\t\t{k} = {num(v)}"]
                    noted = True
        else:
            at = insert_point(lines)
            lines[at:at] = [f"\t{name} = {{", f"\t\t{note}"] + [f"\t\t{k} = {num(v)}" for k, v in mods.items()] + ["\t}", ""]
    if tier["on_complete"].strip():
        found = find_block(lines, "on_complete")
        body = [f"\t\t{note}", f"\t\t{tier['on_complete'].strip()}"]
        if found:
            lines[found[1]:found[1]] = body
        else:
            at = insert_point(lines)
            lines[at:at] = ["\ton_complete = {"] + body + ["\t}", ""]
    if next_key:
        depths = depths_of(lines)
        line = f"\tnext_building = {next_key} {note}"
        for i, l in enumerate(lines):
            if depths[i] == 1 and re.match(r"\tnext_building\s*=", l):
                lines[i] = line
                break
        else:
            at = insert_point(lines)
            lines[at:at] = [line, ""]
    return NL.join(lines) + NL


def load_monuments(region: str) -> list:
    return importlib.import_module(f"data.monuments.{region}").MONUMENTS


def num(v) -> str:
    s = f"{float(v):.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("", "-0") else s


def ai_value(category: str) -> list:
    out = ["\tai_value = {", "\t\tbase = 100"]
    if category in AI_PREFERENCE:
        out.append(f"\t\t{AI_PREFERENCE[category]} = yes")
    return out + AI_GUARD + ["\t}"]


def gate_body(m: dict) -> list:
    """The EU4 culture gate in the holder's scope, wrapped in its custom tooltip (indented for a depth-1 block)."""
    return ["\t\tscope:holder = {", "\t\t\tcustom_tooltip = {", f"\t\t\t\ttext = aov_monument_{m['eu4_key']}_gate",
            f"\t\t\t\t{m['gate']}", "\t\t\t}", "\t\t}"]


def building(m: dict, level: int, key: str, next_key) -> str:
    tier = m["tiers"][level - 1]
    icon = translation.ICONS[m["category"]]
    out = [f"{key} = {{", f"\tconstruction_time = {tier['days']}", "",
           f'\ttype_icon = "{icon}"', "",
           "\tcan_construct_potential = {", "\t\tbuilding_requirement_tribal = no", "\t}", ""]
    if m["gate"]:
        for name in ("can_construct", "is_enabled"):
            out += [f"\t{name} = {{"] + gate_body(m) + ["\t}", ""]
    out += [f"\tcost_gold = {tier['cost']}", ""]
    for block in BLOCKS:
        mods = tier[block]
        if mods:
            out.append(f"\t{block} = {{")
            out += [f"\t\t{k} = {num(v)}" for k, v in mods.items()]
            out += ["\t}", ""]
    if tier["on_complete"].strip():
        out += ["\ton_complete = {", f"\t\t{tier['on_complete'].strip()}", "\t}", ""]
    if next_key:
        out += [f"\tnext_building = {next_key}", ""]
    out += ai_value(m["category"]) + ["", "\ttype = special", "}", ""]
    return "\n".join(out)


def chain_top(m: dict, known: set):
    """The chain's last Anbennar-keyed level, or None when the chain starts with a new building."""
    if m["levels"][0] not in known:
        return None
    return [k for k in m["levels"] if k in known][-1]


def set_line(lines: list, name: str, value, note: str) -> None:
    """Set the depth-1 `name = value` line, or add it after the opening line."""
    depths = depths_of(lines)
    line = f"\t{name} = {value} {note}"
    for i, l in enumerate(lines):
        if depths[i] == 1 and re.match(rf"\t{name}\s*=", l):
            lines[i] = line
            return
    lines[1:1] = [line]


UPGRADE_FIELDS = {"cost_gold": "cost", "construction_time": "days"}


def line_value(text: str, name: str):
    """Raw value of the depth-1 `name = value` line of a building definition, or None."""
    lines = text.split(NL)
    depths = depths_of(lines)
    for i, l in enumerate(lines):
        m = re.match(rf"\t{name}\s*=\s*([^#\s]+)", l)
        if depths[i] == 1 and m:
            return m.group(1)
    return None


def upgrade_value(m: dict, level: int, name: str, top: str, root, values: dict, warnings: list):
    """(raw, number, note) for `name` (cost_gold or construction_time) of new upper level `level`: the EU4 tier's
    value, but never below that of the level it upgrades from (an upgrade must not be cheaper or quicker than the
    building it replaces; Anbennar's citadels cost 2000 gold, the EU4 tiers 1000)."""
    tier_value = m["tiers"][level - 1][UPGRADE_FIELDS[name]]
    prev = m["levels"][level - 2]
    if level - 2 <= m["levels"].index(top):
        raw = line_value(anbennar_definition(root, prev), name)
        try:
            floor = (raw, resolve(raw, values)) if raw else None
        except ValueError as e:
            warnings.append(f"{m['levels'][level - 1]}: {name} of {prev} ({raw}) ignored ({e})")
            floor = None
    else:
        floor = upgrade_value(m, level - 1, name, top, root, values, warnings)[:2]
    if floor and floor[1] > float(tier_value):
        return floor[0], floor[1], f" ({num(tier_value)}), not below {prev}"
    return num(tier_value), float(tier_value), ""


def or_gate(lines: list, found: tuple, m: dict) -> None:
    """Add the EU4 gate to can_construct (`found` = its start and closing line) as one more alternative: inside the
    block's only statement when that is an OR, else as OR = { AND = { <Anbennar's triggers> } <gate> }."""
    start, end = found
    depths = depths_of(lines)
    gate = ["\t\t\t# Anbennar Overhaul: EU4 culture gate, an alternative to Anbennar's"] + ["\t" + l for l in gate_body(m)]
    heads = [i for i in range(start + 1, end) if depths[i] == 2 and strip_comment(lines[i]).strip()]
    if len(heads) == 1 and re.match(r"\t\tOR\s*=\s*\{\s*$", strip_comment(lines[heads[0]])):
        close = next(j for j in range(heads[0] + 1, end) if depths[j + 1] == 2)  # the OR's closing line
        lines[close:close] = gate
        return
    body = ["\t\t" + l if l.strip() else l for l in lines[start + 1:end]]
    lines[start + 1:end] = ["\t\tOR = {", "\t\t\tAND = {"] + body + ["\t\t\t}"] + gate + ["\t\t}"]


def upper_level(m: dict, level: int, key: str, next_key, top: str, root, values: dict, warnings: list) -> str:
    """A new upper level of an Anbennar chain: Anbennar's `top` level renamed, with EU4 tier `level` merged as in
    override(), cost and time from the tier (not below the previous level's), next_building set (removed at the end
    of the chain), the EU4 gate added to can_construct only (is_enabled would also switch off Anbennar's own
    effects; as an extra requirement, or as an alternative to Anbennar's when the monument's gate_mode is "or"),
    and vanilla's free-building-slot guard added to Anbennar's ai_value."""
    tier = m["tiers"][level - 1]
    note = f"# Anbennar Overhaul: EU4 tier {level}"
    lines = override(anbennar_definition(root, top), key, tier, next_key, level, values, warnings).rstrip(NL).split(NL)
    if not next_key:
        depths = depths_of(lines)
        lines = [l for i, l in enumerate(lines) if not (depths[i] == 1 and re.match(r"\tnext_building\s*=", l))]
    for name in UPGRADE_FIELDS:
        raw, _, why = upgrade_value(m, level, name, top, root, values, warnings)
        set_line(lines, name, raw, note + why)
    if m["gate"]:
        found = find_block(lines, "can_construct")
        if m.get("gate_mode") == "or":
            if not found:
                raise GeneratorError(f"monument {m['eu4_key']}: gate_mode or needs a can_construct on {top}")
            or_gate(lines, found, m)
        elif found:
            lines[found[1]:found[1]] = ["\t\t# Anbennar Overhaul: EU4 culture gate"] + gate_body(m)
        else:
            at = insert_point(lines)
            lines[at:at] = ["\tcan_construct = { # Anbennar Overhaul: EU4 culture gate"] + gate_body(m) + ["\t}", ""]
    found = find_block(lines, "ai_value")
    if found is None:
        at = insert_point(lines)
        lines[at:at] = ai_value(m["category"]) + [""]
    elif not any("free_building_slots" in l for l in lines[found[0]:found[1]]):
        lines[found[1]:found[1]] = AI_GUARD
    head = f"# Anbennar Overhaul: Anbennar's {top} with EU4 tier {level} merged in"
    return head + NL + NL.join(lines) + NL


def written_levels(monuments: list, known: set):
    """Yield (monument, level, key, next_key) for every level this generator writes."""
    for m in monuments:
        keys = m["levels"]
        for i, key in enumerate(keys):
            if key not in known:
                yield m, i + 1, key, (keys[i + 1] if i + 1 < len(keys) else None)


def buildings(monuments: list, known: set, root: Path = ANBENNAR_CK3) -> str:
    values, warnings, out = load_values(root), [], []
    for m, lvl, key, nxt in written_levels(monuments, known):
        top = chain_top(m, known)
        if top:
            out.append(upper_level(m, lvl, key, nxt, top, root, values, warnings))
        else:
            out.append(building(m, lvl, key, nxt))
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)
    return HEADER + "\n" + "\n".join(out)


def overrides(monuments: list, known: set, root: Path = ANBENNAR_CK3) -> str:
    out = [HEADER]
    values, warnings = load_values(root), []
    for m in monuments:
        keys = m["levels"]
        for i, key in enumerate(keys):
            if key in known:
                nxt = keys[i + 1] if i + 1 < len(keys) else None
                out.append(override(anbennar_definition(root, key), key, m["tiers"][i], nxt, i + 1, values, warnings))
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)
    return "\n".join(out)


def history(monuments: list, known: set) -> str:
    out = [HEADER]
    for m in monuments:
        first = m["levels"][0]
        if first in known:
            continue
        lines = [f"{m['province']} = {{", "\t1000.1.1 = {", f"\t\tspecial_building_slot = {first}"]
        if m["start_level"] == 1:
            lines.append(f"\t\tspecial_building = {first}")
        lines += ["\t}", "}", ""]
        out.append(NL.join(lines))
    return NL.join(out)


def q(text: str) -> str:
    return text.replace('"', "'")


def loc(monuments: list, known: set, root: Path = ANBENNAR_CK3) -> str:
    out = ["l_english:"]
    for m, level, key, _ in written_levels(monuments, known):
        name = m["name"] if m["levels"][0] == "castle_dameris_01" else m["name"] + ROMAN[level]
        desc = m["desc"] + (DROPPED_NOTE if m["tiers"][level - 1]["dropped"] else "")
        out.append(f' building_{key}: "{q(name)}"')
        out.append(f' building_{key}_desc: "{q(desc)}"')
    for m, level, key, _ in written_levels(monuments, known):  # tiger wants a type name for every level key
        out.append(f' building_type_{key}: "$building_{key}$"')
        out.append(f' building_type_{key}_desc: "$building_{key}_desc$"')
    anb_loc = NL.join(f.read_text(encoding="utf-8-sig") for f in (Path(root) / "localization" / "english").glob("*.yml"))
    for m in monuments:  # tiger wants a type description for overridden keys too; fill Anbennar's gaps
        for key in m["levels"]:
            if key in known and f" building_type_{key}_desc:" not in anb_loc:
                out.append(f' building_type_{key}_desc: "$building_{key}_desc$"')
    for m in monuments:
        if m["art"]:
            out.append(f' aov_monument_art_{m["eu4_key"]}: "{ART_DIR}/{m["eu4_key"]}.dds"')
    out.append(' aov_monument_art_none: ""')
    for m in monuments:
        if m["gate"]:
            out.append(f' aov_monument_{m["eu4_key"]}_gate: "{q("Built and used by: " + m["gate_desc"])}"')
    return "\n".join(out) + "\n"


def illustration(monuments: list) -> str:
    """Custom loc AovMonumentIllustration: the texture path of the painting for the province's monument, else empty."""
    out = [HEADER, "AovMonumentIllustration = {", "\ttype = province", ""]
    for m in monuments:
        if m["art"]:
            out += ["\ttext = {", "\t\ttrigger = {", f"\t\t\thas_building_or_higher = {m['levels'][0]}", "\t\t}",
                    f"\t\tlocalization_key = aov_monument_art_{m['eu4_key']}", "\t}", ""]
    out += ["\ttext = {", "\t\tfallback = yes", "\t\tlocalization_key = aov_monument_art_none", "\t}", "}", ""]
    return NL.join(out)


def render_art(region: str, roots=None) -> dict:
    """Published path -> uncompressed BGRA DDS of each monument's EU4 painting (EU4 size)."""
    roots = roots or eu4_monuments.EU4_ROOTS
    out = {}
    for m in load_monuments(region):
        if not m["art"]:
            continue
        src = eu4_monuments.art_file(roots, m["eu4_key"])
        if src is None:
            raise GeneratorError(f"EU4 painting for {m['eu4_key']} not found ({m['art']})")
        data = src.read_bytes()
        w, h, px = eu4_monuments.decode_dxt1(data) if data[84:88] == b"DXT1" else read_bgra(data)  # a few are already BGRA
        out[f"{ART_DIR}/{m['eu4_key']}.dds"] = write_bgra(w, h, bytes(px))
    return out


def hand_keys(region: str) -> set:
    """CK3 modifier keys the region's hand file sets in its tiers."""
    try:
        hand = importlib.import_module(f"data.monuments.{region}_hand").HAND
    except ModuleNotFoundError:
        return set()
    return {k for fields in hand.values() for tier in fields.get("tiers", [])
            for block in BLOCKS for k in (tier.get(block) or {})}


def validate(monuments: list, known: set, extra_keys=()) -> None:
    """Raise GeneratorError naming the monument for: no barony or province, a province used twice, an empty name or
    desc, a category without an icon, a modifier key that is no translation-table target (nor in `extra_keys`, the
    hand file's keys), or a level without any effect (no modifier and no on_complete). Levels of chains that start
    with an Anbennar building carry Anbennar's effects, so they need no EU4 effect of their own."""
    allowed = {row.ck3 for row in translation.MODIFIERS.values() if isinstance(row, translation.Row)} | set(extra_keys)
    seen = {}
    for m in monuments:
        key = m.get("eu4_key", "?")

        def fail(msg):
            raise GeneratorError(f"monument {key}: {msg}")

        if not m.get("barony") or m.get("province") is None:
            fail("no barony or province")
        if m["province"] in seen:
            fail(f"province {m['province']} already holds {seen[m['province']]}")
        seen[m["province"]] = key
        for field in ("name", "desc"):
            if not (m.get(field) or "").strip():
                fail(f"empty {field}")
        if m.get("category") not in translation.ICONS:
            fail(f"category {m.get('category')!r} has no icon in translation.ICONS")
        top = chain_top(m, known)
        for level, tier in enumerate(m["tiers"], 1):
            for block in BLOCKS:
                for k in tier[block]:
                    if k not in allowed:
                        fail(f"level {level} {block} key {k} is not a translation-table target or a hand key")
            if top is None and not (any(tier[b] for b in BLOCKS) or tier["on_complete"].strip()):
                fail(f"level {level} has no effect (no modifier and no on_complete)")


def render_all(region: str, root: Path = ANBENNAR_CK3) -> dict:
    """The region's own files. The overrides file only exists for a region that extends Anbennar levels."""
    monuments = load_monuments(region)
    known = anbennar_keys(root)
    validate(monuments, known, hand_keys(region))
    files = {
        f"common/buildings/aov_monuments_{region}.txt": buildings(monuments, known, root),
        f"history/provinces/aov_monuments_{region}.txt": history(monuments, known),
        f"localization/english/aov_monuments_{region}_l_english.yml": loc(monuments, known, root),
    }
    if any(level in known for m in monuments for level in m["levels"]):
        files[f"common/buildings/zz_aov_monument_overrides_{region}.txt"] = overrides(monuments, known, root)
    return files


def render_shared(regions=REGIONS) -> dict:
    """Files shared by every region: the illustration custom loc. Raises GeneratorError when one province holds
    monuments from two regions."""
    monuments, seen = [], {}
    for region in regions:
        for m in load_monuments(region):
            if m["province"] in seen:
                raise GeneratorError(f"monument {m['eu4_key']} ({region}): province {m['province']} already holds "
                                     f"{seen[m['province']]}")
            seen[m["province"]] = f"{m['eu4_key']} ({region})"
            monuments.append(m)
    return {SHARED: illustration(monuments)}


def write_all(files: dict, root: Path) -> None:
    for rel, text in files.items():
        out = Path(root) / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\xef\xbb\xbf" + text.replace("\r\n", "\n").encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--region", choices=REGIONS, help="one region (default: every region)")
    args = parser.parse_args()
    try:
        files, art = {}, {}
        for region in [args.region] if args.region else REGIONS:
            files.update(render_all(region))
            art.update(render_art(region))
        files.update(render_shared())
        write_all(files, SUBMOD)
        for rel, data in art.items():
            out = SUBMOD / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(data)
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    print(f"wrote {len(files)} files and {len(art)} paintings")


if __name__ == "__main__":
    main()
