"""Generate the per-spell magic files from tools/data/spells.py.

Every file written here repeats one block per spell, so it is generated rather than written by hand.
Rerun after editing tools/data/spells.py:

    python -I tools/build_spells.py [--eu4 PATH]

--eu4 is EU4 Anbennar's Workshop folder, used to copy the magic art.
"""

import argparse
import importlib.util
import re
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # python -I does not add the script's folder
from build_inventions import GeneratorError, dx10_bgra_to_legacy  # noqa: E402

SUBMOD = Path(__file__).resolve().parent.parent
DATA = SUBMOD / "tools" / "data" / "spells.py"
DEFAULT_EU4 = Path("C:/Program Files (x86)/Steam/steamapps/workshop/content/236850/1385440355")
EU4_MAGIC = Path("gfx/interface/custom_gui/magic")
ART_DIR = "gfx/interface/icons/aov_magic"
TAB_ICON = "gfx/interface/skinned/hud_maintab/aov_maintab_magic.dds"
HEADER = "# Anbennar Overhaul: generated by tools/build_spells.py from tools/data/spells.py; do not edit by hand.\n"

SCHOOLS = ("abjuration", "conjuration", "divination", "enchantment", "evocation", "illusion", "necromancy", "transmutation")
TYPES = ("self", "realm", "war", "targeted")
COSTS = (25, 50, 100, 200)
YEARS = (1, 2, 3, 5)
LEVEL_OF_SLOT = {1: 0, 2: 1, 3: 1, 4: 2, 5: 2, 6: 3}

# EU4 source (in EU4_MAGIC) -> published name (in ART_DIR)
ART = {f"magic_spell_icons_slot_{n}_60x60.dds": f"spell_slot_{n}.dds" for n in range(1, 7)}
ART.update({f"magic_{s}_icon.dds": f"school_{s}.dds" for s in SCHOOLS})
ART.update({
    "levels_strip_glow_1_7.dds": "levels_strip.dds",
    "magic_ui_spell_frames_64x76.dds": "spell_frames.dds",
    "magic_cast_spell_button.dds": "spell_plate.dds",
    "magic_bg.dds": "magic_bg.dds",
})
TAB_SOURCE = "magic_center_graphic.dds"


def load_spells(path: Path = DATA) -> list:
    spec = importlib.util.spec_from_file_location("aov_spells_data", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.SPELLS


def validate(spells: list) -> None:
    keys = [s["key"] for s in spells]
    if len(set(keys)) != len(keys):
        raise GeneratorError("duplicate spell keys")
    for s in spells:
        k = s["key"]
        if not re.fullmatch(r"[a-z0-9_]+", k):
            raise GeneratorError(f"{k}: bad key")
        if s["school"] not in SCHOOLS:
            raise GeneratorError(f"{k}: unknown school {s['school']}")
        if s["type"] not in TYPES:
            raise GeneratorError(f"{k}: unknown type {s['type']}")
        if s["level"] not in (0, 1, 2, 3):
            raise GeneratorError(f"{k}: bad level {s['level']}")
        if s["slot"] and LEVEL_OF_SLOT.get(s["slot"]) != s["level"]:
            raise GeneratorError(f"{k}: slot {s['slot']} does not match level {s['level']}")
        if s["type"] == "targeted" and not s["interaction"]:
            raise GeneratorError(f"{k}: targeted spell without interaction")
        if s["type"] != "targeted" and not (s["modifier"].strip() or s["effect"].strip()):
            raise GeneratorError(f"{k}: no modifier and no effect")
        if '"' in s["name"] + s["desc"] + s["flavour"]:
            raise GeneratorError(f"{k}: double quote in name, desc or flavour")


def read_bgra(data: bytes):
    """Width, height and BGRA pixels of an uncompressed 32-bit classic-header DDS."""
    if data[:4] != b"DDS ":
        raise GeneratorError("not a DDS")
    height, width = struct.unpack("<II", data[12:20])
    flags, fourcc, bits = struct.unpack("<I4sI", data[80:92])
    if not flags & 0x40 or bits != 32:
        raise GeneratorError("not an uncompressed 32-bit DDS")
    return width, height, data[128:128 + width * height * 4]


def write_bgra(width: int, height: int, pixels: bytes) -> bytes:
    """Classic A8R8G8B8 DDS (same header as dx10_bgra_to_legacy)."""
    head = bytearray(128)
    head[0:4] = b"DDS "
    struct.pack_into("<7I", head, 4, 124, 0x100F, height, width, width * 4, 0, 1)
    struct.pack_into("<8I", head, 76, 32, 0x41, 0, 32, 0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)
    struct.pack_into("<I", head, 108, 0x1000)
    return bytes(head) + pixels


def downscale(px: bytes, w: int, h: int, size: int) -> bytes:
    """Area-average BGRA pixels to size x size."""
    out = bytearray(size * size * 4)
    for oy in range(size):
        y0, y1 = oy * h // size, max(oy * h // size + 1, (oy + 1) * h // size)
        for ox in range(size):
            x0, x1 = ox * w // size, max(ox * w // size + 1, (ox + 1) * w // size)
            acc = [0, 0, 0, 0]
            n = 0
            for y in range(y0, y1):
                row = y * w * 4
                for x in range(x0, x1):
                    i = row + x * 4
                    for c in range(4):
                        acc[c] += px[i + c]
                    n += 1
            o = (oy * size + ox) * 4
            out[o:o + 4] = bytes(v // n for v in acc)
    return bytes(out)


def copy_art(eu4: Path, root: Path) -> None:
    src_dir = eu4 / EU4_MAGIC
    missing = [n for n in list(ART) + [TAB_SOURCE] if not (src_dir / n).is_file()]
    if missing:
        raise GeneratorError(f"EU4 magic art not found in {src_dir}: {', '.join(missing)}")
    dst = root / ART_DIR
    dst.mkdir(parents=True, exist_ok=True)
    for src, name in ART.items():
        data = (src_dir / src).read_bytes()
        if data[84:88] == b"DX10":
            data = dx10_bgra_to_legacy(data)
        (dst / name).write_bytes(data)
    w, h, px = read_bgra((src_dir / TAB_SOURCE).read_bytes())
    tab = root / TAB_ICON
    tab.parent.mkdir(parents=True, exist_ok=True)
    tab.write_bytes(write_bgra(95, 95, downscale(px, w, h, 95)))


def of_school(spells: list, school: str) -> list:
    return [s for s in spells if s["school"] == school]


def lasting(s) -> bool:
    return bool(s["modifier"].strip())


def window_spell(s) -> bool:
    return s["type"] != "targeted"


def body(text: str, depth: int) -> str:
    pad = "\t" * depth
    return "\n".join(pad + line.strip() for line in text.splitlines() if line.strip())


def modifiers(spells: list) -> str:
    out = [HEADER]
    for s in spells:
        if lasting(s):
            out.append(f"aov_spell_{s['key']} = {{\n\ticon = learning_positive\n{body(s['modifier'], 1)}\n}}\n")
    return "\n".join(out)


def triggers(spells: list) -> str:
    out = [HEADER, "# Character scope (the caster).\n"]
    for s in spells:
        k, c, lvl = s["key"], s["school"], s["level"]
        cost = COSTS[lvl]
        war = (f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_WAR\n\t\tis_at_war = yes\n\t}}\n" if s["type"] == "war" else "")
        out.append(
            f"aov_spell_{k}_known = {{\n\taov_school_level_at_least = {{ SCHOOL = {c} LEVEL = {lvl} }}\n}}\n"
            f"aov_spell_{k}_ready = {{\n\tNOT = {{ has_variable = aov_spell_{k}_cd }}\n}}\n"
            f"aov_spell_{k}_castable = {{\n"
            f"\taov_is_mage = yes\n"
            f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_{c.upper()}_{lvl}\n\t\taov_spell_{k}_known = yes\n\t}}\n"
            f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_READY\n\t\taov_spell_{k}_ready = yes\n\t}}\n"
            f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_MANA_{cost}\n\t\taov_mana >= {cost}\n\t}}\n"
            f"{war}}}\n"
        )
    return "\n".join(out)


def effects(spells: list) -> str:
    out = [HEADER, "# Character scope (the caster); targeted spells have the target as scope:recipient.\n"]
    for s in spells:
        k, c, lvl = s["key"], s["school"], s["level"]
        cost, years = COSTS[lvl], YEARS[lvl]
        lines = [
            f"\tcustom_tooltip = AOV_SPELL_COST_{cost}",
            f"\thidden_effect = {{",
            f"\t\taov_mana_change = {{ AMOUNT = -{cost} }}",
            f"\t\taov_school_add_progress = {{ SCHOOL = {c} AMOUNT = {cost} }}",
            f"\t\tset_variable = {{ name = aov_spell_{k}_cd years = {years} }}",
            f"\t}}",
        ]
        if lasting(s):
            lines.append(f"\tadd_character_modifier = {{ modifier = aov_spell_{k} years = {years} }}")
        if s["effect"].strip():
            lines.append(body(s["effect"], 1))
        if c == "necromancy":
            lines.append("\taov_dark_magic_roll = yes")
        out.append(f"aov_spell_{k}_cast = {{\n" + "\n".join(lines) + "\n}\n")
    return "\n".join(out)


def sguis(spells: list) -> str:
    out = [HEADER, "# Magic window (gui/aov_window_magic.gui, gui/aov_magic_generated.gui). Targeted spells are interactions.\n"]
    for s in spells:
        if window_spell(s):
            k = s["key"]
            out.append(f"aov_spell_{k}_sgui = {{\n\tscope = character\n\tis_valid = {{ aov_spell_{k}_castable = yes }}\n"
                       f"\teffect = {{ aov_spell_{k}_cast = yes }}\n}}\n")
    for c in SCHOOLS:
        out.append(f"aov_study_{c}_sgui = {{\n\tscope = character\n\tis_shown = {{ aov_is_studying = {{ SCHOOL = {c} }} }}\n"
                   f"\tis_valid = {{\n\t\taov_is_mage = yes\n\t\tcustom_tooltip = {{\n\t\t\ttext = AOV_STUDY_REQ_NOT_MASTERED\n"
                   f"\t\t\taov_school_{c}_level < 3\n\t\t}}\n\t}}\n\teffect = {{ aov_study_set = {{ SCHOOL = {c} }} }}\n}}\n")
    return "\n".join(out)


def interactions(spells: list) -> str:
    """Targeted spells without an Anbennar interaction. Magic cannot be refused: auto-accepted.
    AI does not use them (ai_will_do 0); it casts window spells (aov_magic_ai_quarterly)."""
    out = [HEADER]
    for s in spells:
        if s["type"] != "targeted" or s["interaction"] != f"aov_spell_{s['key']}_interaction":
            continue
        k = s["key"]
        out.append(
            f"aov_spell_{k}_interaction = {{\n"
            f"\tcategory = interaction_category_spells\n"
            f"\tcommon_interaction = no\n"
            f"\tdesc = aov_spell_{k}_interaction_desc\n\n"
            f"\tis_shown = {{\n\t\tscope:actor = {{ aov_is_mage = yes }}\n\t\tNOT = {{ scope:recipient = scope:actor }}\n\t}}\n\n"
            f"\tis_valid_showing_failures_only = {{\n"
            f"\t\tscope:actor = {{ aov_spell_{k}_castable = yes }}\n"
            f"\t\tscope:recipient = {{ aov_spell_target_allowed = yes }}\n\t}}\n\n"
            f"\ton_accept = {{\n\t\tscope:actor = {{ aov_spell_{k}_cast = yes }}\n\t}}\n\n"
            f"\tauto_accept = yes\n\n"
            f"\tai_will_do = {{\n\t\tbase = 0\n\t}}\n"
            f"}}\n"
        )
    return "\n".join(out)


def loc(spells: list) -> str:
    out = ["l_english:", " # " + HEADER.strip("# \n")]
    for s in spells:
        k = s["key"]
        out.append(f' aov_spell_{k}: "{s["name"]}"')
        out.append(f' aov_spell_{k}_desc: "{s["desc"]}"')
        out.append(f' aov_spell_{k}_flavour: "#F {s["flavour"]}#!"')
        if s["interaction"] == f"aov_spell_{k}_interaction":
            out.append(f' aov_spell_{k}_interaction: "Cast {s["name"]}"')
            out.append(f' aov_spell_{k}_interaction_desc: "{s["desc"]}"')
    out.append("")
    for c in SCHOOLS:
        for lvl in range(4):
            out.append(f' AOV_SPELL_REQ_{c.upper()}_{lvl}: "Knows $AOV_SCHOOL_{c.upper()}$ at level {lvl} or higher"')
    for cost in COSTS:
        out.append(f' AOV_SPELL_REQ_MANA_{cost}: "Has at least #V {cost}#! mana"')
        out.append(f' AOV_SPELL_COST_{cost}: "Costs #V {cost}#! mana"')
    return "\n".join(out) + "\n"


def render_all(spells: list) -> dict:
    return {
        "common/modifiers/aov_spell_modifiers.txt": modifiers(spells),
        "common/scripted_triggers/aov_spell_triggers.txt": triggers(spells),
        "common/scripted_effects/aov_spell_effects.txt": effects(spells),
        "common/scripted_guis/aov_spell_sgui.txt": sguis(spells),
        "common/character_interactions/aov_spell_interactions.txt": interactions(spells),
        "localization/english/aov_spells_l_english.yml": loc(spells),
    }


def write_all(files: dict, root: Path) -> None:
    for rel, text in files.items():
        out = root / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\xef\xbb\xbf" + text.replace("\r\n", "\n").encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--eu4", type=Path, default=DEFAULT_EU4)
    args = parser.parse_args()
    try:
        spells = load_spells()
        validate(spells)
        files = render_all(spells)
        write_all(files, SUBMOD)
        copy_art(args.eu4, SUBMOD)
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    print(f"wrote {len(files)} files for {len(spells)} spells; copied {len(ART) + 1} art files")


if __name__ == "__main__":
    main()
