"""Generate the per-spell magic files from tools/data/spells.py.

Every file written here repeats one block per spell, so it is generated rather than written by hand.
Rerun after editing tools/data/spells.py:

    python -I tools/build_spells.py [--eu4 PATH]

--eu4 is EU4 Anbennar's Workshop folder, used to copy the magic art.
"""

import argparse
import importlib.util
import re
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # python -I does not add the script's folder
from build_inventions import GeneratorError, dx10_bgra_to_legacy  # noqa: E402

SUBMOD = Path(__file__).resolve().parent.parent
DATA = SUBMOD / "tools" / "data" / "spells.py"
DEFAULT_EU4 = Path("C:/Program Files (x86)/Steam/steamapps/workshop/content/236850/1385440355")
EU4_MAGIC = Path("gfx/interface/custom_gui/magic")
ART_DIR = "gfx/interface/icons/aov_magic"
TAB_ICON = "gfx/interface/skinned/hud_maintab/aov_maintab_magic.dds"
HEADER = "# Anbennar Overhaul: generated by tools/build_spells.py from tools/data/spells.py; do not edit by hand.\n"

SCHOOLS = ("abjuration", "conjuration", "divination", "enchantment", "evocation", "illusion", "necromancy", "transmutation")
TYPES = ("self", "realm", "war", "targeted")
COSTS = (25, 50, 100, 200)
YEARS = (1, 2, 3, 5)
LEVEL_OF_SLOT = {1: 0, 2: 1, 3: 1, 4: 2, 5: 2, 6: 3}

# EU4 source (in EU4_MAGIC) -> published name (in ART_DIR)
ART = {f"magic_spell_icons_slot_{n}_60x60.dds": f"spell_slot_{n}.dds" for n in range(1, 7)}
ART.update({f"magic_{s}_icon.dds": f"school_{s}.dds" for s in SCHOOLS})
ART.update({
    "levels_strip_glow_1_7.dds": "levels_strip.dds",
    "magic_ui_spell_frames_64x76.dds": "spell_frames.dds",
    "magic_cast_spell_button.dds": "spell_plate.dds",
    "magic_bg.dds": "magic_bg.dds",
})
TAB_SOURCE = "magic_center_graphic.dds"


def load_spells(path: Path = DATA) -> list:
    spec = importlib.util.spec_from_file_location("aov_spells_data", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.SPELLS


def validate(spells: list) -> None:
    keys = [s["key"] for s in spells]
    if len(set(keys)) != len(keys):
        raise GeneratorError("duplicate spell keys")
    for s in spells:
        k = s["key"]
        if not re.fullmatch(r"[a-z0-9_]+", k):
            raise GeneratorError(f"{k}: bad key")
        if s["school"] not in SCHOOLS:
            raise GeneratorError(f"{k}: unknown school {s['school']}")
        if s["type"] not in TYPES:
            raise GeneratorError(f"{k}: unknown type {s['type']}")
        if s["level"] not in (0, 1, 2, 3):
            raise GeneratorError(f"{k}: bad level {s['level']}")
        if LEVEL_OF_SLOT.get(s["slot"]) != s["level"]:
            raise GeneratorError(f"{k}: slot {s['slot']} does not match level {s['level']}")
        if s["scales_duration"] and not (s["modifier"].strip() or k == "summon_elementals"):
            raise GeneratorError(f"{k}: scales_duration without a lasting effect")
        if s["type"] == "targeted" and not s["interaction"]:
            raise GeneratorError(f"{k}: targeted spell without interaction")
        if s["type"] != "targeted" and not (s["modifier"].strip() or s["effect"].strip()):
            raise GeneratorError(f"{k}: no modifier and no effect")
        if '"' in s["name"] + s["desc"] + s["flavour"]:
            raise GeneratorError(f"{k}: double quote in name, desc or flavour")


def read_bgra(data: bytes):
    """Width, height and BGRA pixels of an uncompressed 32-bit classic-header DDS."""
    if data[:4] != b"DDS ":
        raise GeneratorError("not a DDS")
    height, width = struct.unpack("<II", data[12:20])
    flags, fourcc, bits = struct.unpack("<I4sI", data[80:92])
    if not flags & 0x40 or bits != 32:
        raise GeneratorError("not an uncompressed 32-bit DDS")
    return width, height, data[128:128 + width * height * 4]


def write_bgra(width: int, height: int, pixels: bytes) -> bytes:
    """Classic A8R8G8B8 DDS (same header as dx10_bgra_to_legacy)."""
    head = bytearray(128)
    head[0:4] = b"DDS "
    struct.pack_into("<7I", head, 4, 124, 0x100F, height, width, width * 4, 0, 1)
    struct.pack_into("<8I", head, 76, 32, 0x41, 0, 32, 0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)
    struct.pack_into("<I", head, 108, 0x1000)
    return bytes(head) + pixels


# The hands-and-flame emblem sits inside the school ring of magic_center_graphic.dds; the ring's inner edge is
# ~52 px from the centre. EU4's standalone copies of the emblem are 32 px at most, too small for the tab.
EMBLEM_RADIUS = 46


def tab_emblem(px: bytes, w: int, h: int, size: int) -> bytes:
    """Only the emblem from the middle of the school wheel: pixels beyond EMBLEM_RADIUS from the centre are
    cleared, and the rest is cropped to a square around them (2 px margin) and resized to size x size."""
    from build_magic_lifestyle_art import resize  # imports this module, so not at the top
    cx, cy = w / 2, h / 2
    kept = bytearray(w * h * 4)
    xs, ys = [], []
    for y in range(h):
        for x in range(w):
            i = (y * w + x) * 4
            if px[i + 3] and (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2 <= EMBLEM_RADIUS ** 2:
                kept[i:i + 4] = px[i:i + 4]
                xs.append(x)
                ys.append(y)
    if not xs:
        raise GeneratorError(f"no emblem within {EMBLEM_RADIUS} px of the centre of {TAB_SOURCE}")
    side = max(max(xs) - min(xs), max(ys) - min(ys)) + 1 + 4
    x0 = (min(xs) + max(xs) + 1 - side) // 2
    y0 = (min(ys) + max(ys) + 1 - side) // 2
    crop = bytearray(side * side * 4)
    for y in range(side):
        for x in range(side):
            sx, sy = x0 + x, y0 + y
            if 0 <= sx < w and 0 <= sy < h:
                crop[(y * side + x) * 4:(y * side + x) * 4 + 4] = kept[(sy * w + sx) * 4:(sy * w + sx) * 4 + 4]
    return resize(bytes(crop), side, side, size, size)


def copy_art(eu4: Path, root: Path) -> None:
    src_dir = eu4 / EU4_MAGIC
    missing = [n for n in list(ART) + [TAB_SOURCE] if not (src_dir / n).is_file()]
    if missing:
        raise GeneratorError(f"EU4 magic art not found in {src_dir}: {', '.join(missing)}")
    dst = root / ART_DIR
    dst.mkdir(parents=True, exist_ok=True)
    for src, name in ART.items():
        data = (src_dir / src).read_bytes()
        if data[84:88] == b"DX10":
            data = dx10_bgra_to_legacy(data)
        (dst / name).write_bytes(data)
    w, h, px = read_bgra((src_dir / TAB_SOURCE).read_bytes())
    tab = root / TAB_ICON
    tab.parent.mkdir(parents=True, exist_ok=True)
    tab.write_bytes(write_bgra(95, 95, tab_emblem(px, w, h, 95)))


def of_school(spells: list, school: str) -> list:
    return [s for s in spells if s["school"] == school]


def lasting(s) -> bool:
    return bool(s["modifier"].strip())


def window_spell(s) -> bool:
    return s["type"] != "targeted"


def body(text: str, depth: int) -> str:
    pad = "\t" * depth
    return "\n".join(pad + line.strip() for line in text.splitlines() if line.strip())


def modifiers(spells: list) -> str:
    out = [HEADER]
    for s in spells:
        if lasting(s):
            out.append(f"aov_spell_{s['key']} = {{\n\ticon = learning_positive\n{body(s['modifier'], 1)}\n}}\n")
    return "\n".join(out)


def values(spells: list) -> str:
    """Per-spell cost (mana) and duration (years) as script values, read through the caster's bonus layer."""
    out = [HEADER, "# Character scope (the caster). Cost cuts and duration multipliers: aov_magic_lifestyle_values.txt\n"]
    for s in spells:
        k, c, lvl = s["key"], s["school"], s["level"]
        extra = f"\tsubtract = aov_cost_cut_{s['type']}\n" if s["type"] in ("war", "targeted") else ""
        mult = f"\tmultiply = aov_years_mult_{c}\n" if s["scales_duration"] else ""
        out.append(
            f"aov_spell_{k}_cost = {{\n\tvalue = 1\n\tsubtract = aov_cost_cut_{c}\n{extra}"
            f"\tmin = 0.5\n\tmultiply = {COSTS[lvl]}\n\tadd = 0.5\n\tfloor = yes\n}}\n"
            f"aov_spell_{k}_years = {{\n\tvalue = {YEARS[lvl]}\n{mult}\tadd = 0.5\n\tfloor = yes\n}}\n"
        )
    return "\n".join(out)


def triggers(spells: list) -> str:
    out = [HEADER, "# Character scope (the caster).\n"]
    for s in spells:
        k, c, lvl = s["key"], s["school"], s["level"]
        war = (f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_WAR\n\t\tis_at_war = yes\n\t}}\n" if s["type"] == "war" else "")
        out.append(
            f"aov_spell_{k}_known = {{\n\taov_school_level_at_least = {{ SCHOOL = {c} LEVEL = {lvl} }}\n}}\n"
            f"aov_spell_{k}_ready = {{\n\tNOT = {{ has_variable = aov_spell_{k}_cd }}\n}}\n"
            f"aov_spell_{k}_castable = {{\n"
            f"\taov_is_mage = yes\n"
            f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_{c.upper()}_{lvl}\n\t\taov_spell_{k}_known = yes\n\t}}\n"
            f"\tcustom_tooltip = {{\n\t\ttext = AOV_SPELL_REQ_READY\n\t\taov_spell_{k}_ready = yes\n\t}}\n"
            f"\tcustom_tooltip = {{\n\t\ttext = aov_spell_{k}_req_mana\n\t\taov_mana >= aov_spell_{k}_cost\n\t}}\n"
            f"{war}}}\n"
        )
    castable = "\n".join(f"\t\taov_spell_{s['key']}_castable = yes" for s in spells if window_spell(s))
    out.append(f"# AI: some window spell can be cast\naov_magic_ai_any_castable = {{\n\tOR = {{\n{castable}\n\t}}\n}}\n")
    return "\n".join(out)


def effects(spells: list) -> str:
    out = [HEADER, "# Character scope (the caster); targeted spells have the target as scope:recipient.\n"]
    for s in spells:
        k, c, lvl = s["key"], s["school"], s["level"]
        base = COSTS[lvl]
        lines = [
            f"\tcustom_tooltip = aov_spell_{k}_cost_tt",
            f"\thidden_effect = {{",
            f"\t\taov_mana_spend = {{ AMOUNT = aov_spell_{k}_cost }}",
            f"\t\taov_school_add_progress = {{ SCHOOL = {c} AMOUNT = {base} }}",
            f"\t\tadd_magic_lifestyle_xp = {base}",
            f"\t\tset_variable = {{ name = aov_spell_{k}_cd years = aov_spell_{k}_years }}",
            f"\t}}",
        ]
        if lasting(s):
            lines.append(f"\tadd_character_modifier = {{ modifier = aov_spell_{k} years = aov_spell_{k}_years }}")
        if s["effect"].strip():
            lines.append(body(s["effect"], 1))
        if c == "necromancy":
            lines.append("\taov_dark_magic_roll = yes")
        out.append(f"aov_spell_{k}_cast = {{\n" + "\n".join(lines) + "\n}\n")
    options = "\n".join(
        # The AI keeps clear of Forbidden Magic Practitioner: no Necromancy where magic is illegal or shunned
        f"\t\t{30 if s['type'] == 'war' else 10} = {{\n\t\t\ttrigger = {{ "
        + ("NOT = { aov_dark_magic_risky = yes } " if s["school"] == "necromancy" else "")
        + f"aov_spell_{s['key']}_castable = yes }}\n"
        f"\t\t\taov_spell_{s['key']}_cast = yes\n\t\t}}"
        for s in spells if window_spell(s))
    out.append("# AI (aov_magic_ai_quarterly): one castable window spell; war spells weigh more\n"
               f"aov_magic_ai_cast_random = {{\n\trandom_list = {{\n{options}\n\t}}\n}}\n")
    return "\n".join(out)


def sguis(spells: list) -> str:
    out = [HEADER, "# Magic window (gui/aov_window_magic.gui, gui/aov_magic_generated.gui). Targeted spells are interactions.\n"]
    for s in spells:
        if window_spell(s):
            k = s["key"]
            out.append(f"aov_spell_{k}_sgui = {{\n\tscope = character\n\tis_valid = {{ aov_spell_{k}_castable = yes }}\n"
                       f"\teffect = {{ aov_spell_{k}_cast = yes }}\n}}\n")
    for c in SCHOOLS:
        out.append(f"aov_study_{c}_sgui = {{\n\tscope = character\n\tis_shown = {{ aov_is_studying = {{ SCHOOL = {c} }} }}\n"
                   f"\tis_valid = {{\n\t\taov_is_mage = yes\n\t\tcustom_tooltip = {{\n\t\t\ttext = AOV_STUDY_REQ_NOT_MASTERED\n"
                   f"\t\t\taov_school_{c}_level < 3\n\t\t}}\n\t}}\n\teffect = {{ aov_study_set = {{ SCHOOL = {c} }} }}\n}}\n")
    return "\n".join(out)


def interactions(spells: list) -> str:
    """Targeted spells without an Anbennar interaction. Magic cannot be refused: auto-accepted.
    AI does not use them (ai_will_do 0); it casts window spells (aov_magic_ai_quarterly)."""
    out = [HEADER]
    for s in spells:
        if s["type"] != "targeted" or s["interaction"] != f"aov_spell_{s['key']}_interaction":
            continue
        k = s["key"]
        out.append(
            f"aov_spell_{k}_interaction = {{\n"
            f"\tcategory = interaction_category_spells\n"
            f"\tcommon_interaction = no\n"
            f"\tdesc = aov_spell_{k}_interaction_desc\n\n"
            f"\tis_shown = {{\n\t\tscope:actor = {{ aov_is_mage = yes }}\n\t\tNOT = {{ scope:recipient = scope:actor }}\n\t}}\n\n"
            f"\tis_valid_showing_failures_only = {{\n"
            f"\t\tscope:actor = {{ aov_spell_{k}_castable = yes }}\n"
            f"\t\tscope:recipient = {{ aov_spell_target_allowed = yes }}\n\t}}\n\n"
            f"\ton_accept = {{\n\t\tscope:actor = {{ aov_spell_{k}_cast = yes }}\n\t}}\n\n"
            f"\tauto_accept = yes\n\n"
            f"\tai_will_do = {{\n\t\tbase = 0\n\t}}\n"
            f"}}\n"
        )
    return "\n".join(out)


TYPE_LOC = {"self": "AOV_SPELL_TYPE_SELF", "realm": "AOV_SPELL_TYPE_REALM", "war": "AOV_SPELL_TYPE_WAR",
            "targeted": "AOV_SPELL_TYPE_TARGETED"}
TYPE_LABEL = {"self": "Self", "realm": "Realm", "war": "War", "targeted": "Targeted"}
ROOT = "GuiScope.SetRoot( GetPlayer.MakeScope ).End"


def sgref(name: str, call: str) -> str:
    return f"GetScriptedGui('{name}').{call}( {ROOT} )"


def text_at(x: int, y: int, text: str, max_width: int, fmt: str = "", visible: str = "") -> str:
    """One line of card text at a fixed position."""
    return ("\ttext_single = {\n"
            + (f'\t\tvisible = "{visible}"\n' if visible else "")
            + f'\t\tposition = {{ {x} {y} }}\n\t\ttext = "{text}"\n'
            + (f'\t\tdefault_format = "{fmt}"\n' if fmt else "")
            + f"\t\tmax_width = {max_width}\n\t\talign = left|nobaseline\n\t}}\n")


def card(s) -> str:
    """One spell, laid out like an EU4 spell slot: the 290x64 plate and the 64x76 level frame at the origin and the
    60x60 icon at +2,+2, all unscaled; the name on the plate's banner, the facts under it, the effect line below the
    plate, and the Cast button (or the portrait hint) right of the plate. 480 x 88."""
    k, c, lvl = s["key"], s["school"], s["level"]
    icon = (f'\ticon = {{\n\t\tposition = {{ 2 2 }}\n\t\tsize = {{ 60 60 }}\n'
            f'\t\ttexture = "{ART_DIR}/spell_slot_{s["slot"]}.dds"\n\t\tframesize = {{ 60 60 }}\n'
            f'\t\tframe = {SCHOOLS.index(c) + 1}\n\t}}\n')
    if window_spell(s):
        sg = f"aov_spell_{k}_sgui"
        action = (f"\tbutton_standard = {{\n\t\tparentanchor = right\n\t\tposition = {{ -6 16 }}\n"
                  f"\t\tsize = {{ 110 32 }}\n\t\ttext = \"AOV_SPELL_CAST\"\n"
                  f"\t\tenabled = \"[{sgref(sg, 'IsValid')}]\"\n"
                  f"\t\ttooltip = \"[{sgref(sg, 'BuildTooltip')}]\"\n"
                  f"\t\tonclick = \"[{sgref(sg, 'Execute')}]\"\n\t}}\n")
    else:
        action = ("\ttext_multi = {\n\t\tparentanchor = right\n\t\tposition = { -6 16 }\n"
                  "\t\tsize = { 110 0 }\n\t\tmax_width = 110\n\t\tautoresize = yes\n"
                  "\t\ttext = \"AOV_SPELL_CAST_FROM_PORTRAIT\"\n\t\tdefault_format = \"#weak\"\n\t}\n")
    on_cd = f"GetPlayer.MakeScope.Var( 'aov_spell_{k}_cd' ).IsSet"
    return (
        f"widget = {{\n"
        f'\tname = "aov_spell_card_{k}"\n'
        f"\tsize = {{ 480 88 }}\n"
        f'\ttooltip = "aov_spell_{k}_tt"\n\n'
        f'\ticon = {{\n\t\tposition = {{ 0 0 }}\n\t\tsize = {{ 290 64 }}\n\t\ttexture = "{ART_DIR}/spell_plate.dds"\n\t}}\n'
        + icon
        + f'\ticon = {{\n\t\tposition = {{ 0 0 }}\n\t\tsize = {{ 64 76 }}\n\t\ttexture = "{ART_DIR}/spell_frames.dds"\n'
          f"\t\tframesize = {{ 64 76 }}\n\t\tframe = {lvl + 1}\n\t}}\n\n"
        + text_at(72, 8, f"aov_spell_{k}", 205, "#T")
        + text_at(72, 38, f"aov_spell_{k}_facts", 280, "#weak")
        + text_at(72, 66, f"aov_spell_{k}_desc", 400, visible=f"[Not( {on_cd} )]")
        + text_at(72, 66, "AOV_SPELL_ON_COOLDOWN", 400, visible=f"[{on_cd}]")
        + "\n" + action
        + "}\n"
    )


def school_page(spells: list, c: str) -> str:
    sg = f"aov_study_{c}_sgui"
    header = (
        f"hbox = {{\n\tlayoutpolicy_horizontal = expanding\n\tmargin = {{ 6 4 }}\n\tspacing = 10\n\n"
        f'\ticon = {{\n\t\tsize = {{ 48 48 }}\n\t\ttexture = "{ART_DIR}/school_{c}.dds"\n\t}}\n\n'
        f"\tvbox = {{\n\t\tlayoutpolicy_horizontal = expanding\n\t\tspacing = 4\n\n"
        f"\t\thbox = {{\n\t\t\tlayoutpolicy_horizontal = expanding\n\t\t\tspacing = 6\n\n"
        f'\t\t\ttext_single = {{\n\t\t\t\ttext = "AOV_SCHOOL_{c.upper()}"\n\t\t\t\tusing = Font_Type_Flavor\n'
        f'\t\t\t\tusing = Font_Size_Medium\n\t\t\t\tdefault_format = "#T"\n\t\t\t\talign = left|nobaseline\n\t\t\t}}\n\n'
        + "".join(
            f'\t\t\ticon = {{\n\t\t\t\tvisible = "[EqualTo_CFixedPoint( GetPlayer.MakeScope.ScriptValue( \'aov_school_{c}_level\' ), \'(CFixedPoint){n}\' )]"\n'
            f'\t\t\t\tsize = {{ 30 29 }}\n\t\t\t\ttexture = "{ART_DIR}/levels_strip.dds"\n\t\t\t\tframesize = {{ 42 41 }}\n\t\t\t\tframe = {n}\n'
            f'\t\t\t\ttooltip = "AOV_SCHOOL_LEVEL_TT"\n\t\t\t}}\n' for n in (1, 2, 3))
        + f"\n\t\t\texpand = {{}}\n\t\t}}\n\n"
        f"\t\thbox = {{\n\t\t\tlayoutpolicy_horizontal = expanding\n\t\t\tspacing = 8\n\n"
        f"\t\t\tprogressbar_standard = {{\n\t\t\t\tsize = {{ 200 14 }}\n\t\t\t\tmin = 0\n\t\t\t\tmax = 100\n"
        f"\t\t\t\tvalue = \"[FixedPointToFloat( GetPlayer.MakeScope.ScriptValue( 'aov_school_{c}_percent' ) )]\"\n"
        f'\t\t\t\ttooltip = "AOV_SCHOOL_{c.upper()}_PROGRESS_TT"\n\t\t\t}}\n\n'
        f'\t\t\ttext_single = {{\n\t\t\t\ttext = "AOV_SCHOOL_{c.upper()}_PROGRESS"\n\t\t\t\talign = left|nobaseline\n\t\t\t}}\n\n'
        f"\t\t\texpand = {{}}\n\t\t}}\n\t}}\n\n"
        f"\tbutton_standard = {{\n\t\tsize = {{ 140 32 }}\n"
        f"\t\ttext = \"[SelectLocalization( {sgref(sg, 'IsShown')}, 'AOV_STUDYING', 'AOV_STUDY_THIS_SCHOOL' )]\"\n"
        f"\t\tdown = \"[{sgref(sg, 'IsShown')}]\"\n"
        f"\t\tenabled = \"[{sgref(sg, 'IsValid')}]\"\n"
        f"\t\ttooltip = \"[{sgref(sg, 'BuildTooltip')}]\"\n"
        f"\t\tonclick = \"[{sgref(sg, 'Execute')}]\"\n\t}}\n}}\n"
    )
    cards = "\n".join(card(s) for s in of_school(spells, c))
    pad = lambda t, n: "".join(("\t" * n + l) if l.strip() else l for l in t.splitlines(True))  # noqa: E731
    return (f"\ttype aov_magic_school_{c} = vbox {{\n\t\tlayoutpolicy_horizontal = expanding\n\t\tspacing = 6\n\n"
            + pad(header, 2) + "\n" + pad(cards, 2) + "\t}\n")


def gui(spells: list) -> str:
    return (HEADER + "\ntypes AovMagic\n{\n"
            + "\n".join(school_page(spells, c) for c in SCHOOLS) + "}\n")


def loc(spells: list) -> str:
    out = ["l_english:", " # " + HEADER.strip("# \n")]
    for s in spells:
        k = s["key"]
        out.append(f' aov_spell_{k}: "{s["name"]}"')
        out.append(f' aov_spell_{k}_desc: "{s["desc"]}"')
        out.append(f' aov_spell_{k}_flavour: "#F {s["flavour"]}#!"')
        effects_text = (f"[GetModifier('aov_spell_{k}').GetDescWithEffects]" if lasting(s) else f"$aov_spell_{k}_desc$")
        out.append(f' aov_spell_{k}_tt: "#T $aov_spell_{k}$#!\\n#weak $AOV_SCHOOL_{s["school"].upper()}$, $aov_spell_{k}_facts$#!'
                   f'\\n\\n{effects_text}\\n\\n$aov_spell_{k}_flavour$"')
        player = "GetPlayer.MakeScope.ScriptValue"
        cost = f"#V [{player}('aov_spell_{k}_cost')|0]#!"
        years = f"#V [{player}('aov_spell_{k}_years')|0]#!"
        out.append(f' aov_spell_{k}_facts: "Level {s["level"]} · {cost} mana · {TYPE_LABEL[s["type"]]} · {years} yr"')
        out.append(f' aov_spell_{k}_req_mana: "Has at least {cost} mana"')
        out.append(f' aov_spell_{k}_cost_tt: "Costs {cost} mana"')
        if s["interaction"] == f"aov_spell_{k}_interaction":
            out.append(f' aov_spell_{k}_interaction: "Cast {s["name"]}"')
            out.append(f' aov_spell_{k}_interaction_desc: "{s["desc"]}"')
    out.append("")
    for c in SCHOOLS:
        for lvl in range(4):
            out.append(f' AOV_SPELL_REQ_{c.upper()}_{lvl}: "Knows $AOV_SCHOOL_{c.upper()}$ at level {lvl} or higher"')
    return "\n".join(out) + "\n"


def render_all(spells: list) -> dict:
    return {
        "common/modifiers/aov_spell_modifiers.txt": modifiers(spells),
        "common/script_values/aov_spell_values.txt": values(spells),
        "common/scripted_triggers/aov_spell_triggers.txt": triggers(spells),
        "common/scripted_effects/aov_spell_effects.txt": effects(spells),
        "common/scripted_guis/aov_spell_sgui.txt": sguis(spells),
        "common/character_interactions/aov_spell_interactions.txt": interactions(spells),
        "gui/aov_magic_generated.gui": gui(spells),
        "localization/english/aov_spells_l_english.yml": loc(spells),
    }


def write_all(files: dict, root: Path) -> None:
    for rel, text in files.items():
        out = root / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\xef\xbb\xbf" + text.replace("\r\n", "\n").encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--eu4", type=Path, default=DEFAULT_EU4)
    args = parser.parse_args()
    try:
        spells = load_spells()
        validate(spells)
        files = render_all(spells)
        write_all(files, SUBMOD)
        copy_art(args.eu4, SUBMOD)
    except GeneratorError as e:
        sys.exit(f"error: {e}")
    print(f"wrote {len(files)} files for {len(spells)} spells; copied {len(ART) + 1} art files")


if __name__ == "__main__":
    main()
